// ============================================================================
// Generated from t27 spec: avs_controller_96
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module avs_controller_96 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] PINS_96 = 96;
    parameter [15:0] VOLTAGE_MIN_MV = 700;
    parameter [15:0] VOLTAGE_MAX_MV = 1300;
    parameter [15:0] VOLTAGE_STEP_MV = 5;
    parameter [7:0] VOLTAGE_LEVELS = 121;
    parameter [15:0] TARGET_MV = 1000;
    parameter [15:0] HYSTERESIS_MV = 15;
    parameter [15:0] SETTLING_US = 80;
    parameter [7:0] CONTROL_PIN_OFFSET = 64;
    parameter [7:0] CONTROL_PIN_COUNT = 7;
    parameter [31:0] FREQ_MIN_KHZ = 10000;
    parameter [31:0] FREQ_MAX_KHZ = 200000;
    parameter DUAL_CHANNEL = 1'b1;
    parameter [7:0] CHANNEL_PIN_GROUPS = 2;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum AvsChannel
    localparam AvsChannel_channel0 = 0;
    localparam AvsChannel_channel1 = 1;
    localparam AvsChannel_both = 2;
    // enum AvsState
    localparam AvsState_disabled = 0;
    localparam AvsState_enabled = 1;
    localparam AvsState_adjusting = 2;
    localparam AvsState_settled = 3;
    localparam AvsState_fault = 4;
    localparam AvsState_calibrating = 5;
    // enum AvsMode
    localparam AvsMode_manual = 0;
    localparam AvsMode_automatic = 1;
    localparam AvsMode_adaptive = 2;
    localparam AvsMode_dual_independent = 3;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct AvsChannelConfig
    reg [31:0] avschannelconfig_channel; // AvsChannelConfig.channel
    reg avschannelconfig_enabled; // AvsChannelConfig.enabled
    reg [15:0] avschannelconfig_target_mv; // AvsChannelConfig.target_mv
    reg [15:0] avschannelconfig_current_mv; // AvsChannelConfig.current_mv
    reg [7:0] avschannelconfig_level; // AvsChannelConfig.level
    // struct AvsPinConfig
    reg [7:0] avspinconfig_pin_index; // AvsPinConfig.pin_index
    reg avspinconfig_is_output; // AvsPinConfig.is_output
    reg [7:0] avspinconfig_function; // AvsPinConfig.function
    // struct AvsVoltageLevel
    reg [7:0] avsvoltagelevel_level; // AvsVoltageLevel.level
    reg [15:0] avsvoltagelevel_voltage_mv; // AvsVoltageLevel.voltage_mv
    reg [7:0] avsvoltagelevel_control_code; // AvsVoltageLevel.control_code
    // struct AvsStatus
    reg [31:0] avsstatus_state; // AvsStatus.state
    reg [31:0] avsstatus_mode; // AvsStatus.mode
    reg [31:0] avsstatus_channel0; // AvsStatus.channel0
    reg [31:0] avsstatus_channel1; // AvsStatus.channel1
    reg [7:0] avsstatus_fault_code; // AvsStatus.fault_code
    reg avsstatus_calibration_complete; // AvsStatus.calibration_complete
    // struct AvsConfig
    reg [31:0] avsconfig_mode; // AvsConfig.mode
    reg [15:0] avsconfig_min_mv; // AvsConfig.min_mv
    reg [15:0] avsconfig_max_mv; // AvsConfig.max_mv
    reg [15:0] avsconfig_target_mv; // AvsConfig.target_mv
    reg [15:0] avsconfig_hysteresis_mv; // AvsConfig.hysteresis_mv
    reg [15:0] avsconfig_settling_us; // AvsConfig.settling_us
    reg avsconfig_enable_dual_channel; // AvsConfig.enable_dual_channel
    // struct 
    reg [7:0] _opcode; // .opcode
    reg [7:0] _level; // .level
    reg [7:0] _channel; // .channel

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: avs_voltage_from_level
    function [15:0] avs_voltage_from_level; // -> u16
        input [7:0] level;
        begin
            avs_voltage_from_level = (VOLTAGE_MIN_MV + (@as(u16, level) * VOLTAGE_STEP_MV));
        end
    endfunction

    // function: avs_level_from_voltage
    function [7:0] avs_level_from_voltage; // -> u8
        input [15:0] voltage_mv;
        begin
            if ((voltage_mv < VOLTAGE_MIN_MV)) begin
                mv = VOLTAGE_MIN_MV;
            end else if ((voltage_mv > VOLTAGE_MAX_MV)) begin
                mv = VOLTAGE_MAX_MV;
            end
            avs_level_from_voltage = @as(u8, ((voltage_mv - VOLTAGE_MIN_MV) / VOLTAGE_STEP_MV));
        end
    endfunction

    // function: avs_control_code_from_level
    function [7:0] avs_control_code_from_level; // -> u8
        input [7:0] level;
        begin
            avs_control_code_from_level = (level && 8'h7F);
        end
    endfunction

    // function: avs_level_from_control_code
    function [7:0] avs_level_from_control_code; // -> u8
        input [7:0] code;
        begin
            avs_level_from_control_code = (code && 8'h7F);
        end
    endfunction

    // function: avs_voltage_valid
    function avs_voltage_valid; // -> bool
        input [15:0] voltage_mv;
        begin
            avs_voltage_valid = ((voltage_mv >= VOLTAGE_MIN_MV) && (voltage_mv <= VOLTAGE_MAX_MV));
        end
    endfunction

    // function: avs_voltage_in_hysteresis
    function avs_voltage_in_hysteresis; // -> bool
        input [15:0] current_mv;
        input [15:0] target_mv;
        input [15:0] hysteresis_mv;
        begin
            if ((current_mv > target_mv)) begin
                avs_voltage_in_hysteresis = ((current_mv - target_mv) <= hysteresis_mv);
            end else begin
                avs_voltage_in_hysteresis = ((target_mv - current_mv) <= hysteresis_mv);
            end
        end
    endfunction

    // function: avs_should_adjust
    function avs_should_adjust; // -> bool
        input [15:0] current_mv;
        input [15:0] target_mv;
        input [15:0] hysteresis_mv;
        begin
            avs_should_adjust = not;
            avs_voltage_in_hysteresis(current_mv, target_mv, hysteresis_mv);
        end
    endfunction

    // function: avs_config_init
    function [31:0] avs_config_init; // -> AvsConfig
        begin
            avs_config_init = 0 /* AvsConfig {...} */;
        end
    endfunction

    // function: avs_config_dual
    function [31:0] avs_config_dual; // -> AvsConfig
        input [15:0] target0_mv;
        input [15:0] target1_mv;
        begin
            avs_config_dual = 0 /* AvsConfig {...} */;
        end
    endfunction

    // function: avs_config_adaptive
    function [31:0] avs_config_adaptive; // -> AvsConfig
        input [15:0] min_mv;
        input [15:0] max_mv;
        begin
            avs_config_adaptive = 0 /* AvsConfig {...} */;
        end
    endfunction

    // function: avs_channel_init
    function [31:0] avs_channel_init; // -> AvsChannelConfig
        input [31:0] channel;
        begin
            avs_channel_init = 0 /* AvsChannelConfig {...} */;
        end
    endfunction

    // function: avs_channel_enable
    function [31:0] avs_channel_enable; // -> AvsChannelConfig
        input [31:0] channel;
        input [15:0] target_mv;
        begin
            avs_channel_enable = 0 /* AvsChannelConfig {...} */;
        end
    endfunction

    // function: avs_channel_adjust
    function [31:0] avs_channel_adjust; // -> AvsChannelConfig
        input [31:0] channel;
        input [7:0] new_level;
        begin
            reg [31:0] new_mv = avs_voltage_from_level(new_level);
            avs_channel_adjust = 0 /* AvsChannelConfig {...} */;
        end
    endfunction

    // function: avs_status_init
    function [31:0] avs_status_init; // -> AvsStatus
        begin
            avs_status_init = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_enable
    function [31:0] avs_status_enable; // -> AvsStatus
        input [31:0] status;
        input [31:0] config;
        begin
            reg [31:0] ch0 = status_channel0;
            reg [31:0] ch1 = status_channel1;
            if (config_enable_dual_channel) begin
                ch0 = avs_channel_enable(ch0, config_target_mv);
                ch1 = avs_channel_enable(ch1, config_target_mv);
            end else begin
                ch0 = avs_channel_enable(ch0, config_target_mv);
            end
            avs_status_enable = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_calibrate
    function [31:0] avs_status_calibrate; // -> AvsStatus
        input [31:0] status;
        begin
            avs_status_calibrate = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_calibration_complete
    function [31:0] avs_status_calibration_complete; // -> AvsStatus
        input [31:0] status;
        begin
            avs_status_calibration_complete = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_fault
    function [31:0] avs_status_fault; // -> AvsStatus
        input [31:0] status;
        input [7:0] fault_code;
        begin
            avs_status_fault = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_control_pins_start
    function [7:0] avs_control_pins_start; // -> u8
        begin
            avs_control_pins_start = CONTROL_PIN_OFFSET;
        end
    endfunction

    // function: avs_control_pins_end
    function [7:0] avs_control_pins_end; // -> u8
        begin
            avs_control_pins_end = ((CONTROL_PIN_OFFSET + CONTROL_PIN_COUNT) - 1);
        end
    endfunction

    // function: avs_control_pins_secondary_start
    function [7:0] avs_control_pins_secondary_start; // -> u8
        begin
            avs_control_pins_secondary_start = (CONTROL_PIN_OFFSET + CONTROL_PIN_COUNT);
        end
    endfunction

    // function: avs_control_pins_secondary_end
    function [7:0] avs_control_pins_secondary_end; // -> u8
        begin
            avs_control_pins_secondary_end = ((avs_control_pins_secondary_start() + CONTROL_PIN_COUNT) - 1);
        end
    endfunction

    // function: avs_is_control_pin
    function avs_is_control_pin; // -> bool
        input [7:0] pin_index;
        begin
            avs_is_control_pin = (avs_is_control_pin_primary(pin_index) || avs_is_control_pin_secondary(pin_index));
        end
    endfunction

    // function: avs_is_control_pin_primary
    function avs_is_control_pin_primary; // -> bool
        input [7:0] pin_index;
        begin
            avs_is_control_pin_primary = ((pin_index >= avs_control_pins_start()) && (pin_index <= avs_control_pins_end()));
        end
    endfunction

    // function: avs_is_control_pin_secondary
    function avs_is_control_pin_secondary; // -> bool
        input [7:0] pin_index;
        begin
            avs_is_control_pin_secondary = ((pin_index >= avs_control_pins_secondary_start()) && (pin_index <= avs_control_pins_secondary_end()));
        end
    endfunction

    // function: avs_control_pin_for_bit
    function [7:0] avs_control_pin_for_bit; // -> u8
        input [7:0] bit_index;
        input [31:0] channel;
        begin
            if ((bit_index >= CONTROL_PIN_COUNT)) begin
                bit_index = 0;
            end
            if ((channel == AvsChannel_channel1)) begin
                avs_control_pin_for_bit = (avs_control_pins_secondary_start() + bit_index);
            end else begin
                avs_control_pin_for_bit = (avs_control_pins_start() + bit_index);
            end
        end
    endfunction

    // function: encode_avs_96_cmd
    function [15:0] encode_avs_96_cmd; // -> u16
        input [7:0] opcode;
        input [7:0] level;
        input [7:0] channel;
        begin
            reg [15:0] op_field = (@as(u16, opcode) << 8);
            reg [15:0] level_field = (@as(u16, (level && 8'h7F)) << 1);
            reg [15:0] channel_field = @as(u16, (channel && 8'h01));
            encode_avs_96_cmd = ((op_field || level_field) || channel_field);
        end
    endfunction
endmodule

`default_nettype wire
