// ============================================================================
// Generated from t27 spec: avs_controller_48
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module avs_controller_48 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] PINS_48 = 48;
    parameter [15:0] VOLTAGE_MIN_MV = 800;
    parameter [15:0] VOLTAGE_MAX_MV = 1200;
    parameter [15:0] VOLTAGE_STEP_MV = 10;
    parameter [7:0] VOLTAGE_LEVELS = 41;
    parameter [15:0] TARGET_MV = 1000;
    parameter [15:0] HYSTERESIS_MV = 20;
    parameter [15:0] SETTLING_US = 100;
    parameter [7:0] CONTROL_PIN_OFFSET = 16;
    parameter [7:0] CONTROL_PIN_COUNT = 6;
    parameter [31:0] FREQ_MIN_KHZ = 10000;
    parameter [31:0] FREQ_MAX_KHZ = 100000;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum AvsState
    localparam AvsState_disabled = 0;
    localparam AvsState_enabled = 1;
    localparam AvsState_adjusting = 2;
    localparam AvsState_settled = 3;
    localparam AvsState_fault = 4;
    // enum AvsMode
    localparam AvsMode_manual = 0;
    localparam AvsMode_automatic = 1;
    localparam AvsMode_adaptive = 2;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct AvsPinConfig
    reg [7:0] avspinconfig_pin_index; // AvsPinConfig.pin_index
    reg avspinconfig_is_output; // AvsPinConfig.is_output
    reg [7:0] avspinconfig_function; // AvsPinConfig.function
    // struct AvsVoltageLevel
    reg [7:0] avsvoltagelevel_level; // AvsVoltageLevel.level
    reg [15:0] avsvoltagelevel_voltage_mv; // AvsVoltageLevel.voltage_mv
    reg [7:0] avsvoltagelevel_control_code; // AvsVoltageLevel.control_code
    // struct AvsStatus
    reg [31:0] avsstatus_state; // AvsStatus.state
    reg [31:0] avsstatus_mode; // AvsStatus.mode
    reg [15:0] avsstatus_current_mv; // AvsStatus.current_mv
    reg [15:0] avsstatus_target_mv; // AvsStatus.target_mv
    reg [7:0] avsstatus_level; // AvsStatus.level
    reg [7:0] avsstatus_fault_code; // AvsStatus.fault_code
    // struct AvsConfig
    reg [31:0] avsconfig_mode; // AvsConfig.mode
    reg [15:0] avsconfig_min_mv; // AvsConfig.min_mv
    reg [15:0] avsconfig_max_mv; // AvsConfig.max_mv
    reg [15:0] avsconfig_target_mv; // AvsConfig.target_mv
    reg [15:0] avsconfig_hysteresis_mv; // AvsConfig.hysteresis_mv
    reg [15:0] avsconfig_settling_us; // AvsConfig.settling_us
    // struct 
    reg [7:0] _opcode; // .opcode
    reg [7:0] _level; // .level
    reg [7:0] _reserved; // .reserved

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: avs_voltage_from_level
    function [15:0] avs_voltage_from_level; // -> u16
        input [7:0] level;
        begin
            avs_voltage_from_level = (VOLTAGE_MIN_MV + (@as(u16, level) * VOLTAGE_STEP_MV));
        end
    endfunction

    // function: avs_level_from_voltage
    function [7:0] avs_level_from_voltage; // -> u8
        input [15:0] voltage_mv;
        begin
            if ((voltage_mv < VOLTAGE_MIN_MV)) begin
                mv = VOLTAGE_MIN_MV;
            end else if ((voltage_mv > VOLTAGE_MAX_MV)) begin
                mv = VOLTAGE_MAX_MV;
            end
            avs_level_from_voltage = @as(u8, ((voltage_mv - VOLTAGE_MIN_MV) / VOLTAGE_STEP_MV));
        end
    endfunction

    // function: avs_control_code_from_level
    function [7:0] avs_control_code_from_level; // -> u8
        input [7:0] level;
        begin
            avs_control_code_from_level = (level && 8'h3F);
        end
    endfunction

    // function: avs_level_from_control_code
    function [7:0] avs_level_from_control_code; // -> u8
        input [7:0] code;
        begin
            avs_level_from_control_code = (code && 8'h3F);
        end
    endfunction

    // function: avs_voltage_valid
    function avs_voltage_valid; // -> bool
        input [15:0] voltage_mv;
        begin
            avs_voltage_valid = ((voltage_mv >= VOLTAGE_MIN_MV) && (voltage_mv <= VOLTAGE_MAX_MV));
        end
    endfunction

    // function: avs_voltage_in_hysteresis
    function avs_voltage_in_hysteresis; // -> bool
        input [15:0] current_mv;
        input [15:0] target_mv;
        input [15:0] hysteresis_mv;
        begin
            if ((current_mv > target_mv)) begin
                avs_voltage_in_hysteresis = ((current_mv - target_mv) <= hysteresis_mv);
            end else begin
                avs_voltage_in_hysteresis = ((target_mv - current_mv) <= hysteresis_mv);
            end
        end
    endfunction

    // function: avs_should_adjust
    function avs_should_adjust; // -> bool
        input [15:0] current_mv;
        input [15:0] target_mv;
        input [15:0] hysteresis_mv;
        begin
            avs_should_adjust = not;
            avs_voltage_in_hysteresis(current_mv, target_mv, hysteresis_mv);
        end
    endfunction

    // function: avs_config_init
    function [31:0] avs_config_init; // -> AvsConfig
        begin
            avs_config_init = 0 /* AvsConfig {...} */;
        end
    endfunction

    // function: avs_config_manual
    function [31:0] avs_config_manual; // -> AvsConfig
        input [15:0] target_mv;
        begin
            avs_config_manual = 0 /* AvsConfig {...} */;
        end
    endfunction

    // function: avs_config_adaptive
    function [31:0] avs_config_adaptive; // -> AvsConfig
        input [15:0] min_mv;
        input [15:0] max_mv;
        begin
            avs_config_adaptive = 0 /* AvsConfig {...} */;
        end
    endfunction

    // function: avs_status_init
    function [31:0] avs_status_init; // -> AvsStatus
        begin
            avs_status_init = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_enable
    function [31:0] avs_status_enable; // -> AvsStatus
        input [31:0] status;
        input [31:0] config;
        begin
            avs_status_enable = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_adjust
    function [31:0] avs_status_adjust; // -> AvsStatus
        input [31:0] status;
        input [7:0] new_level;
        begin
            reg [31:0] new_mv = avs_voltage_from_level(new_level);
            avs_status_adjust = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_settled
    function [31:0] avs_status_settled; // -> AvsStatus
        input [31:0] status;
        input [15:0] measured_mv;
        begin
            avs_status_settled = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_status_fault
    function [31:0] avs_status_fault; // -> AvsStatus
        input [31:0] status;
        input [7:0] fault_code;
        begin
            avs_status_fault = 0 /* AvsStatus {...} */;
        end
    endfunction

    // function: avs_control_pins_start
    function [7:0] avs_control_pins_start; // -> u8
        begin
            avs_control_pins_start = CONTROL_PIN_OFFSET;
        end
    endfunction

    // function: avs_control_pins_end
    function [7:0] avs_control_pins_end; // -> u8
        begin
            avs_control_pins_end = ((CONTROL_PIN_OFFSET + CONTROL_PIN_COUNT) - 1);
        end
    endfunction

    // function: avs_is_control_pin
    function avs_is_control_pin; // -> bool
        input [7:0] pin_index;
        begin
            avs_is_control_pin = ((pin_index >= avs_control_pins_start()) && (pin_index <= avs_control_pins_end()));
        end
    endfunction

    // function: avs_control_pin_for_bit
    function [7:0] avs_control_pin_for_bit; // -> u8
        input [7:0] bit_index;
        begin
            if ((bit_index >= CONTROL_PIN_COUNT)) begin
                avs_control_pin_for_bit = CONTROL_PIN_OFFSET;
            end
            avs_control_pin_for_bit = (CONTROL_PIN_OFFSET + bit_index);
        end
    endfunction

    // function: encode_avs_48_cmd
    function [15:0] encode_avs_48_cmd; // -> u16
        input [7:0] opcode;
        input [7:0] level;
        input [7:0] reserved;
        begin
            reg [15:0] op_field = (@as(u16, opcode) << 8);
            reg [15:0] level_field = (@as(u16, (level && 8'h3F)) << 2);
            reg [15:0] res_field = @as(u16, (reserved && 8'h03));
            encode_avs_48_cmd = ((op_field || level_field) || res_field);
        end
    endfunction
endmodule

`default_nettype wire
