// ============================================================================
// Generated from t27 spec: avs_reconf
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module avs_reconf (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] RECONF_OPCODE_BASE = 8'hF0;
    parameter [7:0] RECONF_OP_SET_VOLTAGE = 8'h00;
    parameter [7:0] RECONF_OP_SET_FREQUENCY = 8'h01;
    parameter [7:0] RECONF_OP_SET_MODE = 8'h02;
    parameter [7:0] RECONF_OP_RESET = 8'h03;
    parameter [7:0] RECONF_OP_QUERY = 8'h04;
    parameter [7:0] RECONF_OP_SAVE_CONFIG = 8'h05;
    parameter [7:0] RECONF_OP_LOAD_CONFIG = 8'h06;
    parameter [7:0] RECONF_OP_CALIBRATE = 8'h07;
    parameter [7:0] RECONF_OP_MAX = 8'h08;
    parameter [7:0] RECONF_MODE_MANUAL = 0;
    parameter [7:0] RECONF_MODE_AUTOMATIC = 1;
    parameter [7:0] RECONF_MODE_PERFORMANCE = 2;
    parameter [7:0] RECONF_MODE_POWER_SAVING = 3;
    parameter [7:0] RECONF_MODE_ADAPTIVE = 4;
    parameter [7:0] RECONF_MODE_MAX = 5;
    parameter [7:0] RECONF_STATE_IDLE = 0;
    parameter [7:0] RECONF_STATE_BUSY = 1;
    parameter [7:0] RECONF_STATE_ERROR = 2;
    parameter [7:0] RECONF_STATE_CALIBRATING = 3;
    parameter [15:0] VOLTAGE_MIN_MV = 700;
    parameter [15:0] VOLTAGE_MAX_MV = 1300;
    parameter [31:0] FREQ_MIN_KHZ = 10000;
    parameter [31:0] FREQ_MAX_KHZ = 200000;
    parameter [15:0] RECONF_TIMEOUT_MS = 1000;
    parameter [7:0] RECONF_RETRY_COUNT = 3;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum ReconfOp
    localparam ReconfOp_set_voltage = RECONF_OP_SET_VOLTAGE;
    localparam ReconfOp_set_frequency = RECONF_OP_SET_FREQUENCY;
    localparam ReconfOp_set_mode = RECONF_OP_SET_MODE;
    localparam ReconfOp_reset = RECONF_OP_RESET;
    localparam ReconfOp_query = RECONF_OP_QUERY;
    localparam ReconfOp_save_config = RECONF_OP_SAVE_CONFIG;
    localparam ReconfOp_load_config = RECONF_OP_LOAD_CONFIG;
    localparam ReconfOp_calibrate = RECONF_OP_CALIBRATE;
    // enum ReconfMode
    localparam ReconfMode_manual = RECONF_MODE_MANUAL;
    localparam ReconfMode_automatic = RECONF_MODE_AUTOMATIC;
    localparam ReconfMode_performance = RECONF_MODE_PERFORMANCE;
    localparam ReconfMode_power_saving = RECONF_MODE_POWER_SAVING;
    localparam ReconfMode_adaptive = RECONF_MODE_ADAPTIVE;
    // enum ReconfState
    localparam ReconfState_idle = RECONF_STATE_IDLE;
    localparam ReconfState_busy = RECONF_STATE_BUSY;
    localparam ReconfState_error = RECONF_STATE_ERROR;
    localparam ReconfState_calibrating = RECONF_STATE_CALIBRATING;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct ReconfConfig
    reg [31:0] reconfconfig_mode; // ReconfConfig.mode
    reg [15:0] reconfconfig_voltage_mv; // ReconfConfig.voltage_mv
    reg [31:0] reconfconfig_freq_khz; // ReconfConfig.freq_khz
    reg reconfconfig_auto_scale; // ReconfConfig.auto_scale
    reg [15:0] reconfconfig_min_voltage_mv; // ReconfConfig.min_voltage_mv
    reg [15:0] reconfconfig_max_voltage_mv; // ReconfConfig.max_voltage_mv
    reg [31:0] reconfconfig_min_freq_khz; // ReconfConfig.min_freq_khz
    reg [31:0] reconfconfig_max_freq_khz; // ReconfConfig.max_freq_khz
    // struct ReconfStatus
    reg [31:0] reconfstatus_state; // ReconfStatus.state
    reg [15:0] reconfstatus_current_voltage_mv; // ReconfStatus.current_voltage_mv
    reg [31:0] reconfstatus_current_freq_khz; // ReconfStatus.current_freq_khz
    reg [31:0] reconfstatus_last_op; // ReconfStatus.last_op
    reg [7:0] reconfstatus_error_code; // ReconfStatus.error_code
    reg [7:0] reconfstatus_retry_count; // ReconfStatus.retry_count
    // struct ReconfCommand
    reg [31:0] reconfcommand_op; // ReconfCommand.op
    reg [31:0] reconfcommand_param1; // ReconfCommand.param1
    reg [31:0] reconfcommand_param2; // ReconfCommand.param2
    reg [15:0] reconfcommand_timeout_ms; // ReconfCommand.timeout_ms
    // struct ReconfResult
    reg reconfresult_success; // ReconfResult.success
    reg [7:0] reconfresult_error_code; // ReconfResult.error_code
    reg [31:0] reconfresult_cycles_taken; // ReconfResult.cycles_taken
    // struct 
    reg [7:0] _op; // .op
    reg [15:0] _param1; // .param1
    reg [15:0] _param2; // .param2

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: avs_reconf_config_init
    function [31:0] avs_reconf_config_init; // -> ReconfConfig
        begin
            avs_reconf_config_init = 0 /* ReconfConfig {...} */;
        end
    endfunction

    // function: avs_reconf_config_performance
    function [31:0] avs_reconf_config_performance; // -> ReconfConfig
        begin
            avs_reconf_config_performance = 0 /* ReconfConfig {...} */;
        end
    endfunction

    // function: avs_reconf_config_power_saving
    function [31:0] avs_reconf_config_power_saving; // -> ReconfConfig
        begin
            avs_reconf_config_power_saving = 0 /* ReconfConfig {...} */;
        end
    endfunction

    // function: avs_reconf_config_adaptive
    function [31:0] avs_reconf_config_adaptive; // -> ReconfConfig
        begin
            avs_reconf_config_adaptive = 0 /* ReconfConfig {...} */;
        end
    endfunction

    // function: avs_reconf_voltage_valid
    function avs_reconf_voltage_valid; // -> bool
        input [15:0] voltage_mv;
        begin
            avs_reconf_voltage_valid = ((voltage_mv >= VOLTAGE_MIN_MV) && (voltage_mv <= VOLTAGE_MAX_MV));
        end
    endfunction

    // function: avs_reconf_freq_valid
    function avs_reconf_freq_valid; // -> bool
        input [31:0] freq_khz;
        begin
            avs_reconf_freq_valid = ((freq_khz >= FREQ_MIN_KHZ) && (freq_khz <= FREQ_MAX_KHZ));
        end
    endfunction

    // function: avs_reconf_config_valid
    function avs_reconf_config_valid; // -> bool
        input [31:0] config;
        begin
            avs_reconf_config_valid = (((avs_reconf_voltage_valid(config_voltage_mv) && avs_reconf_freq_valid(config_freq_khz)) && (config_min_voltage_mv < config_max_voltage_mv)) && (config_min_freq_khz < config_max_freq_khz));
        end
    endfunction

    // function: avs_reconf_status_init
    function [31:0] avs_reconf_status_init; // -> ReconfStatus
        begin
            avs_reconf_status_init = 0 /* ReconfStatus {...} */;
        end
    endfunction

    // function: avs_reconf_status_start_op
    function [31:0] avs_reconf_status_start_op; // -> ReconfStatus
        input [31:0] status;
        input [31:0] op;
        begin
            avs_reconf_status_start_op = 0 /* ReconfStatus {...} */;
        end
    endfunction

    // function: avs_reconf_status_complete
    function [31:0] avs_reconf_status_complete; // -> ReconfStatus
        input [31:0] status;
        input [31:0] result;
        begin
            reg [31:0] new_state = (result_success) ? (ReconfState_idle) : (ReconfState_error);
            reg [31:0] new_retry_count = (result_success) ? (0) : ((status_retry_count + 1));
            avs_reconf_status_complete = 0 /* ReconfStatus {...} */;
        end
    endfunction

    // function: avs_reconf_status_update_voltage
    function [31:0] avs_reconf_status_update_voltage; // -> ReconfStatus
        input [31:0] status;
        input [15:0] voltage_mv;
        begin
            avs_reconf_status_update_voltage = 0 /* ReconfStatus {...} */;
        end
    endfunction

    // function: avs_reconf_status_update_freq
    function [31:0] avs_reconf_status_update_freq; // -> ReconfStatus
        input [31:0] status;
        input [31:0] freq_khz;
        begin
            avs_reconf_status_update_freq = 0 /* ReconfStatus {...} */;
        end
    endfunction

    // function: avs_reconf_command_init
    function [31:0] avs_reconf_command_init; // -> ReconfCommand
        begin
            avs_reconf_command_init = 0 /* ReconfCommand {...} */;
        end
    endfunction

    // function: avs_reconf_command_set_voltage
    function [31:0] avs_reconf_command_set_voltage; // -> ReconfCommand
        input [15:0] voltage_mv;
        begin
            avs_reconf_command_set_voltage = 0 /* ReconfCommand {...} */;
        end
    endfunction

    // function: avs_reconf_command_set_freq
    function [31:0] avs_reconf_command_set_freq; // -> ReconfCommand
        input [31:0] freq_khz;
        begin
            avs_reconf_command_set_freq = 0 /* ReconfCommand {...} */;
        end
    endfunction

    // function: avs_reconf_command_set_mode
    function [31:0] avs_reconf_command_set_mode; // -> ReconfCommand
        input [31:0] mode;
        begin
            avs_reconf_command_set_mode = 0 /* ReconfCommand {...} */;
        end
    endfunction

    // function: avs_reconf_command_calibrate
    function [31:0] avs_reconf_command_calibrate; // -> ReconfCommand
        begin
            avs_reconf_command_calibrate = 0 /* ReconfCommand {...} */;
        end
    endfunction

    // function: avs_reconf_command_save_config
    function [31:0] avs_reconf_command_save_config; // -> ReconfCommand
        input [31:0] config;
        begin
            avs_reconf_command_save_config = 0 /* ReconfCommand {...} */;
        end
    endfunction

    // function: avs_reconf_result_success
    function [31:0] avs_reconf_result_success; // -> ReconfResult
        input [31:0] cycles;
        begin
            avs_reconf_result_success = 0 /* ReconfResult {...} */;
        end
    endfunction

    // function: avs_reconf_result_error
    function [31:0] avs_reconf_result_error; // -> ReconfResult
        input [7:0] error_code;
        input [31:0] cycles;
        begin
            avs_reconf_result_error = 0 /* ReconfResult {...} */;
        end
    endfunction

    // function: avs_reconf_should_retry
    function avs_reconf_should_retry; // -> bool
        input [31:0] status;
        begin
            avs_reconf_should_retry = ((status_state == ReconfState_error) && (status_retry_count < RECONF_RETRY_COUNT));
        end
    endfunction

    // function: encode_avs_reconf_cmd
    function [31:0] encode_avs_reconf_cmd; // -> u32
        input [7:0] op;
        input [15:0] param1;
        input [15:0] param2;
        begin
            reg [31:0] op_field = (@as(u32, op) << 24);
            reg [31:0] param1_field = (@as(u32, (param1 && 12'hFFF)) << 12);
            reg [31:0] param2_field = @as(u32, (param2 && 12'hFFF));
            encode_avs_reconf_cmd = ((op_field || param1_field) || param2_field);
        end
    endfunction
endmodule

`default_nettype wire
