// ============================================================================
// Generated from t27 spec: sacred_drowsy_ret
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module sacred_drowsy_ret (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] OP_DROWSY_RET = 8'hEC;
    parameter [7:0] DROWSY_STATE_BITS = 3;
    parameter [7:0] RET_REASON_BITS = 3;
    parameter [7:0] DROWSY_ACTIVE = 0;
    parameter [7:0] DROWSY_LIGHT = 1;
    parameter [7:0] DROWSY_DEEP = 2;
    parameter [7:0] DROWSY_OFF = 3;
    parameter [7:0] DROWSY_HIBERNATE = 4;
    parameter [7:0] DROWSY_CRITICAL = 5;
    parameter [7:0] DROWSY_MAX = 6;
    parameter [7:0] RET_WAKE = 0;
    parameter [7:0] RET_TIMER = 1;
    parameter [7:0] RET_INTERRUPT = 2;
    parameter [7:0] RET_ERROR = 3;
    parameter [7:0] RET_POWER = 4;
    parameter [7:0] RET_MANUAL = 5;
    parameter [7:0] RET_MAX = 6;
    parameter [31:0] WAKE_CYCLES = 100;
    parameter [31:0] DEEP_WAKE_CYCLES = 1000;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum DrowsyState
    localparam DrowsyState_active = DROWSY_ACTIVE;
    localparam DrowsyState_light = DROWSY_LIGHT;
    localparam DrowsyState_deep = DROWSY_DEEP;
    localparam DrowsyState_off = DROWSY_OFF;
    localparam DrowsyState_hibernate = DROWSY_HIBERNATE;
    localparam DrowsyState_critical = DROWSY_CRITICAL;
    // enum RetReason
    localparam RetReason_wake = RET_WAKE;
    localparam RetReason_timer = RET_TIMER;
    localparam RetReason_interrupt = RET_INTERRUPT;
    localparam RetReason_error = RET_ERROR;
    localparam RetReason_power = RET_POWER;
    localparam RetReason_manual = RET_MANUAL;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct DrowsyConfig
    reg drowsyconfig_enable_light; // DrowsyConfig.enable_light
    reg drowsyconfig_enable_deep; // DrowsyConfig.enable_deep
    reg [31:0] drowsyconfig_light_threshold_ms; // DrowsyConfig.light_threshold_ms
    reg [31:0] drowsyconfig_deep_threshold_ms; // DrowsyConfig.deep_threshold_ms
    reg drowsyconfig_wake_irq_enable; // DrowsyConfig.wake_irq_enable
    // struct DrowsyStatus
    reg [31:0] drowsystatus_state; // DrowsyStatus.state
    reg [31:0] drowsystatus_last_wake_cycle; // DrowsyStatus.last_wake_cycle
    reg [31:0] drowsystatus_drowsy_duration; // DrowsyStatus.drowsy_duration
    reg [31:0] drowsystatus_wake_count; // DrowsyStatus.wake_count
    reg [31:0] drowsystatus_last_ret_reason; // DrowsyStatus.last_ret_reason
    // struct WakeCondition
    reg wakecondition_irq_pending; // WakeCondition.irq_pending
    reg wakecondition_timer_expired; // WakeCondition.timer_expired
    reg wakecondition_power_good; // WakeCondition.power_good
    reg wakecondition_manual_wake; // WakeCondition.manual_wake

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: drowsy_is_active
    function drowsy_is_active; // -> bool
        input [31:0] state;
        begin
            drowsy_is_active = (state == DrowsyState_active);
        end
    endfunction

    // function: drowsy_is_drowsy
    function drowsy_is_drowsy; // -> bool
        input [31:0] state;
        begin
            drowsy_is_drowsy = ((state == DrowsyState_light) || (state == DrowsyState_deep));
        end
    endfunction

    // function: drowsy_is_off
    function drowsy_is_off; // -> bool
        input [31:0] state;
        begin
            drowsy_is_off = ((state == DrowsyState_off) || (state == DrowsyState_hibernate));
        end
    endfunction

    // function: drowsy_is_critical
    function drowsy_is_critical; // -> bool
        input [31:0] state;
        begin
            drowsy_is_critical = (state == DrowsyState_critical);
        end
    endfunction

    // function: drowsy_can_enter_light
    function drowsy_can_enter_light; // -> bool
        input [31:0] state;
        begin
            drowsy_can_enter_light = (state == DrowsyState_active);
        end
    endfunction

    // function: drowsy_can_enter_deep
    function drowsy_can_enter_deep; // -> bool
        input [31:0] state;
        begin
            drowsy_can_enter_deep = (state == DrowsyState_light);
        end
    endfunction

    // function: drowsy_wake_cycles
    function [31:0] drowsy_wake_cycles; // -> u32
        input [31:0] state;
        // TODO: implement
    endfunction
endmodule

`default_nettype wire
