// ============================================================================
// Generated from t27 spec: fbb_active_path
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module fbb_active_path (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] FBB_OPCODE_BASE = 8'hD0;
    parameter [7:0] FBB_OP_PATH_SELECT = 8'h00;
    parameter [7:0] FBB_OP_PATH_ENABLE = 8'h01;
    parameter [7:0] FBB_OP_PATH_DISABLE = 8'h02;
    parameter [7:0] FBB_OP_PATH_STATUS = 8'h03;
    parameter [7:0] FBB_OP_PATH_RESET = 8'h04;
    parameter [7:0] FBB_OP_PATH_BYPASS = 8'h05;
    parameter [7:0] FBB_OP_PATH_LOOPBACK = 8'h06;
    parameter [7:0] FBB_OP_PATH_CONFIG = 8'h07;
    parameter [7:0] FBB_OP_MAX = 8'h08;
    parameter [7:0] FBB_PATH_COUNT = 8;
    parameter [7:0] FBB_MAX_PATHS = 8;
    parameter [7:0] FBB_PATH_STATE_DISABLED = 0;
    parameter [7:0] FBB_PATH_STATE_ENABLED = 1;
    parameter [7:0] FBB_PATH_STATE_ACTIVE = 2;
    parameter [7:0] FBB_PATH_STATE_ERROR = 3;
    parameter [7:0] FBB_PATH_STATE_BYPASSED = 4;
    parameter [7:0] FBB_PATH_STATE_MAX = 5;
    parameter [7:0] FBB_LATENCY_MIN_CYCLES = 1;
    parameter [7:0] FBB_LATENCY_MAX_CYCLES = 16;
    parameter [7:0] FBB_DEFAULT_LATENCY = 4;
    parameter [31:0] FBB_BANDWIDTH_MIN_MBPS = 100;
    parameter [31:0] FBB_BANDWIDTH_MAX_MBPS = 10000;
    parameter [31:0] FBB_DEFAULT_BANDWIDTH = 1000;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum FbbOp
    localparam FbbOp_path_select = FBB_OP_PATH_SELECT;
    localparam FbbOp_path_enable = FBB_OP_PATH_ENABLE;
    localparam FbbOp_path_disable = FBB_OP_PATH_DISABLE;
    localparam FbbOp_path_status = FBB_OP_PATH_STATUS;
    localparam FbbOp_path_reset = FBB_OP_PATH_RESET;
    localparam FbbOp_path_bypass = FBB_OP_PATH_BYPASS;
    localparam FbbOp_path_loopback = FBB_OP_PATH_LOOPBACK;
    localparam FbbOp_path_config = FBB_OP_PATH_CONFIG;
    // enum FbbPathState
    localparam FbbPathState_disabled = FBB_PATH_STATE_DISABLED;
    localparam FbbPathState_enabled = FBB_PATH_STATE_ENABLED;
    localparam FbbPathState_active = FBB_PATH_STATE_ACTIVE;
    localparam FbbPathState_error = FBB_PATH_STATE_ERROR;
    localparam FbbPathState_bypassed = FBB_PATH_STATE_BYPASSED;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct FbbPathConfig
    reg [7:0] fbbpathconfig_path_index; // FbbPathConfig.path_index
    reg fbbpathconfig_enabled; // FbbPathConfig.enabled
    reg [7:0] fbbpathconfig_latency_cycles; // FbbPathConfig.latency_cycles
    reg [31:0] fbbpathconfig_bandwidth_mbps; // FbbPathConfig.bandwidth_mbps
    reg [7:0] fbbpathconfig_priority; // FbbPathConfig.priority
    reg fbbpathconfig_auto_bypass; // FbbPathConfig.auto_bypass
    // struct FbbPathStatus
    reg [7:0] fbbpathstatus_path_index; // FbbPathStatus.path_index
    reg [31:0] fbbpathstatus_state; // FbbPathStatus.state
    reg fbbpathstatus_active; // FbbPathStatus.active
    reg [7:0] fbbpathstatus_error_code; // FbbPathStatus.error_code
    reg [31:0] fbbpathstatus_throughput_mbps; // FbbPathStatus.throughput_mbps
    reg [15:0] fbbpathstatus_latency_measured; // FbbPathStatus.latency_measured
    // struct FbbActivePath
    reg [7:0] fbbactivepath_active_path; // FbbActivePath.active_path
    reg [7:0] fbbactivepath_bypass_path; // FbbActivePath.bypass_path
    reg fbbactivepath_loopback_enabled; // FbbActivePath.loopback_enabled
    reg [31:0] fbbactivepath_paths; // FbbActivePath.paths
    // struct FbbCommand
    reg [31:0] fbbcommand_op; // FbbCommand.op
    reg [7:0] fbbcommand_path_index; // FbbCommand.path_index
    reg [15:0] fbbcommand_param1; // FbbCommand.param1
    reg [15:0] fbbcommand_param2; // FbbCommand.param2
    // struct 
    reg [7:0] _op; // .op
    reg [7:0] _path; // .path
    reg [7:0] _param1; // .param1
    reg [7:0] _param2; // .param2

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: fbb_path_config_init
    function [31:0] fbb_path_config_init; // -> FbbPathConfig
        input [7:0] index;
        begin
            fbb_path_config_init = 0 /* FbbPathConfig {...} */;
        end
    endfunction

    // function: fbb_path_config_low_latency
    function [31:0] fbb_path_config_low_latency; // -> FbbPathConfig
        input [7:0] index;
        begin
            fbb_path_config_low_latency = 0 /* FbbPathConfig {...} */;
        end
    endfunction

    // function: fbb_path_config_high_bandwidth
    function [31:0] fbb_path_config_high_bandwidth; // -> FbbPathConfig
        input [7:0] index;
        begin
            fbb_path_config_high_bandwidth = 0 /* FbbPathConfig {...} */;
        end
    endfunction

    // function: fbb_path_config_enable
    function [31:0] fbb_path_config_enable; // -> FbbPathConfig
        input [31:0] config;
        begin
            fbb_path_config_enable = 0 /* FbbPathConfig {...} */;
        end
    endfunction

    // function: fbb_path_status_init
    function [31:0] fbb_path_status_init; // -> FbbPathStatus
        input [7:0] index;
        begin
            fbb_path_status_init = 0 /* FbbPathStatus {...} */;
        end
    endfunction

    // function: fbb_path_status_enable
    function [31:0] fbb_path_status_enable; // -> FbbPathStatus
        input [31:0] status;
        begin
            fbb_path_status_enable = 0 /* FbbPathStatus {...} */;
        end
    endfunction

    // function: fbb_path_status_activate
    function [31:0] fbb_path_status_activate; // -> FbbPathStatus
        input [31:0] status;
        begin
            fbb_path_status_activate = 0 /* FbbPathStatus {...} */;
        end
    endfunction

    // function: fbb_path_status_bypass
    function [31:0] fbb_path_status_bypass; // -> FbbPathStatus
        input [31:0] status;
        begin
            fbb_path_status_bypass = 0 /* FbbPathStatus {...} */;
        end
    endfunction

    // function: fbb_path_status_error
    function [31:0] fbb_path_status_error; // -> FbbPathStatus
        input [31:0] status;
        input [7:0] error_code;
        begin
            fbb_path_status_error = 0 /* FbbPathStatus {...} */;
        end
    endfunction

    // function: fbb_path_status_update_metrics
    function [31:0] fbb_path_status_update_metrics; // -> FbbPathStatus
        input [31:0] status;
        input [31:0] throughput;
        input [15:0] latency;
        begin
            fbb_path_status_update_metrics = 0 /* FbbPathStatus {...} */;
        end
    endfunction

    // function: fbb_active_path_init
    function [31:0] fbb_active_path_init; // -> FbbActivePath
        begin
            // for-each over iterable
            for (__i = 0; __i < (0 .. FBB_MAX_PATHS); __i = __i + 1) begin
                paths[i] = fbb_path_status_init(@as(u8, @truncate(i)));
            end
            fbb_active_path_init = 0 /* FbbActivePath {...} */;
        end
    endfunction

    // function: fbb_active_path_select
    function [31:0] fbb_active_path_select; // -> FbbActivePath
        input [31:0] active;
        input [7:0] path_index;
        begin
            reg [31:0] idx = (path_index && 8'h07);
            reg [31:0] new_paths = active_paths;
            fbb_active_path_select = 0 /* FbbActivePath {...} */;
        end
    endfunction

    // function: fbb_active_path_enable_bypass
    function [31:0] fbb_active_path_enable_bypass; // -> FbbActivePath
        input [31:0] active;
        input [7:0] bypass_index;
        begin
            reg [31:0] idx = (bypass_index && 8'h07);
            reg [31:0] new_paths = active_paths;
            fbb_active_path_enable_bypass = 0 /* FbbActivePath {...} */;
        end
    endfunction

    // function: fbb_active_path_disable_bypass
    function [31:0] fbb_active_path_disable_bypass; // -> FbbActivePath
        input [31:0] active;
        begin
            reg [31:0] new_paths = active_paths;
            if ((active_bypass_path != 8'hFF)) begin
                new_paths[active_bypass_path] = fbb_path_status_enable(new_paths[active_bypass_path]);
            end
            fbb_active_path_disable_bypass = 0 /* FbbActivePath {...} */;
        end
    endfunction

    // function: fbb_active_path_enable_loopback
    function [31:0] fbb_active_path_enable_loopback; // -> FbbActivePath
        input [31:0] active;
        begin
            fbb_active_path_enable_loopback = 0 /* FbbActivePath {...} */;
        end
    endfunction

    // function: fbb_active_path_disable_loopback
    function [31:0] fbb_active_path_disable_loopback; // -> FbbActivePath
        input [31:0] active;
        begin
            fbb_active_path_disable_loopback = 0 /* FbbActivePath {...} */;
        end
    endfunction

    // function: fbb_active_path_get_path
    function [31:0] fbb_active_path_get_path; // -> FbbPathStatus
        input [31:0] active;
        input [7:0] path_index;
        begin
            reg [31:0] idx = (path_index && 8'h07);
            fbb_active_path_get_path = active_paths[idx];
        end
    endfunction

    // function: fbb_active_path_update_path_metrics
    function [31:0] fbb_active_path_update_path_metrics; // -> FbbActivePath
        input [31:0] active;
        input [7:0] path_index;
        input [31:0] throughput;
        input [15:0] latency;
        begin
            reg [31:0] idx = (path_index && 8'h07);
            reg [31:0] new_paths = active_paths;
            fbb_active_path_update_path_metrics = 0 /* FbbActivePath {...} */;
        end
    endfunction

    // function: fbb_path_index_valid
    function fbb_path_index_valid; // -> bool
        input [7:0] index;
        begin
            fbb_path_index_valid = (index < FBB_PATH_COUNT);
        end
    endfunction

    // function: fbb_latency_valid
    function fbb_latency_valid; // -> bool
        input [7:0] latency;
        begin
            fbb_latency_valid = ((latency >= FBB_LATENCY_MIN_CYCLES) && (latency <= FBB_LATENCY_MAX_CYCLES));
        end
    endfunction

    // function: fbb_bandwidth_valid
    function fbb_bandwidth_valid; // -> bool
        input [31:0] bandwidth;
        begin
            fbb_bandwidth_valid = ((bandwidth >= FBB_BANDWIDTH_MIN_MBPS) && (bandwidth <= FBB_BANDWIDTH_MAX_MBPS));
        end
    endfunction

    // function: fbb_path_config_valid
    function fbb_path_config_valid; // -> bool
        input [31:0] config;
        begin
            fbb_path_config_valid = ((fbb_path_index_valid(config_path_index) && fbb_latency_valid(config_latency_cycles)) && fbb_bandwidth_valid(config_bandwidth_mbps));
        end
    endfunction

    // function: encode_fbb_cmd
    function [31:0] encode_fbb_cmd; // -> u32
        input [7:0] op;
        input [7:0] path;
        input [7:0] param1;
        input [7:0] param2;
        begin
            reg [31:0] op_field = (@as(u32, op) << 24);
            reg [31:0] path_field = (@as(u32, (path && 8'h07)) << 21);
            reg [31:0] param1_field = (@as(u32, param1) << 13);
            reg [31:0] param2_field = (@as(u32, param2) << 5);
            encode_fbb_cmd = (((op_field || path_field) || param1_field) || param2_field);
        end
    endfunction
endmodule

`default_nettype wire
