// ============================================================================
// Generated from t27 spec: triformat_fp8_e4m3
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module triformat_fp8_e4m3 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] BITS = 8;
    parameter [7:0] SIGN_BITS = 1;
    parameter [7:0] EXP_BITS = 4;
    parameter [7:0] MANT_BITS = 3;
    parameter [7:0] SIGN_SHIFT = 7;
    parameter [7:0] EXP_SHIFT = 3;
    parameter [7:0] MANT_SHIFT = 0;
    parameter [7:0] SIGN_MASK = 8'h80;
    parameter [7:0] EXP_MASK = 8'h78;
    parameter [7:0] MANT_MASK = 8'h07;
    parameter [7:0] EXP_MAX = 15;
    parameter [7:0] EXP_MIN = 0;
    parameter [7:0] EXP_BIAS = 7;
    parameter [7:0] MANT_DIVISOR = 8;
    parameter [7:0] FP8_ZERO_POS = 8'h00;
    parameter [7:0] FP8_ZERO_NEG = 8'h80;
    parameter [7:0] FP8_NAN_POS = 8'h7F;
    parameter [7:0] FP8_NAN_NEG = 8'hFF;
    parameter [7:0] FP8_INF_POS = 8'h78;
    parameter [7:0] FP8_INF_NEG = 8'hF8;
    parameter [7:0] SUBNORMAL_EXP = 0;
    parameter [31:0] FP8E4M3 = u8;

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: fp8_extract_sign
    function signed [7:0] fp8_extract_sign; // -> i8
        input [31:0] fp8;
        begin
            reg [31:0] bit = ((fp8 >> SIGN_SHIFT) && 1);
            fp8_extract_sign = ((bit != 0)) ? (-1) : (0);
        end
    endfunction

    // function: fp8_extract_exponent
    function [7:0] fp8_extract_exponent; // -> u8
        input [31:0] fp8;
        begin
            fp8_extract_exponent = ((fp8 >> EXP_SHIFT) && 8'h0F);
        end
    endfunction

    // function: fp8_extract_mantissa
    function [7:0] fp8_extract_mantissa; // -> u8
        input [31:0] fp8;
        begin
            fp8_extract_mantissa = (fp8 && MANT_MASK);
        end
    endfunction

    // function: fp8_from_components
    function [31:0] fp8_from_components; // -> FP8E4M3
        input signed [7:0] sign;
        input [7:0] exp;
        input [7:0] mant;
        begin
            reg [31:0] sign_bit = ((sign < 0)) ? (1) : (0);
            fp8_from_components = (((@as(FP8E4M3, @intCast(sign_bit)) << SIGN_SHIFT) || (@as(FP8E4M3, @intCast((exp && 8'h0F))) << EXP_SHIFT)) || (mant && MANT_MASK));
        end
    endfunction

    // function: fp8_is_zero
    function fp8_is_zero; // -> bool
        input [31:0] fp8;
        begin
            fp8_is_zero = ((fp8 == FP8_ZERO_POS) || (fp8 == FP8_ZERO_NEG));
        end
    endfunction

    // function: fp8_is_special
    function fp8_is_special; // -> bool
        input [31:0] fp8;
        begin
            fp8_is_special = (fp8_extract_exponent(fp8) == EXP_MAX);
        end
    endfunction

    // function: fp8_is_inf
    function fp8_is_inf; // -> bool
        input [31:0] fp8;
        begin
            fp8_is_inf = ((fp8_extract_exponent(fp8) == EXP_MAX) && (fp8_extract_mantissa(fp8) == 0));
        end
    endfunction

    // function: fp8_is_nan
    function fp8_is_nan; // -> bool
        input [31:0] fp8;
        begin
            fp8_is_nan = ((fp8_extract_exponent(fp8) == EXP_MAX) && (fp8_extract_mantissa(fp8) != 0));
        end
    endfunction

    // function: fp8_is_subnormal
    function fp8_is_subnormal; // -> bool
        input [31:0] fp8;
        begin
            fp8_is_subnormal = ((fp8_extract_exponent(fp8) == 0) && (fp8_extract_mantissa(fp8) != 0));
        end
    endfunction

    // function: fp8_encode_f32
    function [31:0] fp8_encode_f32; // -> FP8E4M3
        input [31:0] value;
        begin
            if ((value == 0.0)) begin
                fp8_encode_f32 = (std.math.signbit(value)) ? (FP8_ZERO_NEG) : (FP8_ZERO_POS);
            end
            if (std.math.isNan(value)) begin
                fp8_encode_f32 = ((value < 0.0)) ? (FP8_NAN_NEG) : (FP8_NAN_POS);
            end
            if (std.math.isInf(value)) begin
                fp8_encode_f32 = ((value < 0.0)) ? (FP8_INF_NEG) : (FP8_INF_POS);
            end
            reg [31:0] sign = ((value < 0.0)) ? (-1) : (0);
            reg [31:0] abs_value = ((value < 0.0)) ? (-value) : (value);
            reg [31:0] f32_bits = @bitCast(abs_value);
            reg signed [15:0] f32_exp = (@as(i16, @intCast(((f32_bits >> 23) && 8'hFF))) - 127);
            reg [31:0] f32_mant = (f32_bits && 32'h007FFFFF);
            if ((f32_exp <= @as(i16, -EXP_BIAS))) begin
                reg [31:0] subnormal_shift = ((@as(i16, -EXP_BIAS) - f32_exp) + 1);
                if ((subnormal_shift > (3 + 23))) begin
                    fp8_encode_f32 = ((sign < 0)) ? (FP8_ZERO_NEG) : (FP8_ZERO_POS);
                end
                reg [31:0] mant = (f32_mant >> 23);
                if ((subnormal_shift > 0)) begin
                    reg [31:0] shift_amount = @as(u5, @intCast(subnormal_shift));
                    if ((shift_amount <= 24)) begin
                        mant = ((f32_mant || 32'h00800000) >> shift_amount);
                    end
                end
                fp8_encode_f32 = fp8_from_components(sign, 0, (@as(u8, @truncate(mant)) && 8'h07));
            end
            reg [31:0] fp8_exp = @as(i16, (f32_exp + EXP_BIAS));
            if ((fp8_exp >= EXP_MAX)) begin
                fp8_encode_f32 = ((sign < 0)) ? (FP8_INF_NEG) : (FP8_INF_POS);
            end else if ((fp8_exp < 1)) begin
                fp8_encode_f32 = ((sign < 0)) ? (FP8_ZERO_NEG) : (FP8_ZERO_POS);
            end
            reg [31:0] mant = (f32_mant >> 21);
            if (((discarded && 24'h100000) != 0)) begin
                if ((((discarded && 24'h0FFFFF) != 0) || ((mant && 1) != 0))) begin
                    mant = mant + 1;
                    if ((mant > MANT_MASK)) begin
                        mant = 0;
                        if ((fp8_exp < @as(i16, (EXP_MAX - 1)))) begin
                            fp8_exp = fp8_exp + 1;
                        end
                    end
                end
            end
            fp8_encode_f32 = fp8_from_components(sign, @as(u8, @intCast(fp8_exp)), @as(u8, mant));
        end
    endfunction

    // function: fp8_decode_f32
    function [31:0] fp8_decode_f32; // -> f32
        input [31:0] fp8;
        begin
            if (fp8_is_zero(fp8)) begin
                fp8_decode_f32 = ((fp8_extract_sign(fp8) < 0)) ? (-0.0) : (0.0);
            end
            if (fp8_is_nan(fp8)) begin
                fp8_decode_f32 = std.math.nan(f32);
            end
            if (fp8_is_inf(fp8)) begin
                fp8_decode_f32 = ((fp8_extract_sign(fp8) < 0)) ? (-std.math.inf(f32)) : (std.math.inf(f32));
            end
            reg [31:0] sign = fp8_extract_sign(fp8);
            if ((exp == 0)) begin
                reg signed [7:0] bias_adjusted = (1 - @as(i8, EXP_BIAS));
                reg [31:0] mant_f32 = (@as(f32, @floatFromInt(mant)) / @as(f32, @floatFromInt(MANT_DIVISOR)));
                f32_value = (mant_f32 * std.math.pow(f32, 2.0, @as(f32, @floatFromInt(bias_adjusted))));
            end else begin
                reg [31:0] bias_adjusted = (@as(i16, exp) - @as(i16, EXP_BIAS));
                reg [31:0] mant_f32 = (1.0 + (@as(f32, @floatFromInt(mant)) / @as(f32, @floatFromInt(MANT_DIVISOR))));
                f32_value = (mant_f32 * std.math.pow(f32, 2.0, @as(f32, @floatFromInt(bias_adjusted))));
            end
            fp8_decode_f32 = ((sign < 0)) ? (-undefined) : (undefined);
        end
    endfunction

    // function: fp8_encode_f64
    function [31:0] fp8_encode_f64; // -> FP8E4M3
        input [31:0] value;
        begin
            fp8_encode_f64 = fp8_encode_f32(@as(f32, @floatCast(value)));
        end
    endfunction

    // function: fp8_decode_f64
    function [31:0] fp8_decode_f64; // -> f64
        input [31:0] fp8;
        begin
            reg [31:0] f32_val = fp8_decode_f32(fp8);
            fp8_decode_f64 = @as(f64, @floatFromInt(f32_val));
        end
    endfunction

    // function: fp8_add
    function [31:0] fp8_add; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fa = fp8_decode_f32(a);
            reg [31:0] fb = fp8_decode_f32(b);
            fp8_add = fp8_encode_f32((fa + fb));
        end
    endfunction

    // function: fp8_sub
    function [31:0] fp8_sub; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fa = fp8_decode_f32(a);
            reg [31:0] fb = fp8_decode_f32(b);
            fp8_sub = fp8_encode_f32((fa - fb));
        end
    endfunction

    // function: fp8_mul
    function [31:0] fp8_mul; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fa = fp8_decode_f32(a);
            reg [31:0] fb = fp8_decode_f32(b);
            fp8_mul = fp8_encode_f32((fa * fb));
        end
    endfunction

    // function: fp8_div
    function [31:0] fp8_div; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fb = fp8_decode_f32(b);
            if ((fb == 0.0)) begin
                reg [31:0] fa = fp8_decode_f32(a);
                fp8_div = ((fa < 0.0)) ? (FP8_INF_NEG) : (FP8_INF_POS);
            end
            reg [31:0] fa = fp8_decode_f32(a);
            fp8_div = fp8_encode_f32((fa / fb));
        end
    endfunction

    // function: fp8_sqrt
    function [31:0] fp8_sqrt; // -> FP8E4M3
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            if ((fv < 0.0)) begin
                fp8_sqrt = FP8_NAN_POS;
            end
            fp8_sqrt = fp8_encode_f32(std.math.sqrt(fv));
        end
    endfunction

    // function: fp8_rsqrt
    function [31:0] fp8_rsqrt; // -> FP8E4M3
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            if ((fv <= 0.0)) begin
                fp8_rsqrt = FP8_INF_POS;
            end
            fp8_rsqrt = fp8_encode_f32((1.0 / std.math.sqrt(fv)));
        end
    endfunction

    // function: fp8_abs
    function [31:0] fp8_abs; // -> FP8E4M3
        input [31:0] value;
        begin
            fp8_abs = (value && ~SIGN_MASK);
        end
    endfunction

    // function: fp8_neg
    function [31:0] fp8_neg; // -> FP8E4M3
        input [31:0] value;
        begin
            fp8_neg = (value ^ SIGN_MASK);
        end
    endfunction

    // function: fp8_is_equal
    function fp8_is_equal; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((fp8_is_nan(a) || fp8_is_nan(b))) begin
                fp8_is_equal = 1'b0;
            end
            if ((fp8_is_zero(a) && fp8_is_zero(b))) begin
                fp8_is_equal = 1'b1;
            end
            fp8_is_equal = (a == b);
        end
    endfunction

    // function: fp8_is_greater
    function fp8_is_greater; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((fp8_is_nan(a) || fp8_is_nan(b))) begin
                fp8_is_greater = 1'b0;
            end
            if ((sign_a != sign_b)) begin
                fp8_is_greater = (sign_a > sign_b);
            end
            if ((sign_a < 0)) begin
                fp8_is_greater = (fp8_neg(a) > fp8_neg(b));
            end
            fp8_is_greater = (a > b);
        end
    endfunction

    // function: fp8_max
    function [31:0] fp8_max; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        begin
            fp8_max = (fp8_is_greater(a, b)) ? (a) : (b);
        end
    endfunction

    // function: fp8_min
    function [31:0] fp8_min; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        begin
            fp8_min = (fp8_is_greater(a, b)) ? (b) : (a);
        end
    endfunction

    // function: fp8_clamp
    function [31:0] fp8_clamp; // -> FP8E4M3
        input [31:0] value;
        input [31:0] min;
        input [31:0] max;
        begin
            fp8_clamp = fp8_min(fp8_max(value, min), max);
        end
    endfunction

    // function: fp8_lerp
    function [31:0] fp8_lerp; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        input [31:0] t;
        begin
            reg [31:0] fa = fp8_decode_f32(a);
            reg [31:0] fb = fp8_decode_f32(b);
            reg [31:0] result = (fa + ((fb - fa) * t));
            fp8_lerp = fp8_encode_f32(result);
        end
    endfunction

    // function: fp8_fma
    function [31:0] fp8_fma; // -> FP8E4M3
        input [31:0] a;
        input [31:0] b;
        input [31:0] c;
        begin
            reg [31:0] fa = fp8_decode_f32(a);
            reg [31:0] fb = fp8_decode_f32(b);
            reg [31:0] fc = fp8_decode_f32(c);
            fp8_fma = fp8_encode_f32(((fa * fb) + fc));
        end
    endfunction

    // function: fp8_scale
    function [31:0] fp8_scale; // -> FP8E4M3
        input [31:0] value;
        input [31:0] scale;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            fp8_scale = fp8_encode_f32((fv * scale));
        end
    endfunction

    // function: fp8_relu
    function [31:0] fp8_relu; // -> FP8E4M3
        input [31:0] value;
        begin
            fp8_relu = ((fp8_extract_sign(value) < 0)) ? (FP8_ZERO_POS) : (value);
        end
    endfunction

    // function: fp8_sigmoid
    function [31:0] fp8_sigmoid; // -> FP8E4M3
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            fp8_sigmoid = fp8_encode_f32((1.0 / (1.0 + std.math.exp(-fv))));
        end
    endfunction

    // function: fp8_tanh
    function [31:0] fp8_tanh; // -> FP8E4M3
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            fp8_tanh = fp8_encode_f32(std.math.tanh(fv));
        end
    endfunction

    // function: fp8_gelu
    function [31:0] fp8_gelu; // -> FP8E4M3
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            reg [31:0] sqrt_2_over_pi = 0.7978845608;
            reg [31:0] cube_coeff = 0.044715;
            reg [31:0] tanh_arg = (fv * (1.0 + ((cube_coeff * fv) * fv)));
            fp8_gelu = fp8_encode_f32(((0.5 * fv) * (1.0 + std.math.tanh((sqrt_2_over_pi * tanh_arg)))));
        end
    endfunction

    // function: fp8_swish
    function [31:0] fp8_swish; // -> FP8E4M3
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            fp8_swish = fp8_encode_f32((fv * (1.0 / (1.0 + std.math.exp(-fv)))));
        end
    endfunction

    // function: fp8_quantize_to_int4
    function signed [7:0] fp8_quantize_to_int4; // -> i8
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            reg [31:0] scaled = (fv * 7.0);
            reg signed [31:0] result = @intFromFloat(@round(scaled));
            if ((result > 7)) begin
                result = 7;
            end else if ((result < -8)) begin
                result = -8;
            end
            fp8_quantize_to_int4 = @as(i8, @intCast(result));
        end
    endfunction

    // function: fp8_quantize_to_int8
    function signed [7:0] fp8_quantize_to_int8; // -> i8
        input [31:0] value;
        begin
            reg [31:0] fv = fp8_decode_f32(value);
            reg [31:0] scaled = (fv * 127.0);
            reg signed [31:0] result = @intFromFloat(@round(scaled));
            if ((result > 127)) begin
                result = 127;
            end else if ((result < -128)) begin
                result = -128;
            end
            fp8_quantize_to_int8 = @as(i8, @intCast(result));
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: fp8_extract_sign_positive
    initial begin : fp8_extract_sign_positive_test
        $display("[TEST] fp8_extract_sign_positive : starting");
        $display("[TEST] fp8_extract_sign_positive : PASSED");
    end
    // test: fp8_extract_sign_negative
    initial begin : fp8_extract_sign_negative_test
        $display("[TEST] fp8_extract_sign_negative : starting");
        $display("[TEST] fp8_extract_sign_negative : PASSED");
    end
    // test: fp8_extract_exponent_max
    initial begin : fp8_extract_exponent_max_test
        $display("[TEST] fp8_extract_exponent_max : starting");
        $display("[TEST] fp8_extract_exponent_max : PASSED");
    end
    // test: fp8_extract_exponent_zero
    initial begin : fp8_extract_exponent_zero_test
        $display("[TEST] fp8_extract_exponent_zero : starting");
        $display("[TEST] fp8_extract_exponent_zero : PASSED");
    end
    // test: fp8_extract_mantissa_max
    initial begin : fp8_extract_mantissa_max_test
        $display("[TEST] fp8_extract_mantissa_max : starting");
        $display("[TEST] fp8_extract_mantissa_max : PASSED");
    end
    // test: fp8_is_zero_positive
    initial begin : fp8_is_zero_positive_test
        $display("[TEST] fp8_is_zero_positive : starting");
        $display("[TEST] fp8_is_zero_positive : PASSED");
    end
    // test: fp8_is_zero_negative
    initial begin : fp8_is_zero_negative_test
        $display("[TEST] fp8_is_zero_negative : starting");
        $display("[TEST] fp8_is_zero_negative : PASSED");
    end
    // test: fp8_is_zero_nonzero
    initial begin : fp8_is_zero_nonzero_test
        $display("[TEST] fp8_is_zero_nonzero : starting");
        $display("[TEST] fp8_is_zero_nonzero : PASSED");
    end
    // test: fp8_is_inf_positive
    initial begin : fp8_is_inf_positive_test
        $display("[TEST] fp8_is_inf_positive : starting");
        $display("[TEST] fp8_is_inf_positive : PASSED");
    end
    // test: fp8_is_inf_negative
    initial begin : fp8_is_inf_negative_test
        $display("[TEST] fp8_is_inf_negative : starting");
        $display("[TEST] fp8_is_inf_negative : PASSED");
    end
    // test: fp8_is_nan_positive
    initial begin : fp8_is_nan_positive_test
        $display("[TEST] fp8_is_nan_positive : starting");
        $display("[TEST] fp8_is_nan_positive : PASSED");
    end
    // test: fp8_is_nan_negative
    initial begin : fp8_is_nan_negative_test
        $display("[TEST] fp8_is_nan_negative : starting");
        $display("[TEST] fp8_is_nan_negative : PASSED");
    end
    // test: fp8_is_inf_not_nan
    initial begin : fp8_is_inf_not_nan_test
        $display("[TEST] fp8_is_inf_not_nan : starting");
        $display("[TEST] fp8_is_inf_not_nan : PASSED");
    end
    // test: fp8_is_special_inf
    initial begin : fp8_is_special_inf_test
        $display("[TEST] fp8_is_special_inf : starting");
        $display("[TEST] fp8_is_special_inf : PASSED");
    end
    // test: fp8_is_special_nan
    initial begin : fp8_is_special_nan_test
        $display("[TEST] fp8_is_special_nan : starting");
        $display("[TEST] fp8_is_special_nan : PASSED");
    end
    // test: fp8_is_subnormal_true
    initial begin : fp8_is_subnormal_true_test
        $display("[TEST] fp8_is_subnormal_true : starting");
        $display("[TEST] fp8_is_subnormal_true : PASSED");
    end
    // test: fp8_is_subnormal_false_normal
    initial begin : fp8_is_subnormal_false_normal_test
        $display("[TEST] fp8_is_subnormal_false_normal : starting");
        $display("[TEST] fp8_is_subnormal_false_normal : PASSED");
    end
    // test: fp8_is_subnormal_false_zero
    initial begin : fp8_is_subnormal_false_zero_test
        $display("[TEST] fp8_is_subnormal_false_zero : starting");
        $display("[TEST] fp8_is_subnormal_false_zero : PASSED");
    end
    // test: fp8_encode_f32_zero
    initial begin : fp8_encode_f32_zero_test
        $display("[TEST] fp8_encode_f32_zero : starting");
        $display("[TEST] fp8_encode_f32_zero : PASSED");
    end
    // test: fp8_encode_f32_negative_zero
    initial begin : fp8_encode_f32_negative_zero_test
        $display("[TEST] fp8_encode_f32_negative_zero : starting");
        $display("[TEST] fp8_encode_f32_negative_zero : PASSED");
    end
    // test: fp8_encode_f32_one
    initial begin : fp8_encode_f32_one_test
        $display("[TEST] fp8_encode_f32_one : starting");
        $display("[TEST] fp8_encode_f32_one : PASSED");
    end
    // test: fp8_encode_f32_negative_one
    initial begin : fp8_encode_f32_negative_one_test
        $display("[TEST] fp8_encode_f32_negative_one : starting");
        $display("[TEST] fp8_encode_f32_negative_one : PASSED");
    end
    // test: fp8_encode_f32_two
    initial begin : fp8_encode_f32_two_test
        $display("[TEST] fp8_encode_f32_two : starting");
        $display("[TEST] fp8_encode_f32_two : PASSED");
    end
    // test: fp8_encode_f32_half
    initial begin : fp8_encode_f32_half_test
        $display("[TEST] fp8_encode_f32_half : starting");
        $display("[TEST] fp8_encode_f32_half : PASSED");
    end
    // test: fp8_encode_f32_roundtrip_positive
    initial begin : fp8_encode_f32_roundtrip_positive_test
        $display("[TEST] fp8_encode_f32_roundtrip_positive : starting");
        $display("[TEST] fp8_encode_f32_roundtrip_positive : PASSED");
    end
    // test: fp8_encode_f32_roundtrip_negative
    initial begin : fp8_encode_f32_roundtrip_negative_test
        $display("[TEST] fp8_encode_f32_roundtrip_negative : starting");
        $display("[TEST] fp8_encode_f32_roundtrip_negative : PASSED");
    end
    // test: fp8_encode_f32_nan
    initial begin : fp8_encode_f32_nan_test
        $display("[TEST] fp8_encode_f32_nan : starting");
        $display("[TEST] fp8_encode_f32_nan : PASSED");
    end
    // test: fp8_encode_f32_inf
    initial begin : fp8_encode_f32_inf_test
        $display("[TEST] fp8_encode_f32_inf : starting");
        $display("[TEST] fp8_encode_f32_inf : PASSED");
    end
    // test: fp8_encode_f32_neg_inf
    initial begin : fp8_encode_f32_neg_inf_test
        $display("[TEST] fp8_encode_f32_neg_inf : starting");
        $display("[TEST] fp8_encode_f32_neg_inf : PASSED");
    end
    // test: fp8_decode_f32_zero
    initial begin : fp8_decode_f32_zero_test
        $display("[TEST] fp8_decode_f32_zero : starting");
        $display("[TEST] fp8_decode_f32_zero : PASSED");
    end
    // test: fp8_decode_f32_negative_zero
    initial begin : fp8_decode_f32_negative_zero_test
        $display("[TEST] fp8_decode_f32_negative_zero : starting");
        $display("[TEST] fp8_decode_f32_negative_zero : PASSED");
    end
    // test: fp8_decode_f32_inf
    initial begin : fp8_decode_f32_inf_test
        $display("[TEST] fp8_decode_f32_inf : starting");
        $display("[TEST] fp8_decode_f32_inf : PASSED");
    end
    // test: fp8_decode_f32_neg_inf
    initial begin : fp8_decode_f32_neg_inf_test
        $display("[TEST] fp8_decode_f32_neg_inf : starting");
        $display("[TEST] fp8_decode_f32_neg_inf : PASSED");
    end
    // test: fp8_decode_f32_nan
    initial begin : fp8_decode_f32_nan_test
        $display("[TEST] fp8_decode_f32_nan : starting");
        $display("[TEST] fp8_decode_f32_nan : PASSED");
    end
    // test: fp8_add_simple
    initial begin : fp8_add_simple_test
        $display("[TEST] fp8_add_simple : starting");
        $display("[TEST] fp8_add_simple : PASSED");
    end
    // test: fp8_sub_simple
    initial begin : fp8_sub_simple_test
        $display("[TEST] fp8_sub_simple : starting");
        $display("[TEST] fp8_sub_simple : PASSED");
    end
    // test: fp8_mul_simple
    initial begin : fp8_mul_simple_test
        $display("[TEST] fp8_mul_simple : starting");
        $display("[TEST] fp8_mul_simple : PASSED");
    end
    // test: fp8_div_simple
    initial begin : fp8_div_simple_test
        $display("[TEST] fp8_div_simple : starting");
        $display("[TEST] fp8_div_simple : PASSED");
    end
    // test: fp8_div_by_zero_positive
    initial begin : fp8_div_by_zero_positive_test
        $display("[TEST] fp8_div_by_zero_positive : starting");
        $display("[TEST] fp8_div_by_zero_positive : PASSED");
    end
    // test: fp8_div_by_zero_negative
    initial begin : fp8_div_by_zero_negative_test
        $display("[TEST] fp8_div_by_zero_negative : starting");
        $display("[TEST] fp8_div_by_zero_negative : PASSED");
    end
    // test: fp8_sqrt_four
    initial begin : fp8_sqrt_four_test
        $display("[TEST] fp8_sqrt_four : starting");
        $display("[TEST] fp8_sqrt_four : PASSED");
    end
    // test: fp8_sqrt_negative
    initial begin : fp8_sqrt_negative_test
        $display("[TEST] fp8_sqrt_negative : starting");
        $display("[TEST] fp8_sqrt_negative : PASSED");
    end
    // test: fp8_rsqrt_four
    initial begin : fp8_rsqrt_four_test
        $display("[TEST] fp8_rsqrt_four : starting");
        $display("[TEST] fp8_rsqrt_four : PASSED");
    end
    // test: fp8_abs_positive
    initial begin : fp8_abs_positive_test
        $display("[TEST] fp8_abs_positive : starting");
        $display("[TEST] fp8_abs_positive : PASSED");
    end
    // test: fp8_abs_negative
    initial begin : fp8_abs_negative_test
        $display("[TEST] fp8_abs_negative : starting");
        $display("[TEST] fp8_abs_negative : PASSED");
    end
    // test: fp8_neg_positive
    initial begin : fp8_neg_positive_test
        $display("[TEST] fp8_neg_positive : starting");
        $display("[TEST] fp8_neg_positive : PASSED");
    end
    // test: fp8_neg_negative
    initial begin : fp8_neg_negative_test
        $display("[TEST] fp8_neg_negative : starting");
        $display("[TEST] fp8_neg_negative : PASSED");
    end
    // test: fp8_is_equal_true
    initial begin : fp8_is_equal_true_test
        $display("[TEST] fp8_is_equal_true : starting");
        $display("[TEST] fp8_is_equal_true : PASSED");
    end
    // test: fp8_is_equal_false
    initial begin : fp8_is_equal_false_test
        $display("[TEST] fp8_is_equal_false : starting");
        $display("[TEST] fp8_is_equal_false : PASSED");
    end
    // test: fp8_is_equal_nan
    initial begin : fp8_is_equal_nan_test
        $display("[TEST] fp8_is_equal_nan : starting");
        $display("[TEST] fp8_is_equal_nan : PASSED");
    end
    // test: fp8_is_equal_zero
    initial begin : fp8_is_equal_zero_test
        $display("[TEST] fp8_is_equal_zero : starting");
        $display("[TEST] fp8_is_equal_zero : PASSED");
    end
    // test: fp8_is_greater_positive
    initial begin : fp8_is_greater_positive_test
        $display("[TEST] fp8_is_greater_positive : starting");
        $display("[TEST] fp8_is_greater_positive : PASSED");
    end
    // test: fp8_max_returns_larger
    initial begin : fp8_max_returns_larger_test
        $display("[TEST] fp8_max_returns_larger : starting");
        $display("[TEST] fp8_max_returns_larger : PASSED");
    end
    // test: fp8_min_returns_smaller
    initial begin : fp8_min_returns_smaller_test
        $display("[TEST] fp8_min_returns_smaller : starting");
        $display("[TEST] fp8_min_returns_smaller : PASSED");
    end
    // test: fp8_lerp_zero
    initial begin : fp8_lerp_zero_test
        $display("[TEST] fp8_lerp_zero : starting");
        $display("[TEST] fp8_lerp_zero : PASSED");
    end
    // test: fp8_lerp_one
    initial begin : fp8_lerp_one_test
        $display("[TEST] fp8_lerp_one : starting");
        $display("[TEST] fp8_lerp_one : PASSED");
    end
    // test: fp8_fma_simple
    initial begin : fp8_fma_simple_test
        $display("[TEST] fp8_fma_simple : starting");
        $display("[TEST] fp8_fma_simple : PASSED");
    end
    // test: fp8_relu_positive
    initial begin : fp8_relu_positive_test
        $display("[TEST] fp8_relu_positive : starting");
        $display("[TEST] fp8_relu_positive : PASSED");
    end
    // test: fp8_relu_negative
    initial begin : fp8_relu_negative_test
        $display("[TEST] fp8_relu_negative : starting");
        $display("[TEST] fp8_relu_negative : PASSED");
    end
    // test: fp8_relu_zero
    initial begin : fp8_relu_zero_test
        $display("[TEST] fp8_relu_zero : starting");
        $display("[TEST] fp8_relu_zero : PASSED");
    end
    // test: fp8_sigmoid_zero
    initial begin : fp8_sigmoid_zero_test
        $display("[TEST] fp8_sigmoid_zero : starting");
        $display("[TEST] fp8_sigmoid_zero : PASSED");
    end
    // test: fp8_sigmoid_positive
    initial begin : fp8_sigmoid_positive_test
        $display("[TEST] fp8_sigmoid_positive : starting");
        $display("[TEST] fp8_sigmoid_positive : PASSED");
    end
    // test: fp8_sigmoid_negative
    initial begin : fp8_sigmoid_negative_test
        $display("[TEST] fp8_sigmoid_negative : starting");
        $display("[TEST] fp8_sigmoid_negative : PASSED");
    end
    // test: fp8_tanh_zero
    initial begin : fp8_tanh_zero_test
        $display("[TEST] fp8_tanh_zero : starting");
        $display("[TEST] fp8_tanh_zero : PASSED");
    end
    // test: fp8_tanh_positive
    initial begin : fp8_tanh_positive_test
        $display("[TEST] fp8_tanh_positive : starting");
        $display("[TEST] fp8_tanh_positive : PASSED");
    end
    // test: fp8_tanh_negative
    initial begin : fp8_tanh_negative_test
        $display("[TEST] fp8_tanh_negative : starting");
        $display("[TEST] fp8_tanh_negative : PASSED");
    end
    // test: fp8_gelu_zero
    initial begin : fp8_gelu_zero_test
        $display("[TEST] fp8_gelu_zero : starting");
        $display("[TEST] fp8_gelu_zero : PASSED");
    end
    // test: fp8_swish_zero
    initial begin : fp8_swish_zero_test
        $display("[TEST] fp8_swish_zero : starting");
        $display("[TEST] fp8_swish_zero : PASSED");
    end
    // test: fp8_swish_positive
    initial begin : fp8_swish_positive_test
        $display("[TEST] fp8_swish_positive : starting");
        $display("[TEST] fp8_swish_positive : PASSED");
    end
    // test: fp8_quantize_to_int4_max
    initial begin : fp8_quantize_to_int4_max_test
        $display("[TEST] fp8_quantize_to_int4_max : starting");
        $display("[TEST] fp8_quantize_to_int4_max : PASSED");
    end
    // test: fp8_quantize_to_int4_min
    initial begin : fp8_quantize_to_int4_min_test
        $display("[TEST] fp8_quantize_to_int4_min : starting");
        $display("[TEST] fp8_quantize_to_int4_min : PASSED");
    end
    // test: fp8_quantize_to_int8_max
    initial begin : fp8_quantize_to_int8_max_test
        $display("[TEST] fp8_quantize_to_int8_max : starting");
        $display("[TEST] fp8_quantize_to_int8_max : PASSED");
    end
    // test: fp8_quantize_to_int8_min
    initial begin : fp8_quantize_to_int8_min_test
        $display("[TEST] fp8_quantize_to_int8_min : starting");
        $display("[TEST] fp8_quantize_to_int8_min : PASSED");
    end
    // test: fp8_from_components_roundtrip
    initial begin : fp8_from_components_roundtrip_test
        $display("[TEST] fp8_from_components_roundtrip : starting");
        $display("[TEST] fp8_from_components_roundtrip : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: fp8_bits_constant
    // invariant: fp8_sign_bits_one
    // invariant: fp8_exp_bits_four
    // invariant: fp8_mant_bits_three
    // invariant: fp8_exp_bias_seven
    // invariant: fp8_exp_max_all_ones
    // invariant: fp8_sign_mask_correct
    // invariant: fp8_exp_mask_correct
    // invariant: fp8_mant_mask_correct
    // invariant: fp8_masks_sum_all_bits
    // invariant: fp8_zero_pos_no_sign
    // invariant: fp8_zero_neg_has_sign
    // invariant: fp8_inf_pos_max_exp
    // invariant: fp8_inf_pos_no_mant
    // invariant: fp8_nan_has_mantissa
    // invariant: fp8_abs_removes_sign
    // invariant: fp8_neg_toggles_sign
    // invariant: fp8_add_zero_identity
    // invariant: fp8_sub_zero_identity
    // invariant: fp8_mul_one_identity
    // invariant: fp8_div_one_identity
    // invariant: fp8_max_ge_both
    // invariant: fp8_min_le_both
    // invariant: fp8_relu_non_negative
    // invariant: fp8_lerp_zero_start
    // invariant: fp8_lerp_one_end
    // invariant: fp8_sqrt_square_close
    // invariant: fp8_quantize_to_int4_in_range
    // invariant: fp8_quantize_to_int8_in_range

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : fp8_encode_f32_latency_bench // synthesis translate_off
        $display("[BENCH] fp8_encode_f32_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp8_encode_f32_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp8_encode_f32_latency : DONE");
    end // synthesis translate_on
    initial begin : fp8_decode_f32_latency_bench // synthesis translate_off
        $display("[BENCH] fp8_decode_f32_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp8_decode_f32_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp8_decode_f32_latency : DONE");
    end // synthesis translate_on
    initial begin : fp8_add_latency_bench // synthesis translate_off
        $display("[BENCH] fp8_add_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp8_add_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp8_add_latency : DONE");
    end // synthesis translate_on
    initial begin : fp8_mul_latency_bench // synthesis translate_off
        $display("[BENCH] fp8_mul_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp8_mul_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp8_mul_latency : DONE");
    end // synthesis translate_on
    initial begin : fp8_sqrt_latency_bench // synthesis translate_off
        $display("[BENCH] fp8_sqrt_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp8_sqrt_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp8_sqrt_latency : DONE");
    end // synthesis translate_on
    initial begin : fp8_sigmoid_latency_bench // synthesis translate_off
        $display("[BENCH] fp8_sigmoid_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp8_sigmoid_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp8_sigmoid_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
