// ============================================================================
// Generated from t27 spec: triformat_gf128
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module triformat_gf128 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] SIGN_SHIFT = 127;
    parameter [7:0] EXP_SHIFT = 99;
    parameter [7:0] MANT_SHIFT = 0;
    parameter [63:0] SIGN_MASK_HI = 64'h8000000000000000;
    parameter [63:0] SIGN_MASK_LO = 64'h0000000000000000;
    parameter [7:0] EXP_BITS = 28;
    parameter [7:0] MANT_BITS = 99;
    parameter [7:0] SIGN_BITS = 1;
    parameter [31:0] EXP_MAX = 32'h0FFFFFFF;
    parameter [31:0] EXP_MIN = 32'h00000000;
    parameter signed [31:0] BIAS = 134217727;
    parameter [31:0] SPECIAL_EXP = 32'h0FFFFFFF;
    parameter [31:0] PHI_BIAS = 3932160;
    parameter [31:0] GF128 = u128;
    localparam [31:0] GF128_ZERO_POS = 0;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct GF128Parts
    reg [63:0] gf128parts_hi; // GF128Parts.hi
    reg [63:0] gf128parts_lo; // GF128Parts.lo

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: gf128_to_parts
    function [31:0] gf128_to_parts; // -> GF128Parts
        input [31:0] gf128;
        begin
            gf128_to_parts = 0 /* GF128Parts {...} */;
        end
    endfunction

    // function: gf128_from_parts
    function [31:0] gf128_from_parts; // -> GF128
        input [31:0] parts;
        begin
            gf128_from_parts = ((@as(GF128, parts_hi) << 64) || @as(GF128, parts_lo));
        end
    endfunction

    // function: gf128_extract_sign
    function signed [7:0] gf128_extract_sign; // -> i8
        input [31:0] gf128;
        begin
            reg [31:0] parts = gf128_to_parts(gf128);
            reg [31:0] bit = ((parts_hi >> 63) && 1);
            gf128_extract_sign = ((bit != 0)) ? (-1) : (0);
        end
    endfunction

    // function: gf128_extract_exponent
    function [31:0] gf128_extract_exponent; // -> u32
        input [31:0] gf128;
        begin
            reg [31:0] parts = gf128_to_parts(gf128);
            gf128_extract_exponent = @as(u32, @truncate(((parts_hi >> 35) && 32'h0FFFFFFF)));
        end
    endfunction

    // function: gf128_extract_mantissa
    function [31:0] gf128_extract_mantissa; // -> u128
        input [31:0] gf128;
        begin
            reg [31:0] parts = gf128_to_parts(gf128);
            reg [31:0] hi_mant = (parts_hi && 64'h00000007FFFFFFFF);
            gf128_extract_mantissa = ((@as(u128, hi_mant) << 64) || @as(u128, parts_lo));
        end
    endfunction

    // function: gf128_from_components
    function [31:0] gf128_from_components; // -> GF128
        input signed [7:0] sign;
        input [31:0] exp;
        input [31:0] mant;
        begin
            reg [31:0] sign_bit = ((sign < 0)) ? (1) : (0);
            reg [31:0] clamped_exp = (exp && EXP_MAX);
            reg [31:0] clamped_mant = (mant && (@as(u128, EXP_MAX) >> 1));
            reg [31:0] hi_exp = (@as(u64, @truncate(clamped_exp)) << 35);
            reg [31:0] hi_mant = @as(u64, @truncate((clamped_mant >> 64)));
            reg [31:0] lo_mant = @as(u64, @truncate(clamped_mant));
            reg [31:0] hi = (((@as(u64, @intCast(sign_bit)) << 63) || hi_exp) || hi_mant);
            gf128_from_components = gf128_from_parts(0 /* GF128Parts {...} */);
        end
    endfunction

    // function: gf128_is_zero
    function gf128_is_zero; // -> bool
        input [31:0] gf128;
        begin
            gf128_is_zero = ((gf128 == GF128_ZERO_POS) || (gf128 == GF128_ZERO_NEG));
        end
    endfunction

    // function: gf128_is_special
    function gf128_is_special; // -> bool
        input [31:0] gf128;
        begin
            gf128_is_special = (gf128_extract_exponent(gf128) == EXP_MAX);
        end
    endfunction

    // function: gf128_is_inf
    function gf128_is_inf; // -> bool
        input [31:0] gf128;
        begin
            gf128_is_inf = (gf128_is_special(gf128) && (gf128_extract_mantissa(gf128) == 0));
        end
    endfunction

    // function: gf128_is_nan
    function gf128_is_nan; // -> bool
        input [31:0] gf128;
        begin
            gf128_is_nan = (gf128_is_special(gf128) && (gf128_extract_mantissa(gf128) != 0));
        end
    endfunction

    // function: gf128_encode_f64
    function [31:0] gf128_encode_f64; // -> GF128
        input [31:0] value;
        begin
            if ((value == 0.0)) begin
                gf128_encode_f64 = (std.math.signbit(value)) ? (GF128_ZERO_NEG) : (GF128_ZERO_POS);
            end
            if (std.math.isNan(value)) begin
                gf128_encode_f64 = GF128_NAN;
            end
            if (std.math.isInf(value)) begin
                gf128_encode_f64 = ((value < 0.0)) ? (GF128_INF_NEG) : (GF128_INF_POS);
            end
            reg [31:0] sign = ((value < 0.0)) ? (-1) : (0);
            reg [31:0] abs_value = ((value < 0.0)) ? (-value) : (value);
            reg [63:0] f64_bits = @bitCast(abs_value);
            reg signed [31:0] f64_exp = (@as(i32, @intCast(((f64_bits >> 52) && 12'h7FF))) - 1023);
            reg [63:0] f64_mant = (f64_bits && 64'h000FFFFFFFFFFFFF);
            reg [31:0] gf128_exp = @as(u32, @intCast((f64_exp + BIAS)));
            if ((gf128_exp >= EXP_MAX)) begin
                gf128_encode_f64 = ((sign < 0)) ? (GF128_INF_NEG) : (GF128_INF_POS);
            end
            reg [31:0] mant = (@as(u128, f64_mant) << 47);
            gf128_encode_f64 = gf128_from_components(sign, gf128_exp, mant);
        end
    endfunction

    // function: gf128_decode_f64
    function [31:0] gf128_decode_f64; // -> f64
        input [31:0] gf128;
        begin
            if (gf128_is_zero(gf128)) begin
                gf128_decode_f64 = ((gf128_extract_sign(gf128) < 0)) ? (-0.0) : (0.0);
            end
            if (gf128_is_nan(gf128)) begin
                gf128_decode_f64 = std.math.nan(f64);
            end
            if (gf128_is_inf(gf128)) begin
                gf128_decode_f64 = ((gf128_extract_sign(gf128) < 0)) ? (-std.math.inf(f64)) : (std.math.inf(f64));
            end
            reg [31:0] sign = gf128_extract_sign(gf128);
            reg [31:0] exp = gf128_extract_exponent(gf128);
            reg [31:0] mant = gf128_extract_mantissa(gf128);
            reg [31:0] mant_f64 = (@as(f64, @floatFromInt((mant >> 47))) / 4503599627370496.0);
            reg [31:0] bias_adjusted = (@as(i64, @intCast(exp)) - @as(i64, BIAS));
            if (((bias_adjusted < -1022) || (bias_adjusted > 1023))) begin
                gf128_decode_f64 = ((sign < 0)) ? (-std.math.inf(f64)) : (std.math.inf(f64));
            end
            reg [31:0] value = (mant_f64 * std.math.pow(f64, 2.0, @as(f64, @floatFromInt(bias_adjusted))));
            gf128_decode_f64 = ((sign < 0)) ? (-value) : (value);
        end
    endfunction

    // function: gf128_encode_f128
    function [31:0] gf128_encode_f128; // -> GF128
        input [31:0] value;
        begin
            reg [31:0] value_f64 = @as(f64, @floatCast(value));
            gf128_encode_f128 = gf128_encode_f64(value_f64);
        end
    endfunction

    // function: gf128_decode_f128
    function [31:0] gf128_decode_f128; // -> f128
        input [31:0] gf128;
        begin
            reg [31:0] value_f64 = gf128_decode_f64(gf128);
            gf128_decode_f128 = @as(f128, @floatCast(value_f64));
        end
    endfunction

    // function: gf128_add
    function [31:0] gf128_add; // -> GF128
        input [31:0] a;
        input [31:0] b;
        begin
            gf128_add = gf128_encode_f64((gf128_decode_f64(a) + gf128_decode_f64(b)));
        end
    endfunction

    // function: gf128_sub
    function [31:0] gf128_sub; // -> GF128
        input [31:0] a;
        input [31:0] b;
        begin
            gf128_sub = gf128_encode_f64((gf128_decode_f64(a) - gf128_decode_f64(b)));
        end
    endfunction

    // function: gf128_mul
    function [31:0] gf128_mul; // -> GF128
        input [31:0] a;
        input [31:0] b;
        begin
            gf128_mul = gf128_encode_f64((gf128_decode_f64(a) * gf128_decode_f64(b)));
        end
    endfunction

    // function: gf128_div
    function [31:0] gf128_div; // -> GF128
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fb = gf128_decode_f64(b);
            if ((fb == 0.0)) begin
                reg [31:0] fa = gf128_decode_f64(a);
                gf128_div = ((fa < 0.0)) ? (GF128_INF_NEG) : (GF128_INF_POS);
            end
            gf128_div = gf128_encode_f64((gf128_decode_f64(a) / fb));
        end
    endfunction

    // function: gf128_abs
    function [31:0] gf128_abs; // -> GF128
        input [31:0] gf128;
        begin
            gf128_abs = (gf128 && ~(@as(GF128, 1) << 127));
        end
    endfunction

    // function: gf128_neg
    function [31:0] gf128_neg; // -> GF128
        input [31:0] gf128;
        begin
            gf128_neg = (gf128 ^ (@as(GF128, 1) << 127));
        end
    endfunction

    // function: gf128_is_equal
    function gf128_is_equal; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((gf128_is_nan(a) || gf128_is_nan(b))) begin
                gf128_is_equal = 1'b0;
            end
            if ((gf128_is_zero(a) && gf128_is_zero(b))) begin
                gf128_is_equal = 1'b1;
            end
            gf128_is_equal = (a == b);
        end
    endfunction

    // function: gf128_is_greater
    function gf128_is_greater; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((gf128_is_nan(a) || gf128_is_nan(b))) begin
                gf128_is_greater = 1'b0;
            end
            if ((sign_a != sign_b)) begin
                gf128_is_greater = (sign_a > sign_b);
            end
            if ((sign_a < 0)) begin
                gf128_is_greater = (gf128_neg(a) > gf128_neg(b));
            end
            gf128_is_greater = (a > b);
        end
    endfunction

    // function: gf128_max
    function [31:0] gf128_max; // -> GF128
        input [31:0] a;
        input [31:0] b;
        begin
            gf128_max = (gf128_is_greater(a, b)) ? (a) : (b);
        end
    endfunction

    // function: gf128_min
    function [31:0] gf128_min; // -> GF128
        input [31:0] a;
        input [31:0] b;
        begin
            gf128_min = (gf128_is_greater(a, b)) ? (b) : (a);
        end
    endfunction

    // function: gf128_clamp
    function [31:0] gf128_clamp; // -> GF128
        input [31:0] value;
        input [31:0] min;
        input [31:0] max;
        begin
            gf128_clamp = gf128_min(gf128_max(value, min), max);
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: gf128_extract_sign_positive
    initial begin : gf128_extract_sign_positive_test
        $display("[TEST] gf128_extract_sign_positive : starting");
        $display("[TEST] gf128_extract_sign_positive : PASSED");
    end
    // test: gf128_extract_sign_negative
    initial begin : gf128_extract_sign_negative_test
        $display("[TEST] gf128_extract_sign_negative : starting");
        $display("[TEST] gf128_extract_sign_negative : PASSED");
    end
    // test: gf128_extract_exponent_middle
    initial begin : gf128_extract_exponent_middle_test
        $display("[TEST] gf128_extract_exponent_middle : starting");
        $display("[TEST] gf128_extract_exponent_middle : PASSED");
    end
    // test: gf128_is_zero_positive
    initial begin : gf128_is_zero_positive_test
        $display("[TEST] gf128_is_zero_positive : starting");
        $display("[TEST] gf128_is_zero_positive : PASSED");
    end
    // test: gf128_is_zero_negative
    initial begin : gf128_is_zero_negative_test
        $display("[TEST] gf128_is_zero_negative : starting");
        $display("[TEST] gf128_is_zero_negative : PASSED");
    end
    // test: gf128_is_inf_positive
    initial begin : gf128_is_inf_positive_test
        $display("[TEST] gf128_is_inf_positive : starting");
        $display("[TEST] gf128_is_inf_positive : PASSED");
    end
    // test: gf128_is_nan
    initial begin : gf128_is_nan_test
        $display("[TEST] gf128_is_nan : starting");
        $display("[TEST] gf128_is_nan : PASSED");
    end
    // test: gf128_encode_f64_zero
    initial begin : gf128_encode_f64_zero_test
        $display("[TEST] gf128_encode_f64_zero : starting");
        $display("[TEST] gf128_encode_f64_zero : PASSED");
    end
    // test: gf128_encode_f64_one
    initial begin : gf128_encode_f64_one_test
        $display("[TEST] gf128_encode_f64_one : starting");
        $display("[TEST] gf128_encode_f64_one : PASSED");
    end
    // test: gf128_encode_f64_negative_one
    initial begin : gf128_encode_f64_negative_one_test
        $display("[TEST] gf128_encode_f64_negative_one : starting");
        $display("[TEST] gf128_encode_f64_negative_one : PASSED");
    end
    // test: gf128_encode_f64_roundtrip
    initial begin : gf128_encode_f64_roundtrip_test
        $display("[TEST] gf128_encode_f64_roundtrip : starting");
        $display("[TEST] gf128_encode_f64_roundtrip : PASSED");
    end
    // test: gf128_add_simple
    initial begin : gf128_add_simple_test
        $display("[TEST] gf128_add_simple : starting");
        $display("[TEST] gf128_add_simple : PASSED");
    end
    // test: gf128_mul_simple
    initial begin : gf128_mul_simple_test
        $display("[TEST] gf128_mul_simple : starting");
        $display("[TEST] gf128_mul_simple : PASSED");
    end
    // test: gf128_abs_positive
    initial begin : gf128_abs_positive_test
        $display("[TEST] gf128_abs_positive : starting");
        $display("[TEST] gf128_abs_positive : PASSED");
    end
    // test: gf128_abs_negative
    initial begin : gf128_abs_negative_test
        $display("[TEST] gf128_abs_negative : starting");
        $display("[TEST] gf128_abs_negative : PASSED");
    end
    // test: gf128_neg
    initial begin : gf128_neg_test
        $display("[TEST] gf128_neg : starting");
        $display("[TEST] gf128_neg : PASSED");
    end
    // test: gf128_is_equal_nan
    initial begin : gf128_is_equal_nan_test
        $display("[TEST] gf128_is_equal_nan : starting");
        $display("[TEST] gf128_is_equal_nan : PASSED");
    end
    // test: gf128_is_greater_positive
    initial begin : gf128_is_greater_positive_test
        $display("[TEST] gf128_is_greater_positive : starting");
        $display("[TEST] gf128_is_greater_positive : PASSED");
    end
    // test: gf128_from_components_roundtrip
    initial begin : gf128_from_components_roundtrip_test
        $display("[TEST] gf128_from_components_roundtrip : starting");
        $display("[TEST] gf128_from_components_roundtrip : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: gf128_bits_total
    // invariant: gf128_bias_power_of_two_minus_one
    // invariant: gf128_special_exp_all_ones
    // invariant: gf128_zero_pos_no_sign
    // invariant: gf128_zero_neg_has_sign
    // invariant: gf128_abs_removes_sign
    // invariant: gf128_neg_toggles_sign

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : gf128_extract_sign_latency_bench // synthesis translate_off
        $display("[BENCH] gf128_extract_sign_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf128_extract_sign_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf128_extract_sign_latency : DONE");
    end // synthesis translate_on
    initial begin : gf128_encode_f64_latency_bench // synthesis translate_off
        $display("[BENCH] gf128_encode_f64_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf128_encode_f64_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf128_encode_f64_latency : DONE");
    end // synthesis translate_on
    initial begin : gf128_decode_f64_latency_bench // synthesis translate_off
        $display("[BENCH] gf128_decode_f64_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf128_decode_f64_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf128_decode_f64_latency : DONE");
    end // synthesis translate_on
    initial begin : gf128_add_latency_bench // synthesis translate_off
        $display("[BENCH] gf128_add_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf128_add_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf128_add_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
