// ============================================================================
// Generated from t27 spec: gf16_to_posit16
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module gf16_to_posit16 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] GF16_BITS = 16;
    parameter [7:0] GF16_SIGN_BIT = 15;
    parameter [7:0] GF16_EXP_BITS = 6;
    parameter [7:0] GF16_MANT_BITS = 9;
    parameter signed [7:0] GF16_BIAS = 31;
    parameter [7:0] POSIT16_BITS = 16;
    parameter [7:0] POSIT16_ES = 1;
    parameter signed [7:0] POSIT16_MAX_EXP = 7;
    parameter [7:0] POSIT16_REGIME_BITS = 2;
    parameter [7:0] POSIT16_MANT_BITS = 12;
    parameter signed [7:0] MAX_EXP_DIFF = 5;
    parameter [31:0] Gf16 = packed;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct 
    reg [31:0] _sign; // .sign
    reg [31:0] _exp; // .exp
    reg [31:0] _mant; // .mant
    // struct Posit16
    reg [15:0] posit16_bits; // Posit16.bits
    // struct PositComponents
    reg positcomponents_sign; // PositComponents.sign
    reg signed [7:0] positcomponents_regime; // PositComponents.regime
    reg [7:0] positcomponents_exponent; // PositComponents.exponent
    reg [15:0] positcomponents_mantissa; // PositComponents.mantissa
    // struct ConversionResult
    reg [15:0] conversionresult_bits; // ConversionResult.bits
    reg conversionresult_overflow; // ConversionResult.overflow
    reg conversionresult_underflow; // ConversionResult.underflow
    reg conversionresult_inexact; // ConversionResult.inexact
    // struct ConversionConfig
    reg [7:0] conversionconfig_round_mode; // ConversionConfig.round_mode
    reg conversionconfig_clamp_overflow; // ConversionConfig.clamp_overflow

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: gf16_from_bits
    function [31:0] gf16_from_bits; // -> Gf16
        input [15:0] bits;
        begin
            gf16_from_bits = 0 /* Gf16 {...} */;
        end
    endfunction

    // function: gf16_to_bits
    function [15:0] gf16_to_bits; // -> u16
        input [31:0] gf;
        begin
            reg [15:0] sign_field = (@as(u16, gf_sign) << 15);
            reg [15:0] exp_field = (@as(u16, gf_exp) << 9);
            reg [15:0] mant_field = @as(u16, gf_mant);
            gf16_to_bits = ((sign_field || exp_field) || mant_field);
        end
    endfunction

    // function: gf16_is_zero
    function gf16_is_zero; // -> bool
        input [31:0] gf;
        begin
            gf16_is_zero = ((gf_exp == 0) && (gf_mant == 0));
        end
    endfunction

    // function: gf16_is_subnormal
    function gf16_is_subnormal; // -> bool
        input [31:0] gf;
        begin
            gf16_is_subnormal = ((gf_exp == 0) && (gf_mant != 0));
        end
    endfunction

    // function: gf16_is_normal
    function gf16_is_normal; // -> bool
        input [31:0] gf;
        begin
            gf16_is_normal = ((gf_exp != 0) && (gf_exp != 8'h3F));
        end
    endfunction

    // function: gf16_is_infinity
    function gf16_is_infinity; // -> bool
        input [31:0] gf;
        begin
            gf16_is_infinity = ((gf_exp == 8'h3F) && (gf_mant == 0));
        end
    endfunction

    // function: gf16_is_nan
    function gf16_is_nan; // -> bool
        input [31:0] gf;
        begin
            gf16_is_nan = ((gf_exp == 8'h3F) && (gf_mant != 0));
        end
    endfunction

    // function: gf16_get_exp_biased
    function signed [7:0] gf16_get_exp_biased; // -> i8
        input [31:0] gf;
        begin
            gf16_get_exp_biased = (@as(i8, @bitCast(gf_exp)) - GF16_BIAS);
        end
    endfunction

    // function: posit16_from_bits
    function [31:0] posit16_from_bits; // -> Posit16
        input [15:0] bits;
        begin
            posit16_from_bits = 0 /* Posit16 {...} */;
        end
    endfunction

    // function: posit16_to_bits
    function [15:0] posit16_to_bits; // -> u16
        input [31:0] p;
        begin
            posit16_to_bits = p_bits;
        end
    endfunction

    // function: posit16_is_zero
    function posit16_is_zero; // -> bool
        input [31:0] p;
        begin
            posit16_is_zero = (p_bits == 16'h0000);
        end
    endfunction

    // function: posit16_is_one
    function posit16_is_one; // -> bool
        input [31:0] p;
        begin
            posit16_is_one = (p_bits == 16'h4000);
        end
    endfunction

    // function: posit16_is_neg_one
    function posit16_is_neg_one; // -> bool
        input [31:0] p;
        begin
            posit16_is_neg_one = (p_bits == 16'hC000);
        end
    endfunction

    // function: posit16_is_naR
    function posit16_is_naR; // -> bool
        input [31:0] p;
        begin
            posit16_is_naR = (p_bits == 16'h8000);
        end
    endfunction

    // function: posit16_get_sign
    function posit16_get_sign; // -> bool
        input [31:0] p;
        begin
            posit16_get_sign = ((p_bits >> 15) == 1);
        end
    endfunction

    // function: posit16_decode
    function [31:0] posit16_decode; // -> PositComponents
        input [31:0] p;
        begin
            reg [31:0] sign = 1'b0;
            if ((bits && (16'h8000 != 0))) begin
                sign = 1'b1;
                bits = (~bits + 1);
            end
            if ((bits == 0)) begin
                posit16_decode = 0 /* PositComponents {...} */;
            end
            reg [31:0] regime = 0;
            if ((bits && (16'h4000 != 0))) begin
                while ((bits && (16'h4000 != 0))) begin
                    regime = regime + 1;
                    if ((regime > 16)) begin
disable fork;
                    end
                    regime_bits = regime_bits + 1;
                end
            end else begin
                while ((bits && (16'h4000 == 0))) begin
                    if ((regime < -16)) begin
disable fork;
                    end
                    regime_bits = regime_bits + 1;
                end
            end
            reg [7:0] exponent = 0;
            while (((exp_bit < POSIT16_ES) && (bits != 0))) begin
                if ((bits && (16'h8000 != 0))) begin
                    (exponent || (@as(u8, 1) << ((POSIT16_ES - 1) - exp_bit)));
                end
                exp_bit = exp_bit + 1;
            end
            reg [15:0] mantissa = 0;
            while (((mant_bit < POSIT16_MANT_BITS) && (bits != 0))) begin
                if ((bits && (16'h8000 != 0))) begin
                    (mantissa || (@as(u16, 1) << ((POSIT16_MANT_BITS - 1) - mant_bit)));
                end
                mant_bit = mant_bit + 1;
            end
            posit16_decode = 0 /* PositComponents {...} */;
        end
    endfunction

    // function: conversion_config_init
    function [31:0] conversion_config_init; // -> ConversionConfig
        begin
            conversion_config_init = 0 /* ConversionConfig {...} */;
        end
    endfunction

    // function: gf16_to_posit16_raw
    function [31:0] gf16_to_posit16_raw; // -> Posit16
        input [31:0] gf;
        begin
            if (gf16_is_zero(gf)) begin
                gf16_to_posit16_raw = posit16_from_bits((@as(u16, @bitCast(gf_sign)) << 15));
            end else if (gf16_is_infinity(gf)) begin
                gf16_to_posit16_raw = posit16_from_bits((@as(u16, @bitCast(gf_sign)) << 15));
            end else if (gf16_is_nan(gf)) begin
                gf16_to_posit16_raw = posit16_from_bits(16'h8000);
            end
            reg signed [7:0] regime = 0;
            reg [7:0] exponent = 0;
            if ((exp_i8 > POSIT16_MAX_EXP)) begin
                regime = (exp_i8 - POSIT16_MAX_EXP);
                exponent = 0;
            end else if ((exp_i8 < -POSIT16_MAX_EXP)) begin
                regime = (exp_i8 + POSIT16_MAX_EXP);
                exponent = 0;
            end else begin
                regime = 0;
                exponent = @as(u8, @truncate(@as(u8, @bitCast((exp_i8 + POSIT16_MAX_EXP)))));
            end
            if ((regime > 14)) begin
                regime = 14;
            end
            if ((regime < -14)) begin
                regime = -14;
            end
            reg [15:0] result_bits = 0;
            if (sign) begin
                result_bits = 16'h8000;
            end
            // for-each over iterable
            for (__i = 0; __i < (0 .. @as(usize, @intCast(regime_count))); __i = __i + 1) begin
                if ((regime >= 0)) begin
                    (result_bits || temp_bits);
                end else begin
                    (result_bits || temp_bits);
                end
            end
            (result_bits || (@as(u16, exponent) << (14 - POSIT16_ES)));
            reg [15:0] mant = @as(u16, gf_mant);
            (result_bits || (mant && 16'h0FFF));
            gf16_to_posit16_raw = posit16_from_bits(result_bits);
        end
    endfunction

    // function: gf16_to_posit16_with_result
    function [31:0] gf16_to_posit16_with_result; // -> ConversionResult
        input [31:0] gf;
        input [31:0] config;
        begin
            if (gf16_is_zero(gf)) begin
                result_bits = (@as(u16, @bitCast(gf_sign)) << 15);
                result_overflow = 1'b0;
                result_underflow = 1'b0;
                result_inexact = 1'b0;
                gf16_to_posit16_with_result = undefined;
            end else if ((gf16_is_infinity(gf) || gf16_is_nan(gf))) begin
                result_bits = 16'h8000;
                result_overflow = 1'b0;
                result_underflow = 1'b0;
                result_inexact = 1'b1;
                gf16_to_posit16_with_result = undefined;
            end
            reg [31:0] posit = gf16_to_posit16_raw(gf);
            reg [31:0] exp_i8 = gf16_get_exp_biased(gf);
            if ((undefined_overflow && config_clamp_overflow)) begin
                result_bits = ((gf_sign == 1)) ? (16'hC000) : (16'h7FFF);
            end
            gf16_to_posit16_with_result = undefined;
        end
    endfunction

    // function: gf16_to_posit16
    function [31:0] gf16_to_posit16; // -> Posit16
        input [31:0] gf;
        begin
            gf16_to_posit16 = gf16_to_posit16_raw(gf);
        end
    endfunction

    // function: gf16_bits_to_posit16_bits
    function [15:0] gf16_bits_to_posit16_bits; // -> u16
        input [15:0] gf_bits;
        begin
            reg [31:0] gf = gf16_from_bits(gf_bits);
            reg [31:0] posit = gf16_to_posit16(gf);
            gf16_bits_to_posit16_bits = posit16_to_bits(posit);
        end
    endfunction

    // function: gf16_bits_to_posit16_bits_with_result
    function [31:0] gf16_bits_to_posit16_bits_with_result; // -> ConversionResult
        input [15:0] gf_bits;
        input [31:0] config;
        begin
            reg [31:0] gf = gf16_from_bits(gf_bits);
            gf16_bits_to_posit16_bits_with_result = gf16_to_posit16_with_result(gf, config);
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: gf16_bits_constants
    initial begin : gf16_bits_constants_test
        $display("[TEST] gf16_bits_constants : starting");
        $display("[TEST] gf16_bits_constants : PASSED");
    end
    // test: posit16_constants
    initial begin : posit16_constants_test
        $display("[TEST] posit16_constants : starting");
        $display("[TEST] posit16_constants : PASSED");
    end
    // test: posit16_regime_mant_bits
    initial begin : posit16_regime_mant_bits_test
        $display("[TEST] posit16_regime_mant_bits : starting");
        $display("[TEST] posit16_regime_mant_bits : PASSED");
    end
    // test: gf16_from_bits_roundtrip
    initial begin : gf16_from_bits_roundtrip_test
        $display("[TEST] gf16_from_bits_roundtrip : starting");
        $display("[TEST] gf16_from_bits_roundtrip : PASSED");
    end
    // test: gf16_is_zero_true
    initial begin : gf16_is_zero_true_test
        $display("[TEST] gf16_is_zero_true : starting");
        $display("[TEST] gf16_is_zero_true : PASSED");
    end
    // test: gf16_is_subnormal_true
    initial begin : gf16_is_subnormal_true_test
        $display("[TEST] gf16_is_subnormal_true : starting");
        $display("[TEST] gf16_is_subnormal_true : PASSED");
    end
    // test: gf16_is_normal_true
    initial begin : gf16_is_normal_true_test
        $display("[TEST] gf16_is_normal_true : starting");
        $display("[TEST] gf16_is_normal_true : PASSED");
    end
    // test: gf16_is_infinity_true
    initial begin : gf16_is_infinity_true_test
        $display("[TEST] gf16_is_infinity_true : starting");
        $display("[TEST] gf16_is_infinity_true : PASSED");
    end
    // test: gf16_is_nan_true
    initial begin : gf16_is_nan_true_test
        $display("[TEST] gf16_is_nan_true : starting");
        $display("[TEST] gf16_is_nan_true : PASSED");
    end
    // test: posit16_from_bits_roundtrip
    initial begin : posit16_from_bits_roundtrip_test
        $display("[TEST] posit16_from_bits_roundtrip : starting");
        $display("[TEST] posit16_from_bits_roundtrip : PASSED");
    end
    // test: posit16_is_zero_true
    initial begin : posit16_is_zero_true_test
        $display("[TEST] posit16_is_zero_true : starting");
        $display("[TEST] posit16_is_zero_true : PASSED");
    end
    // test: posit16_is_one_true
    initial begin : posit16_is_one_true_test
        $display("[TEST] posit16_is_one_true : starting");
        $display("[TEST] posit16_is_one_true : PASSED");
    end
    // test: posit16_is_neg_one_true
    initial begin : posit16_is_neg_one_true_test
        $display("[TEST] posit16_is_neg_one_true : starting");
        $display("[TEST] posit16_is_neg_one_true : PASSED");
    end
    // test: posit16_is_naR_true
    initial begin : posit16_is_naR_true_test
        $display("[TEST] posit16_is_naR_true : starting");
        $display("[TEST] posit16_is_naR_true : PASSED");
    end
    // test: posit16_get_sign_positive
    initial begin : posit16_get_sign_positive_test
        $display("[TEST] posit16_get_sign_positive : starting");
        $display("[TEST] posit16_get_sign_positive : PASSED");
    end
    // test: posit16_get_sign_negative
    initial begin : posit16_get_sign_negative_test
        $display("[TEST] posit16_get_sign_negative : starting");
        $display("[TEST] posit16_get_sign_negative : PASSED");
    end
    // test: posit16_decode_one
    initial begin : posit16_decode_one_test
        $display("[TEST] posit16_decode_one : starting");
        $display("[TEST] posit16_decode_one : PASSED");
    end
    // test: conversion_config_init_structure
    initial begin : conversion_config_init_structure_test
        $display("[TEST] conversion_config_init_structure : starting");
        $display("[TEST] conversion_config_init_structure : PASSED");
    end
    // test: gf16_to_posit16_zero
    initial begin : gf16_to_posit16_zero_test
        $display("[TEST] gf16_to_posit16_zero : starting");
        $display("[TEST] gf16_to_posit16_zero : PASSED");
    end
    // test: gf16_to_posit16_infinity
    initial begin : gf16_to_posit16_infinity_test
        $display("[TEST] gf16_to_posit16_infinity : starting");
        $display("[TEST] gf16_to_posit16_infinity : PASSED");
    end
    // test: gf16_to_posit16_nan
    initial begin : gf16_to_posit16_nan_test
        $display("[TEST] gf16_to_posit16_nan : starting");
        $display("[TEST] gf16_to_posit16_nan : PASSED");
    end
    // test: gf16_to_posit16_preserves_sign
    initial begin : gf16_to_posit16_preserves_sign_test
        $display("[TEST] gf16_to_posit16_preserves_sign : starting");
        $display("[TEST] gf16_to_posit16_preserves_sign : PASSED");
    end
    // test: gf16_bits_to_posit16_bits_zero
    initial begin : gf16_bits_to_posit16_bits_zero_test
        $display("[TEST] gf16_bits_to_posit16_bits_zero : starting");
        $display("[TEST] gf16_bits_to_posit16_bits_zero : PASSED");
    end
    // test: gf16_bits_to_posit16_bits_sign_preserved
    initial begin : gf16_bits_to_posit16_bits_sign_preserved_test
        $display("[TEST] gf16_bits_to_posit16_bits_sign_preserved : starting");
        $display("[TEST] gf16_bits_to_posit16_bits_sign_preserved : PASSED");
    end
    // test: gf16_to_posit16_with_result_zero
    initial begin : gf16_to_posit16_with_result_zero_test
        $display("[TEST] gf16_to_posit16_with_result_zero : starting");
        $display("[TEST] gf16_to_posit16_with_result_zero : PASSED");
    end
    // test: gf16_to_posit16_with_result_infinity
    initial begin : gf16_to_posit16_with_result_infinity_test
        $display("[TEST] gf16_to_posit16_with_result_infinity : starting");
        $display("[TEST] gf16_to_posit16_with_result_infinity : PASSED");
    end
    // test: gf16_to_posit16_with_result_overflow_clamped
    initial begin : gf16_to_posit16_with_result_overflow_clamped_test
        $display("[TEST] gf16_to_posit16_with_result_overflow_clamped : starting");
        $display("[TEST] gf16_to_posit16_with_result_overflow_clamped : PASSED");
    end
    // test: gf16_to_posit16_with_result_overflow_not_clamped
    initial begin : gf16_to_posit16_with_result_overflow_not_clamped_test
        $display("[TEST] gf16_to_posit16_with_result_overflow_not_clamped : starting");
        $display("[TEST] gf16_to_posit16_with_result_overflow_not_clamped : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: gf16_bits_total
    // invariant: gf16_exp_mant_sum
    // invariant: posit16_bits_total
    // invariant: posit16_es_value
    // invariant: posit16_regime_mant_sum
    // invariant: gf16_from_bits_roundtrip
    // invariant: posit16_from_bits_roundtrip
    // invariant: gf16_zero_exp_zero_mant_zero
    // invariant: gf16_subnormal_exp_zero_mant_nonzero
    // invariant: gf16_normal_exp_nonzero
    // invariant: posit16_zero_bits_zero
    // invariant: posit16_one_bits_one
    // invariant: posit16_naR_bits_naR
    // invariant: conversion_config_init_clamp_enabled
    // invariant: gf16_to_posit16_zero_preserves
    // invariant: gf16_to_posit16_infinity_to_naR
    // invariant: gf16_to_posit16_nan_to_naR

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : gf16_from_bits_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_from_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_from_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_from_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_to_bits_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_to_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_to_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_to_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : posit16_from_bits_latency_bench // synthesis translate_off
        $display("[BENCH] posit16_from_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] posit16_from_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] posit16_from_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : posit16_to_bits_latency_bench // synthesis translate_off
        $display("[BENCH] posit16_to_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] posit16_to_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] posit16_to_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : posit16_decode_latency_bench // synthesis translate_off
        $display("[BENCH] posit16_decode_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] posit16_decode_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] posit16_decode_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_to_posit16_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_to_posit16_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_to_posit16_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_to_posit16_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_to_posit16_with_result_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_to_posit16_with_result_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_to_posit16_with_result_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_to_posit16_with_result_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_bits_to_posit16_bits_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_bits_to_posit16_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_bits_to_posit16_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_bits_to_posit16_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : conversion_config_init_latency_bench // synthesis translate_off
        $display("[BENCH] conversion_config_init_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] conversion_config_init_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] conversion_config_init_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
