// ============================================================================
// Generated from t27 spec: gf16_to_fp16
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module gf16_to_fp16 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] GF16_SIGN_BITS = 1;
    parameter [7:0] GF16_EXP_BITS = 6;
    parameter [7:0] GF16_MANT_BITS = 9;
    parameter signed [7:0] GF16_BIAS = 31;
    parameter [7:0] FP16_SIGN_BITS = 1;
    parameter [7:0] FP16_EXP_BITS = 5;
    parameter [7:0] FP16_MANT_BITS = 10;
    parameter signed [7:0] FP16_BIAS = 15;
    parameter signed [7:0] MAX_EXP_DIFF = 6;
    parameter [15:0] MANTissa_MASK_GF16 = 16'h01FF;
    parameter [15:0] MANTissa_MASK_FP16 = 16'h03FF;
    parameter [31:0] Gf16 = packed;
    parameter [31:0] Fp16 = packed;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct 
    reg [31:0] _sign; // .sign
    reg [31:0] _exp; // .exp
    reg [31:0] _mant; // .mant
    // struct 
    reg [31:0] _sign; // .sign
    reg [31:0] _exp; // .exp
    reg [31:0] _mant; // .mant
    // struct ConversionResult
    reg [15:0] conversionresult_value; // ConversionResult.value
    reg conversionresult_overflow; // ConversionResult.overflow
    reg conversionresult_underflow; // ConversionResult.underflow
    reg conversionresult_lost_precision; // ConversionResult.lost_precision
    // struct ConversionConfig
    reg [7:0] conversionconfig_round_mode; // ConversionConfig.round_mode
    reg [7:0] conversionconfig_overflow_mode; // ConversionConfig.overflow_mode
    reg conversionconfig_enable_saturation; // ConversionConfig.enable_saturation

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: gf16_from_bits
    function [31:0] gf16_from_bits; // -> Gf16
        input [15:0] bits;
        begin
            gf16_from_bits = 0 /* Gf16 {...} */;
        end
    endfunction

    // function: gf16_to_bits
    function [15:0] gf16_to_bits; // -> u16
        input [31:0] gf;
        begin
            reg [15:0] sign_field = (@as(u16, gf_sign) << 15);
            reg [15:0] exp_field = (@as(u16, gf_exp) << 9);
            reg [15:0] mant_field = @as(u16, gf_mant);
            gf16_to_bits = ((sign_field || exp_field) || mant_field);
        end
    endfunction

    // function: gf16_get_exp_biased
    function signed [7:0] gf16_get_exp_biased; // -> i8
        input [31:0] gf;
        begin
            gf16_get_exp_biased = (@as(i8, @bitCast(gf_exp)) - GF16_BIAS);
        end
    endfunction

    // function: gf16_is_zero
    function gf16_is_zero; // -> bool
        input [31:0] gf;
        begin
            gf16_is_zero = ((gf_exp == 0) && (gf_mant == 0));
        end
    endfunction

    // function: gf16_is_infinity
    function gf16_is_infinity; // -> bool
        input [31:0] gf;
        begin
            gf16_is_infinity = ((gf_exp == 8'h3F) && (gf_mant == 0));
        end
    endfunction

    // function: gf16_is_nan
    function gf16_is_nan; // -> bool
        input [31:0] gf;
        begin
            gf16_is_nan = ((gf_exp == 8'h3F) && (gf_mant != 0));
        end
    endfunction

    // function: fp16_from_bits
    function [31:0] fp16_from_bits; // -> Fp16
        input [15:0] bits;
        begin
            fp16_from_bits = 0 /* Fp16 {...} */;
        end
    endfunction

    // function: fp16_to_bits
    function [15:0] fp16_to_bits; // -> u16
        input [31:0] fp;
        begin
            reg [15:0] sign_field = (@as(u16, fp_sign) << 15);
            reg [15:0] exp_field = (@as(u16, fp_exp) << 10);
            reg [15:0] mant_field = @as(u16, fp_mant);
            fp16_to_bits = ((sign_field || exp_field) || mant_field);
        end
    endfunction

    // function: fp16_get_exp_biased
    function signed [7:0] fp16_get_exp_biased; // -> i8
        input [31:0] fp;
        begin
            if ((fp_exp == 0)) begin
                fp16_get_exp_biased = -14;
            end else if ((fp_exp == 8'h1F)) begin
                fp16_get_exp_biased = 16;
            end
            fp16_get_exp_biased = (@as(i8, @bitCast(fp_exp)) - FP16_BIAS);
        end
    endfunction

    // function: fp16_is_zero
    function fp16_is_zero; // -> bool
        input [31:0] fp;
        begin
            fp16_is_zero = ((fp_exp == 0) && (fp_mant == 0));
        end
    endfunction

    // function: fp16_is_infinity
    function fp16_is_infinity; // -> bool
        input [31:0] fp;
        begin
            fp16_is_infinity = ((fp_exp == 8'h1F) && (fp_mant == 0));
        end
    endfunction

    // function: fp16_is_nan
    function fp16_is_nan; // -> bool
        input [31:0] fp;
        begin
            fp16_is_nan = ((fp_exp == 8'h1F) && (fp_mant != 0));
        end
    endfunction

    // function: conversion_config_init
    function [31:0] conversion_config_init; // -> ConversionConfig
        begin
            conversion_config_init = 0 /* ConversionConfig {...} */;
        end
    endfunction

    // function: conversion_config_no_saturation
    function [31:0] conversion_config_no_saturation; // -> ConversionConfig
        begin
            conversion_config_no_saturation = 0 /* ConversionConfig {...} */;
        end
    endfunction

    // function: gf16_to_fp16_raw
    function [31:0] gf16_to_fp16_raw; // -> Fp16
        input [31:0] gf;
        begin
            reg [31:0] exp_i8 = gf16_get_exp_biased(gf);
            if (gf16_is_zero(gf)) begin
                gf16_to_fp16_raw = 0 /* Fp16 {...} */;
            end else if (gf16_is_infinity(gf)) begin
                gf16_to_fp16_raw = 0 /* Fp16 {...} */;
            end else if (gf16_is_nan(gf)) begin
                gf16_to_fp16_raw = 0 /* Fp16 {...} */;
            end
            reg [31:0] exp = 0;
            reg [31:0] mant = 0;
            if ((exp_i8 <= -15)) begin
                exp = 0;
                mant = 0;
                lost_precision = 1'b1;
            end else if ((exp_i8 >= 16)) begin
                exp = 8'h1F;
                mant = 0;
            end else begin
                exp = @as(u5, @truncate((@as(u8, @bitCast(exp_i8)) && 8'h1F)));
                mant = (@as(u10, gf_mant) << 1);
            end
            gf16_to_fp16_raw = 0 /* Fp16 {...} */;
        end
    endfunction

    // function: gf16_to_fp16_with_result
    function [31:0] gf16_to_fp16_with_result; // -> ConversionResult
        input [31:0] gf;
        input [31:0] config;
        begin
            if (gf16_is_zero(gf)) begin
                result_value = fp16_to_bits(0 /* Fp16 {...} */);
                result_overflow = 1'b0;
                result_underflow = 1'b0;
                result_lost_precision = 1'b0;
                gf16_to_fp16_with_result = undefined;
            end else if (gf16_is_infinity(gf)) begin
                result_value = fp16_to_bits(0 /* Fp16 {...} */);
                result_overflow = 1'b0;
                result_underflow = 1'b0;
                result_lost_precision = 1'b0;
                gf16_to_fp16_with_result = undefined;
            end else if (gf16_is_nan(gf)) begin
                result_value = fp16_to_bits(0 /* Fp16 {...} */);
                result_overflow = 1'b0;
                result_underflow = 1'b0;
                result_lost_precision = 1'b0;
                gf16_to_fp16_with_result = undefined;
            end
            reg [31:0] exp_i8 = gf16_get_exp_biased(gf);
            if ((exp_i8 <= -15)) begin
                if (config_enable_saturation) begin
                    result_value = fp16_to_bits(0 /* Fp16 {...} */);
                end else begin
                    result_value = fp16_to_bits(0 /* Fp16 {...} */);
                end
                result_underflow = 1'b1;
                result_lost_precision = 1'b1;
                gf16_to_fp16_with_result = undefined;
            end else if ((exp_i8 >= 16)) begin
                if (((config_overflow_mode == 0) || config_enable_saturation)) begin
                    result_value = fp16_to_bits(0 /* Fp16 {...} */);
                end else begin
                    result_value = fp16_to_bits(0 /* Fp16 {...} */);
                end
                result_overflow = 1'b1;
                gf16_to_fp16_with_result = undefined;
            end else begin
                exp = @as(u5, @truncate((@as(u8, @bitCast(exp_i8)) && 8'h1F)));
                mant = (@as(u10, gf_mant) << 1);
                result_value = fp16_to_bits(0 /* Fp16 {...} */);
                gf16_to_fp16_with_result = undefined;
            end
        end
    endfunction

    // function: gf16_to_fp16
    function [31:0] gf16_to_fp16; // -> Fp16
        input [31:0] gf;
        begin
            reg [31:0] result = gf16_to_fp16_with_result(gf, conversion_config_init());
            gf16_to_fp16 = fp16_from_bits(result_value);
        end
    endfunction

    // function: gf16_bits_to_fp16_bits
    function [15:0] gf16_bits_to_fp16_bits; // -> u16
        input [15:0] gf_bits;
        begin
            reg [31:0] gf = gf16_from_bits(gf_bits);
            reg [31:0] fp = gf16_to_fp16(gf);
            gf16_bits_to_fp16_bits = fp16_to_bits(fp);
        end
    endfunction

    // function: gf16_bits_to_fp16_bits_with_result
    function [31:0] gf16_bits_to_fp16_bits_with_result; // -> ConversionResult
        input [15:0] gf_bits;
        input [31:0] config;
        begin
            reg [31:0] gf = gf16_from_bits(gf_bits);
            gf16_bits_to_fp16_bits_with_result = gf16_to_fp16_with_result(gf, config);
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: gf16_bits_constants
    initial begin : gf16_bits_constants_test
        $display("[TEST] gf16_bits_constants : starting");
        $display("[TEST] gf16_bits_constants : PASSED");
    end
    // test: fp16_bits_constants
    initial begin : fp16_bits_constants_test
        $display("[TEST] fp16_bits_constants : starting");
        $display("[TEST] fp16_bits_constants : PASSED");
    end
    // test: mantissa_masks
    initial begin : mantissa_masks_test
        $display("[TEST] mantissa_masks : starting");
        $display("[TEST] mantissa_masks : PASSED");
    end
    // test: gf16_from_bits_to_bits_roundtrip
    initial begin : gf16_from_bits_to_bits_roundtrip_test
        $display("[TEST] gf16_from_bits_to_bits_roundtrip : starting");
        $display("[TEST] gf16_from_bits_to_bits_roundtrip : PASSED");
    end
    // test: gf16_from_bits_structure
    initial begin : gf16_from_bits_structure_test
        $display("[TEST] gf16_from_bits_structure : starting");
        $display("[TEST] gf16_from_bits_structure : PASSED");
    end
    // test: fp16_from_bits_to_bits_roundtrip
    initial begin : fp16_from_bits_to_bits_roundtrip_test
        $display("[TEST] fp16_from_bits_to_bits_roundtrip : starting");
        $display("[TEST] fp16_from_bits_to_bits_roundtrip : PASSED");
    end
    // test: gf16_is_zero_true
    initial begin : gf16_is_zero_true_test
        $display("[TEST] gf16_is_zero_true : starting");
        $display("[TEST] gf16_is_zero_true : PASSED");
    end
    // test: gf16_is_zero_false
    initial begin : gf16_is_zero_false_test
        $display("[TEST] gf16_is_zero_false : starting");
        $display("[TEST] gf16_is_zero_false : PASSED");
    end
    // test: gf16_is_infinity_true
    initial begin : gf16_is_infinity_true_test
        $display("[TEST] gf16_is_infinity_true : starting");
        $display("[TEST] gf16_is_infinity_true : PASSED");
    end
    // test: gf16_is_infinity_false
    initial begin : gf16_is_infinity_false_test
        $display("[TEST] gf16_is_infinity_false : starting");
        $display("[TEST] gf16_is_infinity_false : PASSED");
    end
    // test: gf16_is_nan_true
    initial begin : gf16_is_nan_true_test
        $display("[TEST] gf16_is_nan_true : starting");
        $display("[TEST] gf16_is_nan_true : PASSED");
    end
    // test: fp16_is_zero_true
    initial begin : fp16_is_zero_true_test
        $display("[TEST] fp16_is_zero_true : starting");
        $display("[TEST] fp16_is_zero_true : PASSED");
    end
    // test: fp16_is_infinity_true
    initial begin : fp16_is_infinity_true_test
        $display("[TEST] fp16_is_infinity_true : starting");
        $display("[TEST] fp16_is_infinity_true : PASSED");
    end
    // test: conversion_config_init_structure
    initial begin : conversion_config_init_structure_test
        $display("[TEST] conversion_config_init_structure : starting");
        $display("[TEST] conversion_config_init_structure : PASSED");
    end
    // test: conversion_config_no_saturation_structure
    initial begin : conversion_config_no_saturation_structure_test
        $display("[TEST] conversion_config_no_saturation_structure : starting");
        $display("[TEST] conversion_config_no_saturation_structure : PASSED");
    end
    // test: gf16_to_fp16_zero
    initial begin : gf16_to_fp16_zero_test
        $display("[TEST] gf16_to_fp16_zero : starting");
        $display("[TEST] gf16_to_fp16_zero : PASSED");
    end
    // test: gf16_to_fp16_infinity
    initial begin : gf16_to_fp16_infinity_test
        $display("[TEST] gf16_to_fp16_infinity : starting");
        $display("[TEST] gf16_to_fp16_infinity : PASSED");
    end
    // test: gf16_to_fp16_nan
    initial begin : gf16_to_fp16_nan_test
        $display("[TEST] gf16_to_fp16_nan : starting");
        $display("[TEST] gf16_to_fp16_nan : PASSED");
    end
    // test: gf16_to_fp16_preserves_sign
    initial begin : gf16_to_fp16_preserves_sign_test
        $display("[TEST] gf16_to_fp16_preserves_sign : starting");
        $display("[TEST] gf16_to_fp16_preserves_sign : PASSED");
    end
    // test: gf16_to_fp16_with_result_zero
    initial begin : gf16_to_fp16_with_result_zero_test
        $display("[TEST] gf16_to_fp16_with_result_zero : starting");
        $display("[TEST] gf16_to_fp16_with_result_zero : PASSED");
    end
    // test: gf16_bits_to_fp16_bits_zero
    initial begin : gf16_bits_to_fp16_bits_zero_test
        $display("[TEST] gf16_bits_to_fp16_bits_zero : starting");
        $display("[TEST] gf16_bits_to_fp16_bits_zero : PASSED");
    end
    // test: gf16_bits_to_fp16_bits_roundtrip
    initial begin : gf16_bits_to_fp16_bits_roundtrip_test
        $display("[TEST] gf16_bits_to_fp16_bits_roundtrip : starting");
        $display("[TEST] gf16_bits_to_fp16_bits_roundtrip : PASSED");
    end
    // test: gf16_to_fp16_with_result_underflow
    initial begin : gf16_to_fp16_with_result_underflow_test
        $display("[TEST] gf16_to_fp16_with_result_underflow : starting");
        $display("[TEST] gf16_to_fp16_with_result_underflow : PASSED");
    end
    // test: gf16_to_fp16_with_result_overflow
    initial begin : gf16_to_fp16_with_result_overflow_test
        $display("[TEST] gf16_to_fp16_with_result_overflow : starting");
        $display("[TEST] gf16_to_fp16_with_result_overflow : PASSED");
    end
    // test: gf16_to_fp16_with_result_saturation
    initial begin : gf16_to_fp16_with_result_saturation_test
        $display("[TEST] gf16_to_fp16_with_result_saturation : starting");
        $display("[TEST] gf16_to_fp16_with_result_saturation : PASSED");
    end
    // test: gf16_to_fp16_with_result_no_saturation_overflow
    initial begin : gf16_to_fp16_with_result_no_saturation_overflow_test
        $display("[TEST] gf16_to_fp16_with_result_no_saturation_overflow : starting");
        $display("[TEST] gf16_to_fp16_with_result_no_saturation_overflow : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: gf16_bit_count
    // invariant: fp16_bit_count
    // invariant: gf16_exp_width
    // invariant: fp16_exp_width
    // invariant: gf16_mant_width
    // invariant: fp16_mant_width
    // invariant: mantissa_masks_correct
    // invariant: gf16_from_bits_roundtrip
    // invariant: fp16_from_bits_roundtrip
    // invariant: gf16_zero_exp_zero_mant_zero
    // invariant: gf16_infinity_exp_max_mant_zero
    // invariant: fp16_infinity_exp_max_mant_zero
    // invariant: conversion_config_init_saturation_enabled
    // invariant: conversion_config_no_saturation_disabled
    // invariant: gf16_to_fp16_zero_preserves
    // invariant: gf16_to_fp16_infinity_preserves_sign
    // invariant: gf16_to_fp16_nan_preserves_sign

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : gf16_from_bits_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_from_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_from_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_from_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_to_bits_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_to_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_to_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_to_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : fp16_from_bits_latency_bench // synthesis translate_off
        $display("[BENCH] fp16_from_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp16_from_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp16_from_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : fp16_to_bits_latency_bench // synthesis translate_off
        $display("[BENCH] fp16_to_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] fp16_to_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] fp16_to_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_to_fp16_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_to_fp16_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_to_fp16_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_to_fp16_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_to_fp16_with_result_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_to_fp16_with_result_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_to_fp16_with_result_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_to_fp16_with_result_latency : DONE");
    end // synthesis translate_on
    initial begin : gf16_bits_to_fp16_bits_latency_bench // synthesis translate_off
        $display("[BENCH] gf16_bits_to_fp16_bits_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf16_bits_to_fp16_bits_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf16_bits_to_fp16_bits_latency : DONE");
    end // synthesis translate_on
    initial begin : conversion_config_init_latency_bench // synthesis translate_off
        $display("[BENCH] conversion_config_init_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] conversion_config_init_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] conversion_config_init_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
