// ============================================================================
// Generated from t27 spec: triformat_gf256
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module triformat_gf256 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [15:0] SIGN_SHIFT = 255;
    parameter [15:0] EXP_SHIFT = 223;
    parameter [15:0] MANT_SHIFT = 0;
    parameter [7:0] SIGN_BITS = 1;
    parameter [7:0] EXP_BITS = 32;
    parameter [7:0] MANT_BITS = 223;
    parameter [31:0] EXP_MAX = 32'hFFFFFFFF;
    parameter [31:0] EXP_MIN = 32'h00000000;
    parameter signed [63:0] BIAS = 2147483647;
    parameter [31:0] SPECIAL_EXP = 32'hFFFFFFFF;
    parameter [63:0] PHI_BIAS = 67108864;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct GF256
    reg [31:0] gf256_parts; // GF256.parts

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: gf256_zero
    function [31:0] gf256_zero; // -> GF256
        begin
            gf256_zero = 0 /* GF256 {...} */;
        end
    endfunction

    // function: gf256_negative_zero
    function [31:0] gf256_negative_zero; // -> GF256
        begin
            reg [31:0] result = gf256_zero();
            (result_parts[3] || 64'h8000000000000000);
            gf256_negative_zero = result;
        end
    endfunction

    // function: gf256_inf_positive
    function [31:0] gf256_inf_positive; // -> GF256
        begin
            gf256_inf_positive = 0 /* GF256 {...} */;
        end
    endfunction

    // function: gf256_inf_negative
    function [31:0] gf256_inf_negative; // -> GF256
        begin
            reg [31:0] result = gf256_inf_positive();
            (result_parts[3] || 64'h8000000000000000);
            gf256_inf_negative = result;
        end
    endfunction

    // function: gf256_nan
    function [31:0] gf256_nan; // -> GF256
        begin
            reg [31:0] result = gf256_inf_positive();
            gf256_nan = result;
        end
    endfunction

    // function: gf256_extract_sign
    function signed [7:0] gf256_extract_sign; // -> i8
        input [31:0] gf256;
        begin
            reg [31:0] bit = ((gf256_parts[3] >> 63) && 1);
            gf256_extract_sign = ((bit != 0)) ? (-1) : (0);
        end
    endfunction

    // function: gf256_extract_exponent
    function [31:0] gf256_extract_exponent; // -> u32
        input [31:0] gf256;
        begin
            gf256_extract_exponent = @as(u32, @truncate((gf256_parts[3] >> 31)));
        end
    endfunction

    // function: gf256_extract_mantissa
    function [31:0] gf256_extract_mantissa; // -> GF256
        input [31:0] gf256;
        begin
            (gf256_parts[3] && 32'h7FFFFFFF);
            (gf256_parts[3] && 32'h00000000);
            gf256_extract_mantissa = gf256;
        end
    endfunction

    // function: gf256_from_components
    function [31:0] gf256_from_components; // -> GF256
        input signed [7:0] sign;
        input [31:0] exp;
        input [31:0] mant;
        begin
            if ((sign_bit != 0)) begin
                (mant_parts[3] || 64'h8000000000000000);
            end else begin
                (mant_parts[3] && 64'h7FFFFFFFFFFFFFFF);
            end
            gf256_from_components = mant;
        end
    endfunction

    // function: gf256_is_zero
    function gf256_is_zero; // -> bool
        input [31:0] gf256;
        begin
            gf256_is_zero = ((((gf256_parts[0] == 0) && (gf256_parts[1] == 0)) && (gf256_parts[2] == 0)) && ((gf256_parts[3] && 64'h7FFFFFFFFFFFFFFF) == 0));
        end
    endfunction

    // function: gf256_is_special
    function gf256_is_special; // -> bool
        input [31:0] gf256;
        begin
            gf256_is_special = (gf256_extract_exponent(gf256) == EXP_MAX);
        end
    endfunction

    // function: gf256_is_inf
    function gf256_is_inf; // -> bool
        input [31:0] gf256;
        begin
            if (!gf256_is_special(gf256)) begin
                gf256_is_inf = 1'b0;
            end
            reg [31:0] mant = gf256_extract_mantissa(gf256);
            gf256_is_inf = ((((mant_parts[0] == 0) && (mant_parts[1] == 0)) && (mant_parts[2] == 0)) && (mant_parts[3] == 0));
        end
    endfunction

    // function: gf256_is_nan
    function gf256_is_nan; // -> bool
        input [31:0] gf256;
        begin
            if (!gf256_is_special(gf256)) begin
                gf256_is_nan = 1'b0;
            end
            reg [31:0] mant = gf256_extract_mantissa(gf256);
            gf256_is_nan = ((((mant_parts[0] != 0) || (mant_parts[1] != 0)) || (mant_parts[2] != 0)) || (mant_parts[3] != 0));
        end
    endfunction

    // function: gf256_encode_f64
    function [31:0] gf256_encode_f64; // -> GF256
        input [31:0] value;
        begin
            if ((value == 0.0)) begin
                gf256_encode_f64 = (std.math.signbit(value)) ? (gf256_negative_zero()) : (gf256_zero());
            end
            if (std.math.isNan(value)) begin
                gf256_encode_f64 = gf256_nan();
            end
            if (std.math.isInf(value)) begin
                gf256_encode_f64 = ((value < 0.0)) ? (gf256_inf_negative()) : (gf256_inf_positive());
            end
            reg [31:0] sign = ((value < 0.0)) ? (-1) : (0);
            reg [31:0] abs_value = ((value < 0.0)) ? (-value) : (value);
            reg [63:0] f64_bits = @bitCast(abs_value);
            reg signed [63:0] f64_exp = (@as(i64, @intCast(((f64_bits >> 52) && 12'h7FF))) - 1023);
            reg [63:0] f64_mant = (f64_bits && 64'h000FFFFFFFFFFFFF);
            reg [31:0] gf256_exp = @as(u32, @intCast((f64_exp + BIAS)));
            if ((gf256_exp >= EXP_MAX)) begin
                gf256_encode_f64 = ((sign < 0)) ? (gf256_inf_negative()) : (gf256_inf_positive());
            end
            gf256_encode_f64 = gf256_from_components(sign, gf256_exp, undefined);
        end
    endfunction

    // function: gf256_decode_f64
    function [31:0] gf256_decode_f64; // -> f64
        input [31:0] gf256;
        begin
            if (gf256_is_zero(gf256)) begin
                gf256_decode_f64 = ((gf256_extract_sign(gf256) < 0)) ? (-0.0) : (0.0);
            end
            if (gf256_is_nan(gf256)) begin
                gf256_decode_f64 = std.math.nan(f64);
            end
            if (gf256_is_inf(gf256)) begin
                gf256_decode_f64 = ((gf256_extract_sign(gf256) < 0)) ? (-std.math.inf(f64)) : (std.math.inf(f64));
            end
            reg [31:0] sign = gf256_extract_sign(gf256);
            reg [31:0] exp = gf256_extract_exponent(gf256);
            reg [31:0] mant = gf256_extract_mantissa(gf256);
            reg [31:0] mant_f64 = (@as(f64, @floatFromInt(mant_parts[0])) / 4503599627370496.0);
            reg [31:0] bias_adjusted = (@as(i64, @intCast(exp)) - BIAS);
            if (((bias_adjusted < -1022) || (bias_adjusted > 1023))) begin
                gf256_decode_f64 = ((sign < 0)) ? (-std.math.inf(f64)) : (std.math.inf(f64));
            end
            reg [31:0] value = (mant_f64 * std.math.pow(f64, 2.0, @as(f64, @floatFromInt(bias_adjusted))));
            gf256_decode_f64 = ((sign < 0)) ? (-value) : (value);
        end
    endfunction

    // function: gf256_add
    function [31:0] gf256_add; // -> GF256
        input [31:0] a;
        input [31:0] b;
        begin
            gf256_add = gf256_encode_f64((gf256_decode_f64(a) + gf256_decode_f64(b)));
        end
    endfunction

    // function: gf256_sub
    function [31:0] gf256_sub; // -> GF256
        input [31:0] a;
        input [31:0] b;
        begin
            gf256_sub = gf256_encode_f64((gf256_decode_f64(a) - gf256_decode_f64(b)));
        end
    endfunction

    // function: gf256_mul
    function [31:0] gf256_mul; // -> GF256
        input [31:0] a;
        input [31:0] b;
        begin
            gf256_mul = gf256_encode_f64((gf256_decode_f64(a) * gf256_decode_f64(b)));
        end
    endfunction

    // function: gf256_div
    function [31:0] gf256_div; // -> GF256
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fb = gf256_decode_f64(b);
            if ((fb == 0.0)) begin
                reg [31:0] fa = gf256_decode_f64(a);
                gf256_div = ((fa < 0.0)) ? (gf256_inf_negative()) : (gf256_inf_positive());
            end
            gf256_div = gf256_encode_f64((gf256_decode_f64(a) / fb));
        end
    endfunction

    // function: gf256_abs
    function [31:0] gf256_abs; // -> GF256
        input [31:0] gf256;
        begin
            (gf256_parts[3] && 64'h7FFFFFFFFFFFFFFF);
            gf256_abs = gf256;
        end
    endfunction

    // function: gf256_neg
    function [31:0] gf256_neg; // -> GF256
        input [31:0] gf256;
        begin
            gf256_neg = gf256;
        end
    endfunction

    // function: gf256_is_equal
    function gf256_is_equal; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((gf256_is_nan(a) || gf256_is_nan(b))) begin
                gf256_is_equal = 1'b0;
            end
            if ((gf256_is_zero(a) && gf256_is_zero(b))) begin
                gf256_is_equal = 1'b1;
            end
            gf256_is_equal = ((((a_parts[0] == b_parts[0]) && (a_parts[1] == b_parts[1])) && (a_parts[2] == b_parts[2])) && (a_parts[3] == b_parts[3]));
        end
    endfunction

    // function: gf256_is_greater
    function gf256_is_greater; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((gf256_is_nan(a) || gf256_is_nan(b))) begin
                gf256_is_greater = 1'b0;
            end
            if ((sign_a != sign_b)) begin
                gf256_is_greater = (sign_a > sign_b);
            end
            if ((sign_a < 0)) begin
                reg [31:0] neg_a = gf256_neg(a);
                reg [31:0] neg_b = gf256_neg(b);
                gf256_is_greater = ((((neg_a_parts[3] > neg_b_parts[3]) || ((neg_a_parts[3] == neg_b_parts[3]) && (neg_a_parts[2] > neg_b_parts[2]))) || ((neg_a_parts[2] == neg_b_parts[2]) && (neg_a_parts[1] > neg_b_parts[1]))) || ((neg_a_parts[1] == neg_b_parts[1]) && (neg_a_parts[0] > neg_b_parts[0])));
            end
            gf256_is_greater = ((((a_parts[3] > b_parts[3]) || ((a_parts[3] == b_parts[3]) && (a_parts[2] > b_parts[2]))) || ((a_parts[2] == b_parts[2]) && (a_parts[1] > b_parts[1]))) || ((a_parts[1] == b_parts[1]) && (a_parts[0] > b_parts[0])));
        end
    endfunction

    // function: gf256_max
    function [31:0] gf256_max; // -> GF256
        input [31:0] a;
        input [31:0] b;
        begin
            gf256_max = (gf256_is_greater(a, b)) ? (a) : (b);
        end
    endfunction

    // function: gf256_min
    function [31:0] gf256_min; // -> GF256
        input [31:0] a;
        input [31:0] b;
        begin
            gf256_min = (gf256_is_greater(a, b)) ? (b) : (a);
        end
    endfunction

    // function: gf256_clamp
    function [31:0] gf256_clamp; // -> GF256
        input [31:0] value;
        input [31:0] min;
        input [31:0] max;
        begin
            gf256_clamp = gf256_min(gf256_max(value, min), max);
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: gf256_zero_is_zero
    initial begin : gf256_zero_is_zero_test
        $display("[TEST] gf256_zero_is_zero : starting");
        $display("[TEST] gf256_zero_is_zero : PASSED");
    end
    // test: gf256_negative_zero_is_zero
    initial begin : gf256_negative_zero_is_zero_test
        $display("[TEST] gf256_negative_zero_is_zero : starting");
        $display("[TEST] gf256_negative_zero_is_zero : PASSED");
    end
    // test: gf256_nonzero_is_not_zero
    initial begin : gf256_nonzero_is_not_zero_test
        $display("[TEST] gf256_nonzero_is_not_zero : starting");
        $display("[TEST] gf256_nonzero_is_not_zero : PASSED");
    end
    // test: gf256_inf_is_special
    initial begin : gf256_inf_is_special_test
        $display("[TEST] gf256_inf_is_special : starting");
        $display("[TEST] gf256_inf_is_special : PASSED");
    end
    // test: gf256_nan_is_special
    initial begin : gf256_nan_is_special_test
        $display("[TEST] gf256_nan_is_special : starting");
        $display("[TEST] gf256_nan_is_special : PASSED");
    end
    // test: gf256_inf_positive
    initial begin : gf256_inf_positive_test
        $display("[TEST] gf256_inf_positive : starting");
        $display("[TEST] gf256_inf_positive : PASSED");
    end
    // test: gf256_inf_negative
    initial begin : gf256_inf_negative_test
        $display("[TEST] gf256_inf_negative : starting");
        $display("[TEST] gf256_inf_negative : PASSED");
    end
    // test: gf256_nan
    initial begin : gf256_nan_test
        $display("[TEST] gf256_nan : starting");
        $display("[TEST] gf256_nan : PASSED");
    end
    // test: gf256_inf_not_nan
    initial begin : gf256_inf_not_nan_test
        $display("[TEST] gf256_inf_not_nan : starting");
        $display("[TEST] gf256_inf_not_nan : PASSED");
    end
    // test: gf256_extract_sign_positive
    initial begin : gf256_extract_sign_positive_test
        $display("[TEST] gf256_extract_sign_positive : starting");
        $display("[TEST] gf256_extract_sign_positive : PASSED");
    end
    // test: gf256_extract_sign_negative
    initial begin : gf256_extract_sign_negative_test
        $display("[TEST] gf256_extract_sign_negative : starting");
        $display("[TEST] gf256_extract_sign_negative : PASSED");
    end
    // test: gf256_encode_f64_zero
    initial begin : gf256_encode_f64_zero_test
        $display("[TEST] gf256_encode_f64_zero : starting");
        $display("[TEST] gf256_encode_f64_zero : PASSED");
    end
    // test: gf256_encode_f64_one
    initial begin : gf256_encode_f64_one_test
        $display("[TEST] gf256_encode_f64_one : starting");
        $display("[TEST] gf256_encode_f64_one : PASSED");
    end
    // test: gf256_encode_f64_negative_one
    initial begin : gf256_encode_f64_negative_one_test
        $display("[TEST] gf256_encode_f64_negative_one : starting");
        $display("[TEST] gf256_encode_f64_negative_one : PASSED");
    end
    // test: gf256_encode_f64_roundtrip
    initial begin : gf256_encode_f64_roundtrip_test
        $display("[TEST] gf256_encode_f64_roundtrip : starting");
        $display("[TEST] gf256_encode_f64_roundtrip : PASSED");
    end
    // test: gf256_add_simple
    initial begin : gf256_add_simple_test
        $display("[TEST] gf256_add_simple : starting");
        $display("[TEST] gf256_add_simple : PASSED");
    end
    // test: gf256_mul_simple
    initial begin : gf256_mul_simple_test
        $display("[TEST] gf256_mul_simple : starting");
        $display("[TEST] gf256_mul_simple : PASSED");
    end
    // test: gf256_abs_positive
    initial begin : gf256_abs_positive_test
        $display("[TEST] gf256_abs_positive : starting");
        $display("[TEST] gf256_abs_positive : PASSED");
    end
    // test: gf256_abs_negative
    initial begin : gf256_abs_negative_test
        $display("[TEST] gf256_abs_negative : starting");
        $display("[TEST] gf256_abs_negative : PASSED");
    end
    // test: gf256_neg_positive
    initial begin : gf256_neg_positive_test
        $display("[TEST] gf256_neg_positive : starting");
        $display("[TEST] gf256_neg_positive : PASSED");
    end
    // test: gf256_neg_negative
    initial begin : gf256_neg_negative_test
        $display("[TEST] gf256_neg_negative : starting");
        $display("[TEST] gf256_neg_negative : PASSED");
    end
    // test: gf256_is_equal_same
    initial begin : gf256_is_equal_same_test
        $display("[TEST] gf256_is_equal_same : starting");
        $display("[TEST] gf256_is_equal_same : PASSED");
    end
    // test: gf256_is_equal_nan
    initial begin : gf256_is_equal_nan_test
        $display("[TEST] gf256_is_equal_nan : starting");
        $display("[TEST] gf256_is_equal_nan : PASSED");
    end
    // test: gf256_is_equal_zero
    initial begin : gf256_is_equal_zero_test
        $display("[TEST] gf256_is_equal_zero : starting");
        $display("[TEST] gf256_is_equal_zero : PASSED");
    end
    // test: gf256_is_greater_positive
    initial begin : gf256_is_greater_positive_test
        $display("[TEST] gf256_is_greater_positive : starting");
        $display("[TEST] gf256_is_greater_positive : PASSED");
    end
    // test: gf256_is_greater_negative
    initial begin : gf256_is_greater_negative_test
        $display("[TEST] gf256_is_greater_negative : starting");
        $display("[TEST] gf256_is_greater_negative : PASSED");
    end
    // test: gf256_max_returns_larger
    initial begin : gf256_max_returns_larger_test
        $display("[TEST] gf256_max_returns_larger : starting");
        $display("[TEST] gf256_max_returns_larger : PASSED");
    end
    // test: gf256_min_returns_smaller
    initial begin : gf256_min_returns_smaller_test
        $display("[TEST] gf256_min_returns_smaller : starting");
        $display("[TEST] gf256_min_returns_smaller : PASSED");
    end
    // test: gf256_from_components_roundtrip
    initial begin : gf256_from_components_roundtrip_test
        $display("[TEST] gf256_from_components_roundtrip : starting");
        $display("[TEST] gf256_from_components_roundtrip : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: gf256_bits_total
    // invariant: gf256_bias_power_of_two_minus_one
    // invariant: gf256_special_exp_all_ones
    // invariant: gf256_zero_no_sign_mant
    // invariant: gf256_neg_zero_has_sign
    // invariant: gf256_abs_removes_sign
    // invariant: gf256_neg_toggles_sign

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : gf256_extract_sign_latency_bench // synthesis translate_off
        $display("[BENCH] gf256_extract_sign_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf256_extract_sign_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf256_extract_sign_latency : DONE");
    end // synthesis translate_on
    initial begin : gf256_encode_f64_latency_bench // synthesis translate_off
        $display("[BENCH] gf256_encode_f64_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf256_encode_f64_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf256_encode_f64_latency : DONE");
    end // synthesis translate_on
    initial begin : gf256_decode_f64_latency_bench // synthesis translate_off
        $display("[BENCH] gf256_decode_f64_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf256_decode_f64_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf256_decode_f64_latency : DONE");
    end // synthesis translate_on
    initial begin : gf256_add_latency_bench // synthesis translate_off
        $display("[BENCH] gf256_add_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf256_add_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf256_add_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
