// ============================================================================
// Generated from t27 spec: triformat_gf64
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module triformat_gf64 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] SIGN_SHIFT = 63;
    parameter [7:0] EXP_SHIFT = 45;
    parameter [7:0] MANT_SHIFT = 0;
    parameter [63:0] SIGN_MASK = 64'h8000000000000000;
    parameter [63:0] EXP_MASK = 64'h7FFF800000000000;
    parameter [63:0] MANT_MASK = 64'h00007FFFFFFFFFFF;
    parameter [15:0] EXP_MAX = 20'h3FFFF;
    parameter [15:0] EXP_MIN = 16'h0000;
    parameter signed [15:0] BIAS = 131071;
    parameter [15:0] SPECIAL_EXP = 20'h3FFFF;
    parameter [63:0] MANT_DIVISOR = 35184372088832;
    parameter [7:0] MANT_DIVISOR_SHIFT = 45;
    parameter [31:0] PHI_BIAS = 245760;
    parameter [63:0] GF64_ZERO_POS = 64'h0000000000000000;
    parameter [63:0] GF64_ZERO_NEG = 64'h8000000000000000;
    parameter [63:0] GF64_INF_POS = 64'h7FFF800000000000;
    parameter [63:0] GF64_INF_NEG = 64'hFFFF800000000000;
    parameter [63:0] GF64_NAN = 64'hFFFF800000000001;
    parameter [31:0] GF64 = u64;

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: gf64_extract_sign
    function signed [7:0] gf64_extract_sign; // -> i8
        input [31:0] gf64;
        begin
            reg [31:0] bit = ((gf64 >> SIGN_SHIFT) && 1);
            gf64_extract_sign = ((bit != 0)) ? (-1) : (0);
        end
    endfunction

    // function: gf64_extract_exponent
    function signed [15:0] gf64_extract_exponent; // -> i16
        input [31:0] gf64;
        begin
            gf64_extract_exponent = @as(i16, @intCast(((gf64 >> EXP_SHIFT) && EXP_MAX)));
        end
    endfunction

    // function: gf64_extract_mantissa
    function [63:0] gf64_extract_mantissa; // -> u64
        input [31:0] gf64;
        begin
            gf64_extract_mantissa = (gf64 && MANT_MASK);
        end
    endfunction

    // function: gf64_from_components
    function [31:0] gf64_from_components; // -> GF64
        input signed [7:0] sign;
        input signed [15:0] exp;
        input [63:0] mant;
        begin
            reg [31:0] sign_bit = ((sign < 0)) ? (1) : (0);
            gf64_from_components = (((@as(GF64, @intCast(sign_bit)) << SIGN_SHIFT) || (@as(GF64, @intCast((exp && EXP_MAX))) << EXP_SHIFT)) || (mant && MANT_MASK));
        end
    endfunction

    // function: gf64_is_zero
    function gf64_is_zero; // -> bool
        input [31:0] gf64;
        begin
            gf64_is_zero = ((gf64 == GF64_ZERO_POS) || (gf64 == GF64_ZERO_NEG));
        end
    endfunction

    // function: gf64_is_special
    function gf64_is_special; // -> bool
        input [31:0] gf64;
        begin
            gf64_is_special = (gf64_extract_exponent(gf64) == @as(i16, @intCast(EXP_MAX)));
        end
    endfunction

    // function: gf64_is_inf
    function gf64_is_inf; // -> bool
        input [31:0] gf64;
        begin
            reg [31:0] exp = gf64_extract_exponent(gf64);
            reg [31:0] mant = gf64_extract_mantissa(gf64);
            gf64_is_inf = ((exp == @as(i16, @intCast(EXP_MAX))) && (mant == 0));
        end
    endfunction

    // function: gf64_is_nan
    function gf64_is_nan; // -> bool
        input [31:0] gf64;
        begin
            reg [31:0] exp = gf64_extract_exponent(gf64);
            reg [31:0] mant = gf64_extract_mantissa(gf64);
            gf64_is_nan = ((exp == @as(i16, @intCast(EXP_MAX))) && (mant != 0));
        end
    endfunction

    // function: gf64_encode_f64
    function [31:0] gf64_encode_f64; // -> GF64
        input [31:0] value;
        begin
            if ((value == 0.0)) begin
                gf64_encode_f64 = (std.math.signbit(value)) ? (GF64_ZERO_NEG) : (GF64_ZERO_POS);
            end
            if (std.math.isNan(value)) begin
                gf64_encode_f64 = GF64_NAN;
            end
            if (std.math.isInf(value)) begin
                gf64_encode_f64 = ((value < 0.0)) ? (GF64_INF_NEG) : (GF64_INF_POS);
            end
            reg [31:0] sign = ((value < 0.0)) ? (-1) : (0);
            reg [31:0] abs_value = ((value < 0.0)) ? (-value) : (value);
            reg [63:0] f64_bits = @bitCast(abs_value);
            reg signed [15:0] f64_exp = (@intCast(((f64_bits >> 52) && 12'h7FF)) - 1023);
            reg [63:0] f64_mant = (f64_bits && 64'h000FFFFFFFFFFFFF);
            reg [31:0] gf64_exp = (f64_exp + BIAS);
            if ((gf64_exp < 0)) begin
                gf64_encode_f64 = ((sign < 0)) ? (GF64_ZERO_NEG) : (GF64_ZERO_POS);
            end else if ((gf64_exp > @as(i16, @intCast((EXP_MAX - 1))))) begin
                gf64_encode_f64 = ((sign < 0)) ? (GF64_INF_NEG) : (GF64_INF_POS);
            end
            reg [31:0] mant = (f64_mant >> 7);
            if (((discarded && 8'h40) != 0)) begin
                if ((((discarded && 8'h3F) != 0) || ((mant && 1) != 0))) begin
                    mant = mant + 1;
                    if ((mant > MANT_MASK)) begin
                        mant = 0;
                        if ((gf64_exp < @as(i16, @intCast((EXP_MAX - 1))))) begin
                            gf64_exp = gf64_exp + 1;
                        end
                    end
                end
            end
            gf64_encode_f64 = gf64_from_components(sign, gf64_exp, mant);
        end
    endfunction

    // function: gf64_decode_f64
    function [31:0] gf64_decode_f64; // -> f64
        input [31:0] gf64;
        begin
            if (gf64_is_zero(gf64)) begin
                gf64_decode_f64 = ((gf64_extract_sign(gf64) < 0)) ? (-0.0) : (0.0);
            end
            if (gf64_is_nan(gf64)) begin
                gf64_decode_f64 = std.math.nan(f64);
            end
            if (gf64_is_inf(gf64)) begin
                gf64_decode_f64 = ((gf64_extract_sign(gf64) < 0)) ? (-std.math.inf(f64)) : (std.math.inf(f64));
            end
            reg [31:0] sign = gf64_extract_sign(gf64);
            reg [31:0] exp = gf64_extract_exponent(gf64);
            reg [31:0] mant = gf64_extract_mantissa(gf64);
            reg [31:0] bias_adjusted = (@as(i64, exp) - @as(i64, BIAS));
            reg [31:0] mant_f64 = (@as(f64, @floatFromInt(mant)) / @as(f64, @floatFromInt(MANT_DIVISOR)));
            reg [31:0] value = (mant_f64 * std.math.pow(f64, 2.0, @as(f64, @floatFromInt(bias_adjusted))));
            gf64_decode_f64 = ((sign < 0)) ? (-value) : (value);
        end
    endfunction

    // function: gf64_add
    function [31:0] gf64_add; // -> GF64
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fa = gf64_decode_f64(a);
            reg [31:0] fb = gf64_decode_f64(b);
            gf64_add = gf64_encode_f64((fa + fb));
        end
    endfunction

    // function: gf64_sub
    function [31:0] gf64_sub; // -> GF64
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fa = gf64_decode_f64(a);
            reg [31:0] fb = gf64_decode_f64(b);
            gf64_sub = gf64_encode_f64((fa - fb));
        end
    endfunction

    // function: gf64_mul
    function [31:0] gf64_mul; // -> GF64
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fa = gf64_decode_f64(a);
            reg [31:0] fb = gf64_decode_f64(b);
            gf64_mul = gf64_encode_f64((fa * fb));
        end
    endfunction

    // function: gf64_div
    function [31:0] gf64_div; // -> GF64
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] fb = gf64_decode_f64(b);
            if ((fb == 0.0)) begin
                reg [31:0] fa = gf64_decode_f64(a);
                gf64_div = ((fa < 0.0)) ? (GF64_INF_NEG) : (GF64_INF_POS);
            end
            reg [31:0] fa = gf64_decode_f64(a);
            gf64_div = gf64_encode_f64((fa / fb));
        end
    endfunction

    // function: gf64_abs
    function [31:0] gf64_abs; // -> GF64
        input [31:0] gf64;
        begin
            gf64_abs = (gf64 && ~SIGN_MASK);
        end
    endfunction

    // function: gf64_neg
    function [31:0] gf64_neg; // -> GF64
        input [31:0] gf64;
        begin
            gf64_neg = (gf64 ^ SIGN_MASK);
        end
    endfunction

    // function: gf64_is_equal
    function gf64_is_equal; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((gf64_is_nan(a) || gf64_is_nan(b))) begin
                gf64_is_equal = 1'b0;
            end
            if ((gf64_is_zero(a) && gf64_is_zero(b))) begin
                gf64_is_equal = 1'b1;
            end
            gf64_is_equal = (a == b);
        end
    endfunction

    // function: gf64_is_greater
    function gf64_is_greater; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            if ((gf64_is_nan(a) || gf64_is_nan(b))) begin
                gf64_is_greater = 1'b0;
            end
            if ((sign_a != sign_b)) begin
                gf64_is_greater = (sign_a > sign_b);
            end
            if ((sign_a < 0)) begin
                gf64_is_greater = (gf64_neg(a) > gf64_neg(b));
            end
            gf64_is_greater = (a > b);
        end
    endfunction

    // function: gf64_max
    function [31:0] gf64_max; // -> GF64
        input [31:0] a;
        input [31:0] b;
        begin
            gf64_max = (gf64_is_greater(a, b)) ? (a) : (b);
        end
    endfunction

    // function: gf64_min
    function [31:0] gf64_min; // -> GF64
        input [31:0] a;
        input [31:0] b;
        begin
            gf64_min = (gf64_is_greater(a, b)) ? (b) : (a);
        end
    endfunction

    // function: gf64_clamp
    function [31:0] gf64_clamp; // -> GF64
        input [31:0] value;
        input [31:0] min;
        input [31:0] max;
        begin
            gf64_clamp = gf64_min(gf64_max(value, min), max);
        end
    endfunction

    // function: gf64_lerp
    function [31:0] gf64_lerp; // -> GF64
        input [31:0] a;
        input [31:0] b;
        input [31:0] t;
        begin
            reg [31:0] ft = gf64_decode_f64(t);
            reg [31:0] result = ((gf64_decode_f64(a) * (1.0 - ft)) + (gf64_decode_f64(b) * ft));
            gf64_lerp = gf64_encode_f64(result);
        end
    endfunction

    // function: gf64_from_u32
    function [31:0] gf64_from_u32; // -> GF64
        input [31:0] value;
        begin
            gf64_from_u32 = gf64_encode_f64(@as(f64, @floatFromInt(value)));
        end
    endfunction

    // function: gf64_to_u32
    function [31:0] gf64_to_u32; // -> u32
        input [31:0] gf64;
        begin
            if ((gf64_is_nan(gf64) || gf64_is_inf(gf64))) begin
                gf64_to_u32 = null;
            end
            reg [31:0] value = gf64_decode_f64(gf64);
            if (((value < 0.0) || (value > @as(f64, @floatFromInt(std.math.maxInt(u32)))))) begin
                gf64_to_u32 = null;
            end
            gf64_to_u32 = @as(u32, @intFromFloat(value));
        end
    endfunction

    // function: gf64_from_i32
    function [31:0] gf64_from_i32; // -> GF64
        input signed [31:0] value;
        begin
            gf64_from_i32 = gf64_encode_f64(@as(f64, @floatFromInt(value)));
        end
    endfunction

    // function: gf64_to_i32
    function signed [31:0] gf64_to_i32; // -> i32
        input [31:0] gf64;
        begin
            if ((gf64_is_nan(gf64) || gf64_is_inf(gf64))) begin
                gf64_to_i32 = null;
            end
            reg [31:0] value = gf64_decode_f64(gf64);
            if (((value < @as(f64, @floatFromInt(std.math.minInt(i32)))) || (value > @as(f64, @floatFromInt(std.math.maxInt(i32)))))) begin
                gf64_to_i32 = null;
            end
            gf64_to_i32 = @as(i32, @intFromFloat(value));
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: gf64_extract_sign_positive
    initial begin : gf64_extract_sign_positive_test
        $display("[TEST] gf64_extract_sign_positive : starting");
        $display("[TEST] gf64_extract_sign_positive : PASSED");
    end
    // test: gf64_extract_sign_negative
    initial begin : gf64_extract_sign_negative_test
        $display("[TEST] gf64_extract_sign_negative : starting");
        $display("[TEST] gf64_extract_sign_negative : PASSED");
    end
    // test: gf64_extract_exponent_middle
    initial begin : gf64_extract_exponent_middle_test
        $display("[TEST] gf64_extract_exponent_middle : starting");
        $display("[TEST] gf64_extract_exponent_middle : PASSED");
    end
    // test: gf64_extract_mantissa_max
    initial begin : gf64_extract_mantissa_max_test
        $display("[TEST] gf64_extract_mantissa_max : starting");
        $display("[TEST] gf64_extract_mantissa_max : PASSED");
    end
    // test: gf64_is_zero_positive
    initial begin : gf64_is_zero_positive_test
        $display("[TEST] gf64_is_zero_positive : starting");
        $display("[TEST] gf64_is_zero_positive : PASSED");
    end
    // test: gf64_is_zero_negative
    initial begin : gf64_is_zero_negative_test
        $display("[TEST] gf64_is_zero_negative : starting");
        $display("[TEST] gf64_is_zero_negative : PASSED");
    end
    // test: gf64_is_zero_nonzero
    initial begin : gf64_is_zero_nonzero_test
        $display("[TEST] gf64_is_zero_nonzero : starting");
        $display("[TEST] gf64_is_zero_nonzero : PASSED");
    end
    // test: gf64_is_special_inf
    initial begin : gf64_is_special_inf_test
        $display("[TEST] gf64_is_special_inf : starting");
        $display("[TEST] gf64_is_special_inf : PASSED");
    end
    // test: gf64_is_special_nan
    initial begin : gf64_is_special_nan_test
        $display("[TEST] gf64_is_special_nan : starting");
        $display("[TEST] gf64_is_special_nan : PASSED");
    end
    // test: gf64_is_special_normal
    initial begin : gf64_is_special_normal_test
        $display("[TEST] gf64_is_special_normal : starting");
        $display("[TEST] gf64_is_special_normal : PASSED");
    end
    // test: gf64_is_inf_positive
    initial begin : gf64_is_inf_positive_test
        $display("[TEST] gf64_is_inf_positive : starting");
        $display("[TEST] gf64_is_inf_positive : PASSED");
    end
    // test: gf64_is_inf_negative
    initial begin : gf64_is_inf_negative_test
        $display("[TEST] gf64_is_inf_negative : starting");
        $display("[TEST] gf64_is_inf_negative : PASSED");
    end
    // test: gf64_is_inf_not_nan
    initial begin : gf64_is_inf_not_nan_test
        $display("[TEST] gf64_is_inf_not_nan : starting");
        $display("[TEST] gf64_is_inf_not_nan : PASSED");
    end
    // test: gf64_is_nan
    initial begin : gf64_is_nan_test
        $display("[TEST] gf64_is_nan : starting");
        $display("[TEST] gf64_is_nan : PASSED");
    end
    // test: gf64_is_nan_not_inf
    initial begin : gf64_is_nan_not_inf_test
        $display("[TEST] gf64_is_nan_not_inf : starting");
        $display("[TEST] gf64_is_nan_not_inf : PASSED");
    end
    // test: gf64_encode_f64_zero
    initial begin : gf64_encode_f64_zero_test
        $display("[TEST] gf64_encode_f64_zero : starting");
        $display("[TEST] gf64_encode_f64_zero : PASSED");
    end
    // test: gf64_encode_f64_negative_zero
    initial begin : gf64_encode_f64_negative_zero_test
        $display("[TEST] gf64_encode_f64_negative_zero : starting");
        $display("[TEST] gf64_encode_f64_negative_zero : PASSED");
    end
    // test: gf64_encode_f64_one
    initial begin : gf64_encode_f64_one_test
        $display("[TEST] gf64_encode_f64_one : starting");
        $display("[TEST] gf64_encode_f64_one : PASSED");
    end
    // test: gf64_encode_f64_negative_one
    initial begin : gf64_encode_f64_negative_one_test
        $display("[TEST] gf64_encode_f64_negative_one : starting");
        $display("[TEST] gf64_encode_f64_negative_one : PASSED");
    end
    // test: gf64_encode_f64_two_pow_ten
    initial begin : gf64_encode_f64_two_pow_ten_test
        $display("[TEST] gf64_encode_f64_two_pow_ten : starting");
        $display("[TEST] gf64_encode_f64_two_pow_ten : PASSED");
    end
    // test: gf64_encode_f64_pi
    initial begin : gf64_encode_f64_pi_test
        $display("[TEST] gf64_encode_f64_pi : starting");
        $display("[TEST] gf64_encode_f64_pi : PASSED");
    end
    // test: gf64_decode_f64_roundtrip_positive
    initial begin : gf64_decode_f64_roundtrip_positive_test
        $display("[TEST] gf64_decode_f64_roundtrip_positive : starting");
        $display("[TEST] gf64_decode_f64_roundtrip_positive : PASSED");
    end
    // test: gf64_decode_f64_roundtrip_negative
    initial begin : gf64_decode_f64_roundtrip_negative_test
        $display("[TEST] gf64_decode_f64_roundtrip_negative : starting");
        $display("[TEST] gf64_decode_f64_roundtrip_negative : PASSED");
    end
    // test: gf64_add_simple
    initial begin : gf64_add_simple_test
        $display("[TEST] gf64_add_simple : starting");
        $display("[TEST] gf64_add_simple : PASSED");
    end
    // test: gf64_sub_simple
    initial begin : gf64_sub_simple_test
        $display("[TEST] gf64_sub_simple : starting");
        $display("[TEST] gf64_sub_simple : PASSED");
    end
    // test: gf64_mul_simple
    initial begin : gf64_mul_simple_test
        $display("[TEST] gf64_mul_simple : starting");
        $display("[TEST] gf64_mul_simple : PASSED");
    end
    // test: gf64_div_simple
    initial begin : gf64_div_simple_test
        $display("[TEST] gf64_div_simple : starting");
        $display("[TEST] gf64_div_simple : PASSED");
    end
    // test: gf64_abs_positive
    initial begin : gf64_abs_positive_test
        $display("[TEST] gf64_abs_positive : starting");
        $display("[TEST] gf64_abs_positive : PASSED");
    end
    // test: gf64_abs_negative
    initial begin : gf64_abs_negative_test
        $display("[TEST] gf64_abs_negative : starting");
        $display("[TEST] gf64_abs_negative : PASSED");
    end
    // test: gf64_neg
    initial begin : gf64_neg_test
        $display("[TEST] gf64_neg : starting");
        $display("[TEST] gf64_neg : PASSED");
    end
    // test: gf64_is_equal_same
    initial begin : gf64_is_equal_same_test
        $display("[TEST] gf64_is_equal_same : starting");
        $display("[TEST] gf64_is_equal_same : PASSED");
    end
    // test: gf64_is_equal_different
    initial begin : gf64_is_equal_different_test
        $display("[TEST] gf64_is_equal_different : starting");
        $display("[TEST] gf64_is_equal_different : PASSED");
    end
    // test: gf64_is_equal_nan
    initial begin : gf64_is_equal_nan_test
        $display("[TEST] gf64_is_equal_nan : starting");
        $display("[TEST] gf64_is_equal_nan : PASSED");
    end
    // test: gf64_is_equal_zero
    initial begin : gf64_is_equal_zero_test
        $display("[TEST] gf64_is_equal_zero : starting");
        $display("[TEST] gf64_is_equal_zero : PASSED");
    end
    // test: gf64_is_greater_positive
    initial begin : gf64_is_greater_positive_test
        $display("[TEST] gf64_is_greater_positive : starting");
        $display("[TEST] gf64_is_greater_positive : PASSED");
    end
    // test: gf64_is_greater_negative
    initial begin : gf64_is_greater_negative_test
        $display("[TEST] gf64_is_greater_negative : starting");
        $display("[TEST] gf64_is_greater_negative : PASSED");
    end
    // test: gf64_is_greater_positive_vs_negative
    initial begin : gf64_is_greater_positive_vs_negative_test
        $display("[TEST] gf64_is_greater_positive_vs_negative : starting");
        $display("[TEST] gf64_is_greater_positive_vs_negative : PASSED");
    end
    // test: gf64_max_returns_larger
    initial begin : gf64_max_returns_larger_test
        $display("[TEST] gf64_max_returns_larger : starting");
        $display("[TEST] gf64_max_returns_larger : PASSED");
    end
    // test: gf64_min_returns_smaller
    initial begin : gf64_min_returns_smaller_test
        $display("[TEST] gf64_min_returns_smaller : starting");
        $display("[TEST] gf64_min_returns_smaller : PASSED");
    end
    // test: gf64_clamp_within_range
    initial begin : gf64_clamp_within_range_test
        $display("[TEST] gf64_clamp_within_range : starting");
        $display("[TEST] gf64_clamp_within_range : PASSED");
    end
    // test: gf64_clamp_below_min
    initial begin : gf64_clamp_below_min_test
        $display("[TEST] gf64_clamp_below_min : starting");
        $display("[TEST] gf64_clamp_below_min : PASSED");
    end
    // test: gf64_clamp_above_max
    initial begin : gf64_clamp_above_max_test
        $display("[TEST] gf64_clamp_above_max : starting");
        $display("[TEST] gf64_clamp_above_max : PASSED");
    end
    // test: gf64_lerp_zero
    initial begin : gf64_lerp_zero_test
        $display("[TEST] gf64_lerp_zero : starting");
        $display("[TEST] gf64_lerp_zero : PASSED");
    end
    // test: gf64_lerp_one
    initial begin : gf64_lerp_one_test
        $display("[TEST] gf64_lerp_one : starting");
        $display("[TEST] gf64_lerp_one : PASSED");
    end
    // test: gf64_lerp_half
    initial begin : gf64_lerp_half_test
        $display("[TEST] gf64_lerp_half : starting");
        $display("[TEST] gf64_lerp_half : PASSED");
    end
    // test: gf64_from_u32_zero
    initial begin : gf64_from_u32_zero_test
        $display("[TEST] gf64_from_u32_zero : starting");
        $display("[TEST] gf64_from_u32_zero : PASSED");
    end
    // test: gf64_from_u32_max
    initial begin : gf64_from_u32_max_test
        $display("[TEST] gf64_from_u32_max : starting");
        $display("[TEST] gf64_from_u32_max : PASSED");
    end
    // test: gf64_to_u32_success
    initial begin : gf64_to_u32_success_test
        $display("[TEST] gf64_to_u32_success : starting");
        $display("[TEST] gf64_to_u32_success : PASSED");
    end
    // test: gf64_to_u32_negative
    initial begin : gf64_to_u32_negative_test
        $display("[TEST] gf64_to_u32_negative : starting");
        $display("[TEST] gf64_to_u32_negative : PASSED");
    end
    // test: gf64_to_u32_nan
    initial begin : gf64_to_u32_nan_test
        $display("[TEST] gf64_to_u32_nan : starting");
        $display("[TEST] gf64_to_u32_nan : PASSED");
    end
    // test: gf64_from_i32_zero
    initial begin : gf64_from_i32_zero_test
        $display("[TEST] gf64_from_i32_zero : starting");
        $display("[TEST] gf64_from_i32_zero : PASSED");
    end
    // test: gf64_from_i32_negative
    initial begin : gf64_from_i32_negative_test
        $display("[TEST] gf64_from_i32_negative : starting");
        $display("[TEST] gf64_from_i32_negative : PASSED");
    end
    // test: gf64_to_i32_positive
    initial begin : gf64_to_i32_positive_test
        $display("[TEST] gf64_to_i32_positive : starting");
        $display("[TEST] gf64_to_i32_positive : PASSED");
    end
    // test: gf64_to_i32_negative
    initial begin : gf64_to_i32_negative_test
        $display("[TEST] gf64_to_i32_negative : starting");
        $display("[TEST] gf64_to_i32_negative : PASSED");
    end
    // test: gf64_from_components_roundtrip
    initial begin : gf64_from_components_roundtrip_test
        $display("[TEST] gf64_from_components_roundtrip : starting");
        $display("[TEST] gf64_from_components_roundtrip : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: gf64_sign_mask_single_bit
    // invariant: gf64_exp_mask_no_sign
    // invariant: gf64_mant_mask_no_sign_exp
    // invariant: gf64_masks_cover_all_bits
    // invariant: gf64_bias_power_of_two_minus_one
    // invariant: gf64_special_exp_all_ones
    // invariant: gf64_zero_pos_no_sign
    // invariant: gf64_zero_neg_has_sign
    // invariant: gf64_inf_pos_max_exp
    // invariant: gf64_nan_has_mantissa
    // invariant: gf64_abs_removes_sign
    // invariant: gf64_neg_toggles_sign
    // invariant: gf64_from_u32_zero
    // invariant: gf64_from_i32_zero

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : gf64_extract_sign_latency_bench // synthesis translate_off
        $display("[BENCH] gf64_extract_sign_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf64_extract_sign_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf64_extract_sign_latency : DONE");
    end // synthesis translate_on
    initial begin : gf64_extract_exponent_latency_bench // synthesis translate_off
        $display("[BENCH] gf64_extract_exponent_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf64_extract_exponent_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf64_extract_exponent_latency : DONE");
    end // synthesis translate_on
    initial begin : gf64_encode_f64_latency_bench // synthesis translate_off
        $display("[BENCH] gf64_encode_f64_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf64_encode_f64_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf64_encode_f64_latency : DONE");
    end // synthesis translate_on
    initial begin : gf64_decode_f64_latency_bench // synthesis translate_off
        $display("[BENCH] gf64_decode_f64_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf64_decode_f64_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf64_decode_f64_latency : DONE");
    end // synthesis translate_on
    initial begin : gf64_add_latency_bench // synthesis translate_off
        $display("[BENCH] gf64_add_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf64_add_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf64_add_latency : DONE");
    end // synthesis translate_on
    initial begin : gf64_mul_latency_bench // synthesis translate_off
        $display("[BENCH] gf64_mul_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] gf64_mul_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] gf64_mul_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
