// ============================================================================
// Generated from t27 spec: triformat_int8
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module triformat_int8 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] BITS = 8;
    parameter signed [7:0] MIN = -128;
    parameter signed [7:0] MAX = 127;
    parameter [15:0] RANGE = 256;
    parameter [7:0] MASK = 8'hFF;
    parameter [31:0] Int8 = i8;

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: int8_from_i8
    function [31:0] int8_from_i8; // -> Int8
        input signed [7:0] value;
        begin
            int8_from_i8 = value;
        end
    endfunction

    // function: int8_from_i16
    function [31:0] int8_from_i16; // -> Int8
        input signed [15:0] value;
        begin
            if ((value < @as(i16, MIN))) begin
                int8_from_i16 = MIN;
            end else if ((value > @as(i16, MAX))) begin
                int8_from_i16 = MAX;
            end
            int8_from_i16 = @as(i8, @intCast(value));
        end
    endfunction

    // function: int8_from_i32
    function [31:0] int8_from_i32; // -> Int8
        input signed [31:0] value;
        begin
            if ((value < @as(i32, MIN))) begin
                int8_from_i32 = MIN;
            end else if ((value > @as(i32, MAX))) begin
                int8_from_i32 = MAX;
            end
            int8_from_i32 = @as(i8, @intCast(value));
        end
    endfunction

    // function: int8_from_u8
    function [31:0] int8_from_u8; // -> Int8
        input [7:0] value;
        begin
            if ((value > 127)) begin
                int8_from_u8 = MAX;
            end
            int8_from_u8 = @as(i8, @bitCast(value));
        end
    endfunction

    // function: int8_from_f32
    function [31:0] int8_from_f32; // -> Int8
        input [31:0] value;
        begin
            if (std.math.isNan(value)) begin
                int8_from_f32 = 0;
            end
            if ((value > (@as(f32, @floatFromInt(MAX)) + 0.5))) begin
                int8_from_f32 = MAX;
            end
            if ((value < (@as(f32, @floatFromInt(MIN)) - 0.5))) begin
                int8_from_f32 = MIN;
            end
            reg [31:0] rounded = @as(i32, @intFromFloat(@round(value)));
            int8_from_f32 = int8_from_i32(rounded);
        end
    endfunction

    // function: int8_from_f64
    function [31:0] int8_from_f64; // -> Int8
        input [31:0] value;
        begin
            if (std.math.isNan(value)) begin
                int8_from_f64 = 0;
            end
            if ((value > (@as(f64, @floatFromInt(MAX)) + 0.5))) begin
                int8_from_f64 = MAX;
            end
            if ((value < (@as(f64, @floatFromInt(MIN)) - 0.5))) begin
                int8_from_f64 = MIN;
            end
            reg [31:0] rounded = @as(i32, @intFromFloat(@round(value)));
            int8_from_f64 = int8_from_i32(rounded);
        end
    endfunction

    // function: int8_to_i8
    function signed [7:0] int8_to_i8; // -> i8
        input [31:0] value;
        begin
            int8_to_i8 = value;
        end
    endfunction

    // function: int8_to_i16
    function signed [15:0] int8_to_i16; // -> i16
        input [31:0] value;
        begin
            int8_to_i16 = @as(i16, value);
        end
    endfunction

    // function: int8_to_i32
    function signed [31:0] int8_to_i32; // -> i32
        input [31:0] value;
        begin
            int8_to_i32 = @as(i32, value);
        end
    endfunction

    // function: int8_to_u8
    function [7:0] int8_to_u8; // -> u8
        input [31:0] value;
        begin
            if ((value < 0)) begin
                int8_to_u8 = null;
            end
            int8_to_u8 = @as(u8, @intCast(value));
        end
    endfunction

    // function: int8_to_f32
    function [31:0] int8_to_f32; // -> f32
        input [31:0] value;
        begin
            int8_to_f32 = @as(f32, @floatFromInt(value));
        end
    endfunction

    // function: int8_to_f64
    function [31:0] int8_to_f64; // -> f64
        input [31:0] value;
        begin
            int8_to_f64 = @as(f64, @floatFromInt(value));
        end
    endfunction

    // function: int8_add
    function [31:0] int8_add; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] result = (@as(i16, a) + @as(i16, b));
            int8_add = int8_from_i16(result);
        end
    endfunction

    // function: int8_sub
    function [31:0] int8_sub; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] result = (@as(i16, a) - @as(i16, b));
            int8_sub = int8_from_i16(result);
        end
    endfunction

    // function: int8_mul
    function [31:0] int8_mul; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] result = (@as(i16, a) * @as(i16, b));
            int8_mul = int8_from_i16(result);
        end
    endfunction

    // function: int8_div
    function [31:0] int8_div; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            if ((b == 0)) begin
                int8_div = ((a >= 0)) ? (MAX) : (MIN);
            end
            int8_div = (a / b);
        end
    endfunction

    // function: int8_mod
    function [31:0] int8_mod; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            if ((b == 0)) begin
                int8_mod = 0;
            end
            reg [31:0] result = @rem(a, b);
            int8_mod = ((result < 0)) ? ((result + b)) : (result);
        end
    endfunction

    // function: int8_pow
    function [31:0] int8_pow; // -> Int8
        input [31:0] base;
        input [7:0] exp;
        begin
            if ((exp == 0)) begin
                int8_pow = 1;
            end
            if ((base == 0)) begin
                int8_pow = 0;
            end
            if ((base == 1)) begin
                int8_pow = 1;
            end
            if ((base == -1)) begin
                int8_pow = (((exp % 2) == 0)) ? (1) : (-1);
            end
            reg signed [15:0] result = 1;
            while ((exp > 0)) begin
                if (((exp % 2) == 1)) begin
                    result = (result * current);
                    if ((result > MAX)) begin
                        int8_pow = MAX;
                    end
                    if ((result < MIN)) begin
                        int8_pow = MIN;
                    end
                end
                current = (current * current);
                if ((current > MAX)) begin
                    int8_pow = MAX;
                end
                if ((current < MIN)) begin
                    int8_pow = MIN;
                end
                remaining = (exp / 2);
            end
            int8_pow = int8_from_i16(result);
        end
    endfunction

    // function: int8_and
    function [31:0] int8_and; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            int8_and = (a && b);
        end
    endfunction

    // function: int8_or
    function [31:0] int8_or; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            int8_or = (a || b);
        end
    endfunction

    // function: int8_xor
    function [31:0] int8_xor; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            int8_xor = (a ^ b);
        end
    endfunction

    // function: int8_not
    function [31:0] int8_not; // -> Int8
        input [31:0] value;
        begin
            int8_not = ~value;
        end
    endfunction

    // function: int8_shl
    function [31:0] int8_shl; // -> Int8
        input [31:0] value;
        input [7:0] amount;
        begin
            reg [31:0] clamped = @min(amount, 7);
            reg [31:0] result = (@as(i16, value) << clamped);
            int8_shl = int8_from_i16(result);
        end
    endfunction

    // function: int8_shr
    function [31:0] int8_shr; // -> Int8
        input [31:0] value;
        input [7:0] amount;
        begin
            reg [31:0] clamped = @min(amount, 7);
            int8_shr = @shrExact(value, clamped);
        end
    endfunction

    // function: int8_rol
    function [31:0] int8_rol; // -> Int8
        input [31:0] value;
        input [7:0] amount;
        begin
            reg [31:0] clamped = (amount % 8);
            reg [31:0] uval = @as(u8, @bitCast(value));
            reg [31:0] result = ((uval << clamped) || (uval >> (8 - clamped)));
            int8_rol = @as(i8, @bitCast(result));
        end
    endfunction

    // function: int8_ror
    function [31:0] int8_ror; // -> Int8
        input [31:0] value;
        input [7:0] amount;
        begin
            reg [31:0] clamped = (amount % 8);
            reg [31:0] uval = @as(u8, @bitCast(value));
            reg [31:0] result = ((uval >> clamped) || (uval << (8 - clamped)));
            int8_ror = @as(i8, @bitCast(result));
        end
    endfunction

    // function: int8_abs
    function [31:0] int8_abs; // -> Int8
        input [31:0] value;
        begin
            if ((value == MIN)) begin
                int8_abs = MAX;
            end
            int8_abs = ((value < 0)) ? (-value) : (value);
        end
    endfunction

    // function: int8_neg
    function [31:0] int8_neg; // -> Int8
        input [31:0] value;
        begin
            if ((value == MIN)) begin
                int8_neg = MAX;
            end
            int8_neg = -value;
        end
    endfunction

    // function: int8_sign
    function [31:0] int8_sign; // -> Int8
        input [31:0] value;
        begin
            if ((value < 0)) begin
                int8_sign = -1;
            end else if ((value > 0)) begin
                int8_sign = 1;
            end
            int8_sign = 0;
        end
    endfunction

    // function: int8_is_equal
    function int8_is_equal; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            int8_is_equal = (a == b);
        end
    endfunction

    // function: int8_is_greater
    function int8_is_greater; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            int8_is_greater = (a > b);
        end
    endfunction

    // function: int8_is_less
    function int8_is_less; // -> bool
        input [31:0] a;
        input [31:0] b;
        begin
            int8_is_less = (a < b);
        end
    endfunction

    // function: int8_min
    function [31:0] int8_min; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            int8_min = ((a < b)) ? (a) : (b);
        end
    endfunction

    // function: int8_max
    function [31:0] int8_max; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            int8_max = ((a > b)) ? (a) : (b);
        end
    endfunction

    // function: int8_clamp
    function [31:0] int8_clamp; // -> Int8
        input [31:0] value;
        input [31:0] min;
        input [31:0] max;
        begin
            if ((value < min)) begin
                int8_clamp = min;
            end else if ((value > max)) begin
                int8_clamp = max;
            end
            int8_clamp = value;
        end
    endfunction

    // function: int8_lerp
    function [31:0] int8_lerp; // -> Int8
        input [31:0] a;
        input [31:0] b;
        input [31:0] t;
        begin
            reg [31:0] fa = @as(f32, @floatFromInt(a));
            reg [31:0] fb = @as(f32, @floatFromInt(b));
            reg [31:0] result = (fa + ((fb - fa) * t));
            int8_lerp = int8_from_f32(result);
        end
    endfunction

    // function: int8_sq
    function [31:0] int8_sq; // -> Int8
        input [31:0] value;
        begin
            int8_sq = int8_mul(value, value);
        end
    endfunction

    // function: int8_abs_diff
    function [31:0] int8_abs_diff; // -> Int8
        input [31:0] a;
        input [31:0] b;
        begin
            reg [31:0] diff = int8_sub(a, b);
            int8_abs_diff = int8_abs(diff);
        end
    endfunction

    // function: int8_sqrt
    function [31:0] int8_sqrt; // -> Int8
        input [31:0] value;
        begin
            if ((value < 0)) begin
                int8_sqrt = 0;
            end
            if ((value == 0)) begin
                int8_sqrt = 0;
            end
            reg signed [7:0] result = 0;
            reg signed [7:0] bit = 1;
            while (((bit <= value) && (bit > 0))) begin
                bit = (bit * 4);
            end
            while ((bit != 0)) begin
                if ((value >= (result + bit))) begin
                    value = (value - (result + bit));
                    result = ((result / 2) + bit);
                end else begin
                    result = (result / 2);
                end
                bit = (bit / 4);
            end
            int8_sqrt = result;
        end
    endfunction

    // function: int8_is_power_of_two
    function int8_is_power_of_two; // -> bool
        input [31:0] value;
        begin
            if ((value <= 0)) begin
                int8_is_power_of_two = 1'b0;
            end
            reg [31:0] uval = @as(u8, @bitCast(value));
            int8_is_power_of_two = ((uval && (uval - 1)) == 0);
        end
    endfunction

    // function: int8_count_ones
    function [7:0] int8_count_ones; // -> u8
        input [31:0] value;
        begin
            reg [31:0] uval = @as(u8, @bitCast(value));
            int8_count_ones = @popCount(uval);
        end
    endfunction

    // function: int8_count_zeros
    function [7:0] int8_count_zeros; // -> u8
        input [31:0] value;
        begin
            int8_count_zeros = (8 - int8_count_ones(value));
        end
    endfunction

    // function: int8_reverse_bits
    function [31:0] int8_reverse_bits; // -> Int8
        input [31:0] value;
        begin
            reg [7:0] result = 0;
            while ((i < 8)) begin
                result = ((result << 1) || (uval && 1));
                uval = (uval >> 1);
                i = (i + 1);
            end
            int8_reverse_bits = @as(i8, @bitCast(result));
        end
    endfunction
    // -------------------------------------------------------
    // Test assertions (from test blocks)
    // -------------------------------------------------------
    // synthesis translate_off
    // test: int8_from_i8_identity
    initial begin : int8_from_i8_identity_test
        $display("[TEST] int8_from_i8_identity : starting");
        $display("[TEST] int8_from_i8_identity : PASSED");
    end
    // test: int8_from_i16_positive
    initial begin : int8_from_i16_positive_test
        $display("[TEST] int8_from_i16_positive : starting");
        $display("[TEST] int8_from_i16_positive : PASSED");
    end
    // test: int8_from_i16_overflow
    initial begin : int8_from_i16_overflow_test
        $display("[TEST] int8_from_i16_overflow : starting");
        $display("[TEST] int8_from_i16_overflow : PASSED");
    end
    // test: int8_from_i16_negative
    initial begin : int8_from_i16_negative_test
        $display("[TEST] int8_from_i16_negative : starting");
        $display("[TEST] int8_from_i16_negative : PASSED");
    end
    // test: int8_from_i16_underflow
    initial begin : int8_from_i16_underflow_test
        $display("[TEST] int8_from_i16_underflow : starting");
        $display("[TEST] int8_from_i16_underflow : PASSED");
    end
    // test: int8_from_i32_in_range
    initial begin : int8_from_i32_in_range_test
        $display("[TEST] int8_from_i32_in_range : starting");
        $display("[TEST] int8_from_i32_in_range : PASSED");
    end
    // test: int8_from_i32_overflow
    initial begin : int8_from_i32_overflow_test
        $display("[TEST] int8_from_i32_overflow : starting");
        $display("[TEST] int8_from_i32_overflow : PASSED");
    end
    // test: int8_from_u8_in_range
    initial begin : int8_from_u8_in_range_test
        $display("[TEST] int8_from_u8_in_range : starting");
        $display("[TEST] int8_from_u8_in_range : PASSED");
    end
    // test: int8_from_u8_overflow
    initial begin : int8_from_u8_overflow_test
        $display("[TEST] int8_from_u8_overflow : starting");
        $display("[TEST] int8_from_u8_overflow : PASSED");
    end
    // test: int8_from_f32_zero
    initial begin : int8_from_f32_zero_test
        $display("[TEST] int8_from_f32_zero : starting");
        $display("[TEST] int8_from_f32_zero : PASSED");
    end
    // test: int8_from_f32_one
    initial begin : int8_from_f32_one_test
        $display("[TEST] int8_from_f32_one : starting");
        $display("[TEST] int8_from_f32_one : PASSED");
    end
    // test: int8_from_f32_round_up
    initial begin : int8_from_f32_round_up_test
        $display("[TEST] int8_from_f32_round_up : starting");
        $display("[TEST] int8_from_f32_round_up : PASSED");
    end
    // test: int8_from_f32_round_down
    initial begin : int8_from_f32_round_down_test
        $display("[TEST] int8_from_f32_round_down : starting");
        $display("[TEST] int8_from_f32_round_down : PASSED");
    end
    // test: int8_from_f32_nan
    initial begin : int8_from_f32_nan_test
        $display("[TEST] int8_from_f32_nan : starting");
        $display("[TEST] int8_from_f32_nan : PASSED");
    end
    // test: int8_to_i8_identity
    initial begin : int8_to_i8_identity_test
        $display("[TEST] int8_to_i8_identity : starting");
        $display("[TEST] int8_to_i8_identity : PASSED");
    end
    // test: int8_to_i16_sign_extend
    initial begin : int8_to_i16_sign_extend_test
        $display("[TEST] int8_to_i16_sign_extend : starting");
        $display("[TEST] int8_to_i16_sign_extend : PASSED");
    end
    // test: int8_to_i32_sign_extend
    initial begin : int8_to_i32_sign_extend_test
        $display("[TEST] int8_to_i32_sign_extend : starting");
        $display("[TEST] int8_to_i32_sign_extend : PASSED");
    end
    // test: int8_to_u8_positive
    initial begin : int8_to_u8_positive_test
        $display("[TEST] int8_to_u8_positive : starting");
        $display("[TEST] int8_to_u8_positive : PASSED");
    end
    // test: int8_to_u8_negative
    initial begin : int8_to_u8_negative_test
        $display("[TEST] int8_to_u8_negative : starting");
        $display("[TEST] int8_to_u8_negative : PASSED");
    end
    // test: int8_add_simple
    initial begin : int8_add_simple_test
        $display("[TEST] int8_add_simple : starting");
        $display("[TEST] int8_add_simple : PASSED");
    end
    // test: int8_add_overflow
    initial begin : int8_add_overflow_test
        $display("[TEST] int8_add_overflow : starting");
        $display("[TEST] int8_add_overflow : PASSED");
    end
    // test: int8_add_underflow
    initial begin : int8_add_underflow_test
        $display("[TEST] int8_add_underflow : starting");
        $display("[TEST] int8_add_underflow : PASSED");
    end
    // test: int8_sub_simple
    initial begin : int8_sub_simple_test
        $display("[TEST] int8_sub_simple : starting");
        $display("[TEST] int8_sub_simple : PASSED");
    end
    // test: int8_sub_negative
    initial begin : int8_sub_negative_test
        $display("[TEST] int8_sub_negative : starting");
        $display("[TEST] int8_sub_negative : PASSED");
    end
    // test: int8_mul_positive
    initial begin : int8_mul_positive_test
        $display("[TEST] int8_mul_positive : starting");
        $display("[TEST] int8_mul_positive : PASSED");
    end
    // test: int8_mul_negative
    initial begin : int8_mul_negative_test
        $display("[TEST] int8_mul_negative : starting");
        $display("[TEST] int8_mul_negative : PASSED");
    end
    // test: int8_mul_overflow
    initial begin : int8_mul_overflow_test
        $display("[TEST] int8_mul_overflow : starting");
        $display("[TEST] int8_mul_overflow : PASSED");
    end
    // test: int8_div_simple
    initial begin : int8_div_simple_test
        $display("[TEST] int8_div_simple : starting");
        $display("[TEST] int8_div_simple : PASSED");
    end
    // test: int8_div_by_zero_positive
    initial begin : int8_div_by_zero_positive_test
        $display("[TEST] int8_div_by_zero_positive : starting");
        $display("[TEST] int8_div_by_zero_positive : PASSED");
    end
    // test: int8_div_by_zero_negative
    initial begin : int8_div_by_zero_negative_test
        $display("[TEST] int8_div_by_zero_negative : starting");
        $display("[TEST] int8_div_by_zero_negative : PASSED");
    end
    // test: int8_mod_simple
    initial begin : int8_mod_simple_test
        $display("[TEST] int8_mod_simple : starting");
        $display("[TEST] int8_mod_simple : PASSED");
    end
    // test: int8_mod_by_zero
    initial begin : int8_mod_by_zero_test
        $display("[TEST] int8_mod_by_zero : starting");
        $display("[TEST] int8_mod_by_zero : PASSED");
    end
    // test: int8_pow_zero
    initial begin : int8_pow_zero_test
        $display("[TEST] int8_pow_zero : starting");
        $display("[TEST] int8_pow_zero : PASSED");
    end
    // test: int8_pow_one
    initial begin : int8_pow_one_test
        $display("[TEST] int8_pow_one : starting");
        $display("[TEST] int8_pow_one : PASSED");
    end
    // test: int8_pow_two
    initial begin : int8_pow_two_test
        $display("[TEST] int8_pow_two : starting");
        $display("[TEST] int8_pow_two : PASSED");
    end
    // test: int8_pow_overflow
    initial begin : int8_pow_overflow_test
        $display("[TEST] int8_pow_overflow : starting");
        $display("[TEST] int8_pow_overflow : PASSED");
    end
    // test: int8_and_simple
    initial begin : int8_and_simple_test
        $display("[TEST] int8_and_simple : starting");
        $display("[TEST] int8_and_simple : PASSED");
    end
    // test: int8_or_simple
    initial begin : int8_or_simple_test
        $display("[TEST] int8_or_simple : starting");
        $display("[TEST] int8_or_simple : PASSED");
    end
    // test: int8_xor_simple
    initial begin : int8_xor_simple_test
        $display("[TEST] int8_xor_simple : starting");
        $display("[TEST] int8_xor_simple : PASSED");
    end
    // test: int8_not_simple
    initial begin : int8_not_simple_test
        $display("[TEST] int8_not_simple : starting");
        $display("[TEST] int8_not_simple : PASSED");
    end
    // test: int8_shl_simple
    initial begin : int8_shl_simple_test
        $display("[TEST] int8_shl_simple : starting");
        $display("[TEST] int8_shl_simple : PASSED");
    end
    // test: int8_shl_overflow
    initial begin : int8_shl_overflow_test
        $display("[TEST] int8_shl_overflow : starting");
        $display("[TEST] int8_shl_overflow : PASSED");
    end
    // test: int8_shr_simple
    initial begin : int8_shr_simple_test
        $display("[TEST] int8_shr_simple : starting");
        $display("[TEST] int8_shr_simple : PASSED");
    end
    // test: int8_rol_simple
    initial begin : int8_rol_simple_test
        $display("[TEST] int8_rol_simple : starting");
        $display("[TEST] int8_rol_simple : PASSED");
    end
    // test: int8_ror_simple
    initial begin : int8_ror_simple_test
        $display("[TEST] int8_ror_simple : starting");
        $display("[TEST] int8_ror_simple : PASSED");
    end
    // test: int8_abs_positive
    initial begin : int8_abs_positive_test
        $display("[TEST] int8_abs_positive : starting");
        $display("[TEST] int8_abs_positive : PASSED");
    end
    // test: int8_abs_negative
    initial begin : int8_abs_negative_test
        $display("[TEST] int8_abs_negative : starting");
        $display("[TEST] int8_abs_negative : PASSED");
    end
    // test: int8_abs_min
    initial begin : int8_abs_min_test
        $display("[TEST] int8_abs_min : starting");
        $display("[TEST] int8_abs_min : PASSED");
    end
    // test: int8_neg_positive
    initial begin : int8_neg_positive_test
        $display("[TEST] int8_neg_positive : starting");
        $display("[TEST] int8_neg_positive : PASSED");
    end
    // test: int8_neg_negative
    initial begin : int8_neg_negative_test
        $display("[TEST] int8_neg_negative : starting");
        $display("[TEST] int8_neg_negative : PASSED");
    end
    // test: int8_neg_min
    initial begin : int8_neg_min_test
        $display("[TEST] int8_neg_min : starting");
        $display("[TEST] int8_neg_min : PASSED");
    end
    // test: int8_sign_positive
    initial begin : int8_sign_positive_test
        $display("[TEST] int8_sign_positive : starting");
        $display("[TEST] int8_sign_positive : PASSED");
    end
    // test: int8_sign_negative
    initial begin : int8_sign_negative_test
        $display("[TEST] int8_sign_negative : starting");
        $display("[TEST] int8_sign_negative : PASSED");
    end
    // test: int8_sign_zero
    initial begin : int8_sign_zero_test
        $display("[TEST] int8_sign_zero : starting");
        $display("[TEST] int8_sign_zero : PASSED");
    end
    // test: int8_min_smaller
    initial begin : int8_min_smaller_test
        $display("[TEST] int8_min_smaller : starting");
        $display("[TEST] int8_min_smaller : PASSED");
    end
    // test: int8_max_larger
    initial begin : int8_max_larger_test
        $display("[TEST] int8_max_larger : starting");
        $display("[TEST] int8_max_larger : PASSED");
    end
    // test: int8_clamp_in_range
    initial begin : int8_clamp_in_range_test
        $display("[TEST] int8_clamp_in_range : starting");
        $display("[TEST] int8_clamp_in_range : PASSED");
    end
    // test: int8_clamp_below
    initial begin : int8_clamp_below_test
        $display("[TEST] int8_clamp_below : starting");
        $display("[TEST] int8_clamp_below : PASSED");
    end
    // test: int8_clamp_above
    initial begin : int8_clamp_above_test
        $display("[TEST] int8_clamp_above : starting");
        $display("[TEST] int8_clamp_above : PASSED");
    end
    // test: int8_lerp_zero
    initial begin : int8_lerp_zero_test
        $display("[TEST] int8_lerp_zero : starting");
        $display("[TEST] int8_lerp_zero : PASSED");
    end
    // test: int8_lerp_one
    initial begin : int8_lerp_one_test
        $display("[TEST] int8_lerp_one : starting");
        $display("[TEST] int8_lerp_one : PASSED");
    end
    // test: int8_lerp_half
    initial begin : int8_lerp_half_test
        $display("[TEST] int8_lerp_half : starting");
        $display("[TEST] int8_lerp_half : PASSED");
    end
    // test: int8_sq_positive
    initial begin : int8_sq_positive_test
        $display("[TEST] int8_sq_positive : starting");
        $display("[TEST] int8_sq_positive : PASSED");
    end
    // test: int8_sq_negative
    initial begin : int8_sq_negative_test
        $display("[TEST] int8_sq_negative : starting");
        $display("[TEST] int8_sq_negative : PASSED");
    end
    // test: int8_sq_overflow
    initial begin : int8_sq_overflow_test
        $display("[TEST] int8_sq_overflow : starting");
        $display("[TEST] int8_sq_overflow : PASSED");
    end
    // test: int8_abs_diff_same
    initial begin : int8_abs_diff_same_test
        $display("[TEST] int8_abs_diff_same : starting");
        $display("[TEST] int8_abs_diff_same : PASSED");
    end
    // test: int8_abs_diff_positive
    initial begin : int8_abs_diff_positive_test
        $display("[TEST] int8_abs_diff_positive : starting");
        $display("[TEST] int8_abs_diff_positive : PASSED");
    end
    // test: int8_sqrt_zero
    initial begin : int8_sqrt_zero_test
        $display("[TEST] int8_sqrt_zero : starting");
        $display("[TEST] int8_sqrt_zero : PASSED");
    end
    // test: int8_sqrt_one
    initial begin : int8_sqrt_one_test
        $display("[TEST] int8_sqrt_one : starting");
        $display("[TEST] int8_sqrt_one : PASSED");
    end
    // test: int8_sqrt_four
    initial begin : int8_sqrt_four_test
        $display("[TEST] int8_sqrt_four : starting");
        $display("[TEST] int8_sqrt_four : PASSED");
    end
    // test: int8_sqrt_sixteen
    initial begin : int8_sqrt_sixteen_test
        $display("[TEST] int8_sqrt_sixteen : starting");
        $display("[TEST] int8_sqrt_sixteen : PASSED");
    end
    // test: int8_sqrt_negative
    initial begin : int8_sqrt_negative_test
        $display("[TEST] int8_sqrt_negative : starting");
        $display("[TEST] int8_sqrt_negative : PASSED");
    end
    // test: int8_is_power_of_two_true
    initial begin : int8_is_power_of_two_true_test
        $display("[TEST] int8_is_power_of_two_true : starting");
        $display("[TEST] int8_is_power_of_two_true : PASSED");
    end
    // test: int8_is_power_of_two_false
    initial begin : int8_is_power_of_two_false_test
        $display("[TEST] int8_is_power_of_two_false : starting");
        $display("[TEST] int8_is_power_of_two_false : PASSED");
    end
    // test: int8_is_power_of_two_zero
    initial begin : int8_is_power_of_two_zero_test
        $display("[TEST] int8_is_power_of_two_zero : starting");
        $display("[TEST] int8_is_power_of_two_zero : PASSED");
    end
    // test: int8_count_ones_zero
    initial begin : int8_count_ones_zero_test
        $display("[TEST] int8_count_ones_zero : starting");
        $display("[TEST] int8_count_ones_zero : PASSED");
    end
    // test: int8_count_ones_all
    initial begin : int8_count_ones_all_test
        $display("[TEST] int8_count_ones_all : starting");
        $display("[TEST] int8_count_ones_all : PASSED");
    end
    // test: int8_count_ones_mixed
    initial begin : int8_count_ones_mixed_test
        $display("[TEST] int8_count_ones_mixed : starting");
        $display("[TEST] int8_count_ones_mixed : PASSED");
    end
    // test: int8_count_zeros_zero
    initial begin : int8_count_zeros_zero_test
        $display("[TEST] int8_count_zeros_zero : starting");
        $display("[TEST] int8_count_zeros_zero : PASSED");
    end
    // test: int8_count_zeros_all
    initial begin : int8_count_zeros_all_test
        $display("[TEST] int8_count_zeros_all : starting");
        $display("[TEST] int8_count_zeros_all : PASSED");
    end
    // test: int8_reverse_bits_zero
    initial begin : int8_reverse_bits_zero_test
        $display("[TEST] int8_reverse_bits_zero : starting");
        $display("[TEST] int8_reverse_bits_zero : PASSED");
    end
    // test: int8_reverse_bits_one
    initial begin : int8_reverse_bits_one_test
        $display("[TEST] int8_reverse_bits_one : starting");
        $display("[TEST] int8_reverse_bits_one : PASSED");
    end
    // test: int8_reverse_bits_all
    initial begin : int8_reverse_bits_all_test
        $display("[TEST] int8_reverse_bits_all : starting");
        $display("[TEST] int8_reverse_bits_all : PASSED");
    end
    // synthesis translate_on

    // -------------------------------------------------------
    // Invariant checks (compile-time assertions)
    // -------------------------------------------------------
    // invariant: int8_bits_constant
    // invariant: int8_min_is_negative_128
    // invariant: int8_max_is_127
    // invariant: int8_range_is_256
    // invariant: int8_mask_all_bits
    // invariant: int8_from_i16_min_saturates
    // invariant: int8_from_i16_max_saturates
    // invariant: int8_to_i16_identity
    // invariant: int8_to_u8_negative_null
    // invariant: int8_to_u8_positive_ok
    // invariant: int8_add_zero
    // invariant: int8_sub_zero
    // invariant: int8_mul_one
    // invariant: int8_mul_zero
    // invariant: int8_div_one
    // invariant: int8_pow_zero_one
    // invariant: int8_pow_one_self
    // invariant: int8_and_zero
    // invariant: int8_and_minus_one
    // invariant: int8_or_zero
    // invariant: int8_or_minus_one
    // invariant: int8_xor_zero
    // invariant: int8_xor_self
    // invariant: int8_not_double
    // invariant: int8_abs_non_negative
    // invariant: int8_neg_twice_original
    // invariant: int8_sign_positive_one
    // invariant: int8_sign_negative_minus_one
    // invariant: int8_sign_zero_zero
    // invariant: int8_min_le_both
    // invariant: int8_max_ge_both
    // invariant: int8_lerp_zero_start
    // invariant: int8_lerp_one_end
    // invariant: int8_sq_non_negative
    // invariant: int8_sqrt_square_original_or_less
    // invariant: int8_count_ones_plus_count_zeros_equals_bits
    // invariant: int8_reverse_bits_double

    // -------------------------------------------------------
    // Benchmark blocks (simulation only)
    // -------------------------------------------------------
    initial begin : int8_add_latency_bench // synthesis translate_off
        $display("[BENCH] int8_add_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] int8_add_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] int8_add_latency : DONE");
    end // synthesis translate_on
    initial begin : int8_mul_latency_bench // synthesis translate_off
        $display("[BENCH] int8_mul_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] int8_mul_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] int8_mul_latency : DONE");
    end // synthesis translate_on
    initial begin : int8_abs_latency_bench // synthesis translate_off
        $display("[BENCH] int8_abs_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] int8_abs_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] int8_abs_latency : DONE");
    end // synthesis translate_on
    initial begin : int8_from_f32_latency_bench // synthesis translate_off
        $display("[BENCH] int8_from_f32_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] int8_from_f32_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] int8_from_f32_latency : DONE");
    end // synthesis translate_on
    initial begin : int8_sqrt_latency_bench // synthesis translate_off
        $display("[BENCH] int8_sqrt_latency : starting");
        integer _bench_cycles = 0;
        $display("[BENCH] int8_sqrt_latency : %%0d cycles", _bench_cycles);
        $display("[BENCH] int8_sqrt_latency : DONE");
    end // synthesis translate_on

endmodule

`default_nettype wire
