// ============================================================================
// Generated from t27 spec: sacred_lut_npu_81_entry
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module sacred_lut_npu_81_entry (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] OP_LUT_NPU = 8'hE3;
    parameter [7:0] LUT_SIZE = 81;
    parameter [7:0] LUT_ADDR_BITS = 7;
    parameter [7:0] LUT_VALUE_BITS = 16;
    parameter [7:0] ENTRY_VALID = 1;
    parameter [7:0] ENTRY_INVALID = 0;
    parameter [7:0] PHI_CONST_BASE = 0;
    parameter [7:0] CONST_LUT_END = 80;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum NpuOperation
    localparam NpuOperation_lookup = 0;
    localparam NpuOperation_transform = 1;
    localparam NpuOperation_phi_project = 2;
    localparam NpuOperation_sparse_reduce = 3;
    localparam NpuOperation_quantize = 4;
    localparam NpuOperation_dequantize = 5;
    localparam NpuOperation_composite = 6;
    localparam NpuOperation_custom = 7;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct LutEntry
    reg [7:0] lutentry_address; // LutEntry.address
    reg [15:0] lutentry_value; // LutEntry.value
    reg lutentry_valid; // LutEntry.valid
    reg lutentry_phi_related; // LutEntry.phi_related
    // struct LutConfig
    reg lutconfig_read_only; // LutConfig.read_only
    reg lutconfig_phi_optimized; // LutConfig.phi_optimized
    reg lutconfig_cache_enabled; // LutConfig.cache_enabled
    // struct Transform9x9
    reg [31:0] transform9x9_grid; // Transform9x9.grid
    reg [7:0] transform9x9_sparsity; // Transform9x9.sparsity
    reg [15:0] transform9x9_phi_score; // Transform9x9.phi_score
    // struct 
    reg [31:0] _op; // .op
    reg [7:0] _addr; // .addr

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: lut_entry_valid
    function lut_entry_valid; // -> bool
        input [31:0] entry;
        begin
            lut_entry_valid = (entry_valid && (entry_address < LUT_SIZE));
        end
    endfunction

    // function: lut_entry_address_valid
    function lut_entry_address_valid; // -> bool
        input [7:0] addr;
        begin
            lut_entry_address_valid = (addr < LUT_SIZE);
        end
    endfunction

    // function: create_lut_entry
    function [31:0] create_lut_entry; // -> LutEntry
        input [7:0] addr;
        input [15:0] value;
        input phi_related;
        begin
            create_lut_entry = 0 /* LutEntry {...} */;
        end
    endfunction

    // function: npu_transform_9x9
    function [31:0] npu_transform_9x9; // -> Transform9x9
        input [31:0] grid;
        begin
            reg [15:0] phi_score = 0;
            npu_transform_9x9 = 0 /* Transform9x9 {...} */;
        end
    endfunction

    // function: transform_is_sparse
    function transform_is_sparse; // -> bool
        input [31:0] transform;
        begin
            transform_is_sparse = (transform_sparsity > 50);
        end
    endfunction

    // function: transform_phi_optimized
    function transform_phi_optimized; // -> bool
        input [31:0] transform;
        begin
            transform_phi_optimized = (transform_phi_score > 100);
        end
    endfunction

    // function: lut_lookup_base
    function [31:0] lut_lookup_base; // -> LutEntry
        input [31:0] lut;
        input [7:0] addr;
        // TODO: implement
    endfunction

    // function: lut_lookup_phi
    function [31:0] lut_lookup_phi; // -> LutEntry
        input [31:0] lut;
        input [7:0] addr;
        begin
            if ((entry_valid && entry_phi_related)) begin
                lut_lookup_phi = entry;
            end
            // for-each over iterable
            for (__i = 0; __i < (0 .. LUT_SIZE); __i = __i + 1) begin
                reg [31:0] e = lut[i];
                if ((e_valid && e_phi_related)) begin
                    lut_lookup_phi = e;
                end
            end
            lut_lookup_phi = entry;
        end
    endfunction

    // function: lut_lookup_range
    function [31:0] lut_lookup_range; // -> [LUT_SIZE]LutEntry
        input [31:0] lut;
        input [7:0] start_addr;
        input [7:0] count;
        begin
            // for-each over iterable
            for (__i = 0; __i < (0 .. LUT_SIZE); __i = __i + 1) begin
                if (((i < count) && lut_entry_address_valid((start_addr + i)))) begin
                    result[i] = lut[@as(u8, @intCast((start_addr + i)))];
                end else begin
                    result[i] = 0 /* LutEntry {...} */;
                end
            end
            lut_lookup_range = undefined;
        end
    endfunction

    // function: encode_lut_npu
    function [15:0] encode_lut_npu; // -> u16
        input [31:0] op;
        input [7:0] addr;
        begin
            reg [15:0] op_field = (@as(u16, OP_LUT_NPU) << 8);
            reg [15:0] opcode_field = (@as(u16, @intFromEnum(op)) << 5);
            reg [15:0] addr_field = @as(u16, (addr && 8'h1F));
            encode_lut_npu = ((op_field || opcode_field) || addr_field);
        end
    endfunction
endmodule

`default_nettype wire
