// ============================================================================
// Generated from t27 spec: sacred_null_pe
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module sacred_null_pe (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] OP_NULL_PE = 8'hEA;
    parameter [7:0] PE_COUNT = 4;
    parameter [7:0] DATA_WIDTH = 16;
    parameter [7:0] PE_STATE_IDLE = 0;
    parameter [7:0] PE_STATE_ACTIVE = 1;
    parameter [7:0] PE_STATE_WAITING = 2;
    parameter [7:0] PE_STATE_ERROR = 3;
    parameter [7:0] NULL_MODE_SKIP = 0;
    parameter [7:0] NULL_MODE_ZERO = 1;
    parameter [7:0] NULL_MODE_IDENTITY = 2;
    parameter [7:0] NULL_MODE_CUSTOM = 3;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum PeState
    localparam PeState_idle = PE_STATE_IDLE;
    localparam PeState_active = PE_STATE_ACTIVE;
    localparam PeState_waiting = PE_STATE_WAITING;
    localparam PeState_error = PE_STATE_ERROR;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct PeConfig
    reg [7:0] peconfig_mode; // PeConfig.mode
    reg peconfig_enabled; // PeConfig.enabled
    reg peconfig_bypass_enabled; // PeConfig.bypass_enabled
    // struct PeStatus
    reg [31:0] pestatus_state; // PeStatus.state
    reg [31:0] pestatus_cycle_count; // PeStatus.cycle_count
    reg [31:0] pestatus_op_count; // PeStatus.op_count
    // struct NullPeResult
    reg nullperesult_valid; // NullPeResult.valid
    reg [15:0] nullperesult_output_data; // NullPeResult.output_data
    reg [7:0] nullperesult_pe_mask; // NullPeResult.pe_mask
    reg [7:0] nullperesult_skip_count; // NullPeResult.skip_count
    // struct PeArray
    reg [31:0] pearray_configs; // PeArray.configs
    reg [31:0] pearray_statuses; // PeArray.statuses
    // struct 
    reg [7:0] _pe_mask; // .pe_mask
    reg [7:0] _mode; // .mode

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: pe_is_active
    function pe_is_active; // -> bool
        input [31:0] status;
        begin
            pe_is_active = (status_state == PeState_active);
        end
    endfunction

    // function: pe_is_idle
    function pe_is_idle; // -> bool
        input [31:0] status;
        begin
            pe_is_idle = (status_state == PeState_idle);
        end
    endfunction

    // function: pe_is_waiting
    function pe_is_waiting; // -> bool
        input [31:0] status;
        begin
            pe_is_waiting = (status_state == PeState_waiting);
        end
    endfunction

    // function: pe_is_error
    function pe_is_error; // -> bool
        input [31:0] status;
        begin
            pe_is_error = (status_state == PeState_error);
        end
    endfunction

    // function: pe_set_state
    function [31:0] pe_set_state; // -> PeStatus
        input [31:0] status;
        input [31:0] state;
        begin
            pe_set_state = 0 /* PeStatus {...} */;
        end
    endfunction

    // function: pe_config_enabled
    function pe_config_enabled; // -> bool
        input [31:0] config;
        begin
            pe_config_enabled = (config_enabled && not);
            config_bypass_enabled;
        end
    endfunction

    // function: pe_is_null
    function pe_is_null; // -> bool
        input [31:0] config;
        begin
            pe_is_null = ((config_mode == NULL_MODE_SKIP) || (config_mode == NULL_MODE_ZERO));
        end
    endfunction

    // function: pe_is_identity
    function pe_is_identity; // -> bool
        input [31:0] config;
        begin
            pe_is_identity = (config_mode == NULL_MODE_IDENTITY);
        end
    endfunction

    // function: null_pe_skip
    function [31:0] null_pe_skip; // -> NullPeResult
        input [15:0] input;
        input [7:0] pe_mask;
        input [31:0] configs;
        // TODO: implement
    endfunction

    // function: null_pe_zero
    function [31:0] null_pe_zero; // -> NullPeResult
        input [15:0] input;
        input [7:0] pe_mask;
        input [31:0] configs;
        // TODO: implement
    endfunction

    // function: null_pe_identity
    function [31:0] null_pe_identity; // -> NullPeResult
        input [15:0] input;
        input [7:0] pe_mask;
        input [31:0] configs;
        // TODO: implement
    endfunction

    // function: null_pe_execute
    function [31:0] null_pe_execute; // -> NullPeResult
        input [15:0] input;
        input [7:0] pe_mask;
        input [31:0] configs;
        // TODO: implement
    endfunction

    // function: pe_array_init
    function [31:0] pe_array_init; // -> PeArray
        begin
            // for-each over iterable
            for (__i = 0; __i < (0 .. PE_COUNT); __i = __i + 1) begin
                configs[i] = 0 /* PeConfig {...} */;
                statuses[i] = 0 /* PeStatus {...} */;
            end
            pe_array_init = 0 /* PeArray {...} */;
        end
    endfunction

    // function: pe_array_enable
    function [31:0] pe_array_enable; // -> PeArray
        input [31:0] pe_array;
        input [7:0] pe_mask;
        begin
            // for-each over iterable
            for (__i = 0; __i < (0 .. PE_COUNT); __i = __i + 1) begin
                if (((pe_mask >> i) && (1 != 0))) begin
                    enabled = 1'b1;
                end else begin
                    enabled = 1'b0;
                end
            end
            pe_array_enable = pe_array;
        end
    endfunction

    // function: pe_array_count_active
    function [7:0] pe_array_count_active; // -> u8
        input [31:0] pe_array;
        begin
            reg [7:0] count = 0;
            // for-each over iterable
            for (onfig = 0; onfig < pe_array_configs; onfig = onfig + 1) begin
            end
            pe_array_count_active = count;
        end
    endfunction

    // function: pe_array_count_null
    function [7:0] pe_array_count_null; // -> u8
        input [31:0] pe_array;
        begin
            reg [7:0] count = 0;
            // for-each over iterable
            for (onfig = 0; onfig < pe_array_configs; onfig = onfig + 1) begin
                if (pe_is_null(config)) begin
                    count = count + 1;
                end
            end
            pe_array_count_null = count;
        end
    endfunction

    // function: pe_array_get_null_mask
    function [7:0] pe_array_get_null_mask; // -> u8
        input [31:0] pe_array;
        // TODO: implement
    endfunction

    // function: encode_null_pe
    function [15:0] encode_null_pe; // -> u16
        input [7:0] pe_mask;
        input [7:0] mode;
        begin
            reg [15:0] op = (@as(u16, OP_NULL_PE) << 8);
            reg [15:0] mode_field = (@as(u16, (mode && 8'h03)) << 6);
            reg [15:0] mask_field = (@as(u16, (pe_mask && 8'h0F)) << 2);
            encode_null_pe = ((op || mode_field) || mask_field);
        end
    endfunction
endmodule

`default_nettype wire
