// ============================================================================
// Generated from t27 spec: purkinje_thermal_gate
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module purkinje_thermal_gate (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] PTG_OPCODE = 8'hF4;
    parameter signed [7:0] TEMP_MIN_C = -40;
    parameter signed [7:0] TEMP_MAX_C = 125;
    parameter signed [7:0] TEMP_NOMINAL_C = 25;
    parameter signed [7:0] TEMP_THRESHOLD_LOW_C = 0;
    parameter signed [7:0] TEMP_THRESHOLD_HIGH_C = 85;
    parameter signed [7:0] TEMP_CRITICAL_C = 100;
    parameter signed [7:0] TEMP_HYSTERESIS_C = 5;
    parameter [15:0] TEMP_SETTLING_MS = 100;
    parameter [7:0] GATE_STATE_CLOSED = 0;
    parameter [7:0] GATE_STATE_OPEN = 1;
    parameter [7:0] GATE_STATE_THROTTLING = 2;
    parameter [7:0] GATE_STATE_ERROR = 3;
    parameter [7:0] THROTTLE_LEVEL_NONE = 0;
    parameter [7:0] THROTTLE_LEVEL_LOW = 1;
    parameter [7:0] THROTTLE_LEVEL_MED = 2;
    parameter [7:0] THROTTLE_LEVEL_HIGH = 3;
    parameter [7:0] THROTTLE_LEVEL_MAX = 4;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum GateState
    localparam GateState_closed = GATE_STATE_CLOSED;
    localparam GateState_open = GATE_STATE_OPEN;
    localparam GateState_throttling = GATE_STATE_THROTTLING;
    localparam GateState_error = GATE_STATE_ERROR;
    // enum ThrottleLevel
    localparam ThrottleLevel_none = THROTTLE_LEVEL_NONE;
    localparam ThrottleLevel_low = THROTTLE_LEVEL_LOW;
    localparam ThrottleLevel_medium = THROTTLE_LEVEL_MED;
    localparam ThrottleLevel_high = THROTTLE_LEVEL_HIGH;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct ThermalState
    reg signed [7:0] thermalstate_temp_c; // ThermalState.temp_c
    reg [31:0] thermalstate_gate_state; // ThermalState.gate_state
    reg [31:0] thermalstate_throttle_level; // ThermalState.throttle_level
    reg [7:0] thermalstate_error_code; // ThermalState.error_code
    // struct GateConfig
    reg signed [7:0] gateconfig_low_threshold_c; // GateConfig.low_threshold_c
    reg signed [7:0] gateconfig_high_threshold_c; // GateConfig.high_threshold_c
    reg signed [7:0] gateconfig_critical_temp_c; // GateConfig.critical_temp_c
    reg signed [7:0] gateconfig_hysteresis_c; // GateConfig.hysteresis_c
    reg gateconfig_auto_throttle; // GateConfig.auto_throttle
    // struct GateStatus
    reg [31:0] gatestatus_current_state; // GateStatus.current_state
    reg signed [7:0] gatestatus_temp_measured_c; // GateStatus.temp_measured_c
    reg [31:0] gatestatus_throttle_level; // GateStatus.throttle_level
    reg [31:0] gatestatus_cycle_count; // GateStatus.cycle_count
    reg [7:0] gatestatus_fault_count; // GateStatus.fault_count
    // struct 
    reg [7:0] _opcode; // .opcode
    reg signed [7:0] _temp_c; // .temp_c
    reg [7:0] _threshold; // .threshold

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: ptg_config_init
    function [31:0] ptg_config_init; // -> GateConfig
        begin
            ptg_config_init = 0 /* GateConfig {...} */;
        end
    endfunction

    // function: ptg_config_strict
    function [31:0] ptg_config_strict; // -> GateConfig
        begin
            ptg_config_strict = 0 /* GateConfig {...} */;
        end
    endfunction

    // function: ptg_config_permissive
    function [31:0] ptg_config_permissive; // -> GateConfig
        begin
            ptg_config_permissive = 0 /* GateConfig {...} */;
        end
    endfunction

    // function: ptg_config_manual
    function [31:0] ptg_config_manual; // -> GateConfig
        begin
            ptg_config_manual = 0 /* GateConfig {...} */;
        end
    endfunction

    // function: ptg_temp_valid
    function ptg_temp_valid; // -> bool
        input signed [7:0] temp_c;
        begin
            ptg_temp_valid = ((temp_c >= TEMP_MIN_C) && (temp_c <= TEMP_MAX_C));
        end
    endfunction

    // function: ptg_temp_critical
    function ptg_temp_critical; // -> bool
        input signed [7:0] temp_c;
        input [31:0] config;
        begin
            ptg_temp_critical = (temp_c >= config_critical_temp_c);
        end
    endfunction

    // function: ptg_temp_high
    function ptg_temp_high; // -> bool
        input signed [7:0] temp_c;
        input [31:0] config;
        begin
            ptg_temp_high = (temp_c >= config_high_threshold_c);
        end
    endfunction

    // function: ptg_temp_low
    function ptg_temp_low; // -> bool
        input signed [7:0] temp_c;
        input [31:0] config;
        begin
            ptg_temp_low = (temp_c < config_low_threshold_c);
        end
    endfunction

    // function: ptg_temp_in_hysteresis
    function ptg_temp_in_hysteresis; // -> bool
        input signed [7:0] temp_c;
        input signed [7:0] threshold;
        input signed [7:0] hysteresis;
        begin
            if ((temp_c >= threshold)) begin
                ptg_temp_in_hysteresis = ((temp_c - threshold) <= hysteresis);
            end else begin
                ptg_temp_in_hysteresis = ((threshold - temp_c) <= hysteresis);
            end
        end
    endfunction

    // function: ptg_thermal_state_init
    function [31:0] ptg_thermal_state_init; // -> ThermalState
        begin
            ptg_thermal_state_init = 0 /* ThermalState {...} */;
        end
    endfunction

    // function: ptg_gate_state_from_temp
    function [31:0] ptg_gate_state_from_temp; // -> GateState
        input signed [7:0] temp_c;
        input [31:0] config;
        // TODO: implement
    endfunction

    // function: ptg_throttle_from_temp
    function [31:0] ptg_throttle_from_temp; // -> ThrottleLevel
        input signed [7:0] temp_c;
        input [31:0] config;
        begin
            if (ptg_temp_critical(temp_c, config)) begin
                ptg_throttle_from_temp = ThrottleLevel_high;
            end else if ((temp_c >= (config_high_threshold_c + 20))) begin
                ptg_throttle_from_temp = ThrottleLevel_high;
            end else if ((temp_c >= (config_high_threshold_c + 10))) begin
                ptg_throttle_from_temp = ThrottleLevel_medium;
            end else if ((temp_c >= config_high_threshold_c)) begin
                ptg_throttle_from_temp = ThrottleLevel_low;
            end else begin
                ptg_throttle_from_temp = ThrottleLevel_none;
            end
        end
    endfunction

    // function: ptg_thermal_state_update
    function [31:0] ptg_thermal_state_update; // -> ThermalState
        input [31:0] thermal;
        input signed [7:0] temp_c;
        input [31:0] config;
        begin
            if (config_auto_throttle) begin
                new_state_throttle_level = ptg_throttle_from_temp(temp_c, config);
            end
            if ((thermal_gate_state == GateState_error)) begin
                new_state_error_code = 1;
            end else if ((thermal_gate_state != GateState_error)) begin
                new_state_error_code = 0;
            end
            ptg_thermal_state_update = thermal;
        end
    endfunction

    // function: ptg_gate_status_init
    function [31:0] ptg_gate_status_init; // -> GateStatus
        begin
            ptg_gate_status_init = 0 /* GateStatus {...} */;
        end
    endfunction

    // function: ptg_gate_status_open
    function [31:0] ptg_gate_status_open; // -> GateStatus
        input [31:0] status;
        begin
            ptg_gate_status_open = 0 /* GateStatus {...} */;
        end
    endfunction

    // function: ptg_gate_status_close
    function [31:0] ptg_gate_status_close; // -> GateStatus
        input [31:0] status;
        begin
            ptg_gate_status_close = 0 /* GateStatus {...} */;
        end
    endfunction

    // function: ptg_gate_status_throttle
    function [31:0] ptg_gate_status_throttle; // -> GateStatus
        input [31:0] status;
        input [31:0] level;
        begin
            ptg_gate_status_throttle = 0 /* GateStatus {...} */;
        end
    endfunction

    // function: ptg_gate_status_error
    function [31:0] ptg_gate_status_error; // -> GateStatus
        input [31:0] status;
        begin
            ptg_gate_status_error = 0 /* GateStatus {...} */;
        end
    endfunction

    // function: ptg_gate_status_update_temp
    function [31:0] ptg_gate_status_update_temp; // -> GateStatus
        input [31:0] status;
        input signed [7:0] temp_c;
        begin
            ptg_gate_status_update_temp = 0 /* GateStatus {...} */;
        end
    endfunction

    // function: ptg_gate_status_increment_cycle
    function [31:0] ptg_gate_status_increment_cycle; // -> GateStatus
        input [31:0] status;
        begin
            ptg_gate_status_increment_cycle = 0 /* GateStatus {...} */;
        end
    endfunction

    // function: encode_ptg_cmd
    function [15:0] encode_ptg_cmd; // -> u16
        input [7:0] opcode;
        input signed [7:0] temp_c;
        input [7:0] threshold;
        begin
            reg [15:0] op_field = (@as(u16, opcode) << 8);
            reg [15:0] temp_field = (@as(u16, @as(u8, @bitCast(temp_c))) << 1);
            reg [15:0] thresh_field = @as(u16, (threshold && 8'h01));
            encode_ptg_cmd = ((op_field || temp_field) || thresh_field);
        end
    endfunction
endmodule

`default_nettype wire
