// ============================================================================
// Generated from t27 spec: sacred_spec_exit
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module sacred_spec_exit (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] OP_SPEC_EXIT = 8'hEB;
    parameter [7:0] MAX_NESTING_DEPTH = 8;
    parameter [7:0] EXIT_REASON_BITS = 3;
    parameter [7:0] EXIT_SUCCESS = 0;
    parameter [7:0] EXIT_SPEC_FAIL = 1;
    parameter [7:0] EXIT_TIMEOUT = 2;
    parameter [7:0] EXIT_EXCEPTION = 3;
    parameter [7:0] EXIT_RESOURCE = 4;
    parameter [7:0] EXIT_ABORT = 5;
    parameter [7:0] EXIT_RECOVER = 6;
    parameter [7:0] EXIT_MAX = 7;
    parameter [7:0] STATE_RUNNING = 0;
    parameter [7:0] STATE_SPECULATING = 1;
    parameter [7:0] STATE_EXITING = 2;
    parameter [7:0] STATE_EXITED = 3;
    parameter [7:0] STATE_RECOVERING = 4;
    parameter [7:0] STATE_ERROR = 5;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum ExitReason
    localparam ExitReason_success = EXIT_SUCCESS;
    localparam ExitReason_spec_fail = EXIT_SPEC_FAIL;
    localparam ExitReason_timeout = EXIT_TIMEOUT;
    localparam ExitReason_exception = EXIT_EXCEPTION;
    localparam ExitReason_resource = EXIT_RESOURCE;
    localparam ExitReason_abort = EXIT_ABORT;
    localparam ExitReason_recover = EXIT_RECOVER;
    // enum SpecState
    localparam SpecState_running = STATE_RUNNING;
    localparam SpecState_speculating = STATE_SPECULATING;
    localparam SpecState_exiting = STATE_EXITING;
    localparam SpecState_exited = STATE_EXITED;
    localparam SpecState_recovering = STATE_RECOVERING;
    localparam SpecState_error = STATE_ERROR;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct SpecExit
    reg [31:0] specexit_reason; // SpecExit.reason
    reg [7:0] specexit_depth; // SpecExit.depth
    reg [15:0] specexit_checkpoint_addr; // SpecExit.checkpoint_addr
    reg specexit_recovery_possible; // SpecExit.recovery_possible
    // struct SpecContext
    reg [31:0] speccontext_state; // SpecContext.state
    reg [7:0] speccontext_current_depth; // SpecContext.current_depth
    reg [31:0] speccontext_spec_count; // SpecContext.spec_count
    reg [31:0] speccontext_exit_count; // SpecContext.exit_count
    // struct SpecConfig
    reg [7:0] specconfig_max_depth; // SpecConfig.max_depth
    reg [31:0] specconfig_timeout_cycles; // SpecConfig.timeout_cycles
    reg specconfig_enable_recovery; // SpecConfig.enable_recovery
    reg [7:0] specconfig_checkpoint_interval; // SpecConfig.checkpoint_interval
    // struct 
    reg [7:0] _reason; // .reason
    reg [7:0] _depth; // .depth
    reg [15:0] _checkpoint; // .checkpoint

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: spec_state_is_running
    function spec_state_is_running; // -> bool
        input [31:0] state;
        begin
            spec_state_is_running = (state == SpecState_running);
        end
    endfunction

    // function: spec_state_is_speculating
    function spec_state_is_speculating; // -> bool
        input [31:0] state;
        begin
            spec_state_is_speculating = (state == SpecState_speculating);
        end
    endfunction

    // function: spec_state_is_exiting
    function spec_state_is_exiting; // -> bool
        input [31:0] state;
        begin
            spec_state_is_exiting = (state == SpecState_exiting);
        end
    endfunction

    // function: spec_state_is_exited
    function spec_state_is_exited; // -> bool
        input [31:0] state;
        begin
            spec_state_is_exited = (state == SpecState_exited);
        end
    endfunction

    // function: spec_state_is_recovering
    function spec_state_is_recovering; // -> bool
        input [31:0] state;
        begin
            spec_state_is_recovering = (state == SpecState_recovering);
        end
    endfunction

    // function: spec_state_is_terminal
    function spec_state_is_terminal; // -> bool
        input [31:0] state;
        begin
            spec_state_is_terminal = ((state == SpecState_exited) || (state == SpecState_error));
        end
    endfunction

    // function: spec_state_can_speculate
    function spec_state_can_speculate; // -> bool
        input [31:0] state;
        begin
            spec_state_can_speculate = ((state == SpecState_running) || (state == SpecState_recovering));
        end
    endfunction

    // function: spec_exit_success
    function [31:0] spec_exit_success; // -> SpecExit
        input [7:0] depth;
        input [15:0] checkpoint;
        begin
            spec_exit_success = 0 /* SpecExit {...} */;
        end
    endfunction

    // function: spec_exit_fail
    function [31:0] spec_exit_fail; // -> SpecExit
        input [31:0] reason;
        input [7:0] depth;
        input [15:0] checkpoint;
        input can_recover;
        begin
            spec_exit_fail = 0 /* SpecExit {...} */;
        end
    endfunction

    // function: spec_exit_timeout
    function [31:0] spec_exit_timeout; // -> SpecExit
        input [7:0] depth;
        input [15:0] checkpoint;
        begin
            spec_exit_timeout = spec_exit_fail(ExitReason_timeout, depth, checkpoint, 1'b1);
        end
    endfunction

    // function: spec_exit_exception
    function [31:0] spec_exit_exception; // -> SpecExit
        input [7:0] depth;
        input [15:0] checkpoint;
        begin
            spec_exit_exception = spec_exit_fail(ExitReason_exception, depth, checkpoint, 1'b0);
        end
    endfunction

    // function: spec_exit_resource
    function [31:0] spec_exit_resource; // -> SpecExit
        input [7:0] depth;
        input [15:0] checkpoint;
        begin
            spec_exit_resource = spec_exit_fail(ExitReason_resource, depth, checkpoint, 1'b1);
        end
    endfunction

    // function: spec_exit_abort
    function [31:0] spec_exit_abort; // -> SpecExit
        input [7:0] depth;
        begin
            spec_exit_abort = 0 /* SpecExit {...} */;
        end
    endfunction

    // function: spec_exit_recover
    function [31:0] spec_exit_recover; // -> SpecExit
        input [7:0] depth;
        input [15:0] checkpoint;
        begin
            spec_exit_recover = 0 /* SpecExit {...} */;
        end
    endfunction

    // function: spec_context_init
    function [31:0] spec_context_init; // -> SpecContext
        begin
            spec_context_init = 0 /* SpecContext {...} */;
        end
    endfunction

    // function: spec_context_enter_speculation
    function [31:0] spec_context_enter_speculation; // -> SpecContext
        input [31:0] context;
        input [7:0] depth_limit;
        // TODO: implement
    endfunction

    // function: spec_context_exit
    function [31:0] spec_context_exit; // -> SpecContext
        input [31:0] context;
        input [31:0] exit;
        begin
            reg [31:0] new_state = context_state;
            if (((exit_reason == ExitReason_success) || (exit_reason == ExitReason_recover))) begin
                new_state = SpecState_exiting;
            end else if (exit_recovery_possible) begin
                new_state = SpecState_recovering;
            end else begin
                new_state = SpecState_error;
            end
            spec_context_exit = 0 /* SpecContext {...} */;
        end
    endfunction

    // function: spec_context_complete
    function [31:0] spec_context_complete; // -> SpecContext
        input [31:0] context;
        begin
            spec_context_complete = 0 /* SpecContext {...} */;
        end
    endfunction

    // function: spec_context_check_timeout
    function spec_context_check_timeout; // -> bool
        input [31:0] context;
        input [31:0] config;
        input [31:0] current_cycle;
        begin
            if ((config_timeout_cycles == 0)) begin
                spec_context_check_timeout = 1'b0;
            end
            spec_context_check_timeout = ((context_spec_count * 100) >= config_timeout_cycles);
        end
    endfunction

    // function: encode_spec_exit
    function [31:0] encode_spec_exit; // -> u32
        input [7:0] reason;
        input [7:0] depth;
        input [15:0] checkpoint;
        begin
            reg [31:0] op = (@as(u32, OP_SPEC_EXIT) << 24);
            reg [31:0] reason_field = (@as(u32, (reason && 8'h07)) << 21);
            reg [31:0] depth_field = (@as(u32, (depth && 8'h1F)) << 16);
            reg [31:0] checkpoint_field = @as(u32, (checkpoint && 16'hFFFF));
            encode_spec_exit = (((op || reason_field) || depth_field) || checkpoint_field);
        end
    endfunction
endmodule

`default_nettype wire
