// ============================================================================
// Generated from t27 spec: sacred_subth_clk
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module sacred_subth_clk (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    output wire        ready
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    parameter [7:0] OP_SUBTH_CLK = 8'hE5;
    parameter [7:0] NUM_CLK_DOMAINS = 8;
    parameter [15:0] SUBTH_THRESHOLD_MV = 400;
    parameter [15:0] NORMAL_VOLTAGE_MV = 1100;
    parameter [7:0] CLK_GATE_OFF = 0;
    parameter [7:0] CLK_GATE_ON = 1;
    parameter [7:0] CLK_GATE_AUTO = 2;
    parameter [7:0] POWER_STATE_ACTIVE = 0;
    parameter [7:0] POWER_STATE_IDLE = 1;
    parameter [7:0] POWER_STATE_SLEEP = 2;
    parameter [7:0] POWER_STATE_DEEP_SLEEP = 3;

    // -------------------------------------------------------
    // Enum constants
    // -------------------------------------------------------
    // enum ClkGateMode
    localparam ClkGateMode_off = CLK_GATE_OFF;
    localparam ClkGateMode_on = CLK_GATE_ON;
    localparam ClkGateMode_auto = CLK_GATE_AUTO;
    // enum PowerState
    localparam PowerState_active = POWER_STATE_ACTIVE;
    localparam PowerState_idle = POWER_STATE_IDLE;
    localparam PowerState_sleep = POWER_STATE_SLEEP;
    localparam PowerState_deep_sleep = POWER_STATE_DEEP_SLEEP;

    // -------------------------------------------------------
    // Registers (from struct declarations)
    // -------------------------------------------------------
    // struct ClkDomain
    reg [7:0] clkdomain_id; // ClkDomain.id
    reg clkdomain_enabled; // ClkDomain.enabled
    reg [31:0] clkdomain_gate_mode; // ClkDomain.gate_mode
    reg [15:0] clkdomain_activity_count; // ClkDomain.activity_count
    reg [31:0] clkdomain_last_active_cycle; // ClkDomain.last_active_cycle
    // struct SubthConfig
    reg [15:0] subthconfig_threshold_mv; // SubthConfig.threshold_mv
    reg [15:0] subthconfig_hysteresis_mv; // SubthConfig.hysteresis_mv
    reg subthconfig_enable_subth; // SubthConfig.enable_subth
    reg [7:0] subthconfig_transition_cycles; // SubthConfig.transition_cycles
    // struct PowerMetrics
    reg [15:0] powermetrics_current_voltage_mv; // PowerMetrics.current_voltage_mv
    reg [15:0] powermetrics_current_power_mw; // PowerMetrics.current_power_mw
    reg [7:0] powermetrics_activity_ratio; // PowerMetrics.activity_ratio
    reg [7:0] powermetrics_clock_gated_domains; // PowerMetrics.clock_gated_domains
    // struct 
    reg [7:0] _domain_id; // .domain_id
    reg [7:0] _mode; // .mode

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: clk_domain_enabled
    function clk_domain_enabled; // -> bool
        input [31:0] domain;
        begin
            clk_domain_enabled = (domain_enabled && (domain_gate_mode != ClkGateMode_off));
        end
    endfunction

    // function: clk_domain_gate_active
    function clk_domain_gate_active; // -> bool
        input [31:0] domain;
        begin
            clk_domain_gate_active = ((domain_gate_mode == ClkGateMode_off) || ((domain_gate_mode == ClkGateMode_auto) && (domain_activity_count == 0)));
        end
    endfunction

    // function: clk_domain_is_idle
    function clk_domain_is_idle; // -> bool
        input [31:0] domain;
        input [31:0] current_cycle;
        input [31:0] idle_threshold;
        begin
            clk_domain_is_idle = ((domain_activity_count == 0) && ((current_cycle - domain_last_active_cycle) > idle_threshold));
        end
    endfunction

    // function: clk_domain_pulse
    function [31:0] clk_domain_pulse; // -> ClkDomain
        input [31:0] domain;
        input [31:0] current_cycle;
        begin
            clk_domain_pulse = 0 /* ClkDomain {...} */;
        end
    endfunction

    // function: clk_domain_decay
    function [31:0] clk_domain_decay; // -> ClkDomain
        input [31:0] domain;
        begin
            reg [31:0] new_count = ((domain_activity_count > 0)) ? ((domain_activity_count - 1)) : (0);
            clk_domain_decay = 0 /* ClkDomain {...} */;
        end
    endfunction

    // function: is_subthreshold
    function is_subthreshold; // -> bool
        input [15:0] voltage_mv;
        input [31:0] config;
        // TODO: implement
    endfunction

    // function: voltage_within_range
    function voltage_within_range; // -> bool
        input [15:0] voltage_mv;
        input [15:0] target_mv;
        input [15:0] tolerance_mv;
        begin
            if ((voltage_mv >= target_mv)) begin
                voltage_within_range = ((voltage_mv - target_mv) <= tolerance_mv);
            end
            voltage_within_range = ((target_mv - voltage_mv) <= tolerance_mv);
        end
    endfunction

    // function: subth_power_estimate
    function [15:0] subth_power_estimate; // -> u16
        input [15:0] voltage_mv;
        begin
            reg [31:0] ratio = (@as(f32, @floatFromInt(voltage_mv)) / 1100.0);
            reg [31:0] power_baseline = 100.0;
            reg [31:0] estimated = ((power_baseline * ratio) * ratio);
            subth_power_estimate = @as(u16, @intFromFloat(@floor(estimated)));
        end
    endfunction

    // function: power_savings_ratio
    function [7:0] power_savings_ratio; // -> u8
        input [15:0] normal_mv;
        input [15:0] subth_mv;
        begin
            reg [31:0] normal_power = subth_power_estimate(normal_mv);
            reg [31:0] subth_power = subth_power_estimate(subth_mv);
            if ((normal_power == 0)) begin
                power_savings_ratio = 0;
            end
            reg [31:0] saved = (normal_power - subth_power);
            reg [31:0] ratio = ((saved * 100) / normal_power);
            power_savings_ratio = @as(u8, @truncate(ratio));
        end
    endfunction

    // function: power_state_can_gate
    function power_state_can_gate; // -> bool
        input [31:0] state;
        begin
            power_state_can_gate = (state != PowerState_active);
        end
    endfunction

    // function: power_state_deeper
    function [31:0] power_state_deeper; // -> PowerState
        input [31:0] a;
        input [31:0] b;
        begin
            if ((@intFromEnum(a) > @intFromEnum(b))) begin
                power_state_deeper = a;
            end
            power_state_deeper = b;
        end
    endfunction

    // function: power_state_sleep_ok
    function power_state_sleep_ok; // -> bool
        input [31:0] domains;
        input [31:0] current_cycle;
        begin
            // for-each over iterable
            for (omain = 0; omain < domains; omain = omain + 1) begin
            end
            power_state_sleep_ok = 1'b1;
        end
    endfunction

    // function: encode_subth_clk
    function [15:0] encode_subth_clk; // -> u16
        input [7:0] domain_id;
        input [7:0] mode;
        begin
            reg [15:0] op = (@as(u16, OP_SUBTH_CLK) << 8);
            reg [15:0] domain_field = (@as(u16, (domain_id && 8'h07)) << 5);
            reg [15:0] mode_field = (@as(u16, (mode && 8'h03)) << 3);
            encode_subth_clk = ((op || domain_field) || mode_field);
        end
    endfunction
endmodule

`default_nettype wire
