// SPDX-License-Identifier: Apache-2.0
// t27/rtl_gen/gf128_add.v
// GoldenFloat128 Addition Unit -- [S(1) | E(48) | M(79)], bias 2^(E-1)-1.
// value = (-1)^S (1 + M/2^79) 2^(E-bias).
//
// Generated by test/gen_gf_add_fix.py (generalizes the exhaustively-verified
// gf8_add). Proper float add: significands carry 3 guard bits, alignment captures
// a sticky bit, the post-add leading 1 is found by priority and renormalized, and
// the 79-bit mantissa is rounded to nearest, ties-to-even. The running exponent is
// SIGNED and wide enough to tell underflow (exp<0) from a valid large exponent --
// the previous unit flushed valid exponents >= 2^(E-1) to zero. Verified by
// test/gf_arith_xcheck.py and test/gf_add_sweep.py.

`default_nettype none
module gf128_add (
    input  wire [127:0] a,
    input  wire [127:0] b,
    output reg  [127:0] result
);

    localparam [47:0] EXP_MAX = 48'd281474976710655;
    localparam signed [49:0] EXP_MAX_S = 50'sd281474976710655;

    wire             sign_a = a[127];
    wire [47:0]   exp_a  = a[126:79];
    wire [78:0]   mant_a = a[78:0];
    wire             sign_b = b[127];
    wire [47:0]   exp_b  = b[126:79];
    wire [78:0]   mant_b = b[78:0];

    wire is_zero_a = (exp_a == 48'd0) && (mant_a == 79'd0);
    wire is_zero_b = (exp_b == 48'd0) && (mant_b == 79'd0);
    wire is_inf_a  = (exp_a == EXP_MAX) && (mant_a == 79'd0);
    wire is_inf_b  = (exp_b == EXP_MAX) && (mant_b == 79'd0);
    wire is_nan_a  = (exp_a == EXP_MAX) && (mant_a != 79'd0);
    wire is_nan_b  = (exp_b == EXP_MAX) && (mant_b != 79'd0);

    wire a_larger = (exp_a > exp_b) || ((exp_a == exp_b) && (mant_a >= mant_b));

    reg        big_sign, small_sign, result_sign;
    reg [47:0] big_exp, small_exp;
    reg [78:0] big_m, small_m;
    reg [82:0] big_ext, small_ext, shifted;   // {1, mant, 3 guard bits}
    reg [48:0]  shamt;
    reg            sticky_shift;
    reg [83:0] sum_m;                          // room for add carry
    reg signed [49:0] rexp;
    reg [78:0]  mant_out;
    reg [79:0]   mant_rounded;                    // M+1 bits, catches overflow
    reg            guard, round_b, sticky, round_up;

    always @(*) begin
        big_sign = 0; small_sign = 0; result_sign = 0;
        big_exp = 0; small_exp = 0; big_m = 0; small_m = 0;
        big_ext = 0; small_ext = 0; shifted = 0; shamt = 0; sticky_shift = 0;
        sum_m = 0; rexp = 0; mant_out = 0; mant_rounded = 0;
        guard = 0; round_b = 0; sticky = 0; round_up = 0;

        if (is_nan_a || is_nan_b)
            result = 128'hFFFFFFFFFFFF80000000000000000001;
        else if (is_inf_a && is_inf_b && (sign_a != sign_b))
            result = 128'hFFFFFFFFFFFF80000000000000000001;
        else if (is_inf_a)
            result = sign_a ? 128'hFFFFFFFFFFFF80000000000000000000 : 128'h7FFFFFFFFFFF80000000000000000000;
        else if (is_inf_b)
            result = sign_b ? 128'hFFFFFFFFFFFF80000000000000000000 : 128'h7FFFFFFFFFFF80000000000000000000;
        else if (is_zero_a && is_zero_b)
            result = 128'h0;
        else if (is_zero_a)
            result = b;
        else if (is_zero_b)
            result = a;
        else begin
            if (a_larger) begin
                big_sign = sign_a; big_exp = exp_a; big_m = mant_a;
                small_sign = sign_b; small_exp = exp_b; small_m = mant_b;
            end else begin
                big_sign = sign_b; big_exp = exp_b; big_m = mant_b;
                small_sign = sign_a; small_exp = exp_a; small_m = mant_a;
            end

            big_ext   = {1'b1, big_m,   3'b0};
            small_ext = {1'b1, small_m, 3'b0};
            shamt     = big_exp - small_exp;

            if (shamt >= 83)
                begin shifted = 0; sticky_shift = |small_ext; end
            else begin
                shifted = small_ext >> shamt;
                sticky_shift = |(small_ext & ((83'd1 << shamt) - 83'd1));
            end

            result_sign = big_sign;
            rexp = $signed({2'b0, big_exp});

            if (big_sign == small_sign)
                sum_m = {1'b0, big_ext} + {1'b0, shifted};
            else
                sum_m = {1'b0, big_ext} - {1'b0, shifted};

            if (sum_m == 0) begin
                result = 128'h0;
            end else begin
                if (sum_m[83]) begin
                    rexp = rexp + 50'sd1;
                    mant_out = sum_m[82:4];
                    guard = sum_m[3]; round_b = sum_m[2]; sticky = (|sum_m[1:0]) | sticky_shift;
                end
                else if (sum_m[82]) begin
                    mant_out = sum_m[81:3];
                    guard = sum_m[2]; round_b = sum_m[1]; sticky = (|sum_m[0:0]) | sticky_shift;
                end
                else if (sum_m[81]) begin
                    rexp = rexp - 50'sd1;
                    mant_out = sum_m[80:2];
                    guard = sum_m[1]; round_b = sum_m[0]; sticky = sticky_shift;
                end
                else if (sum_m[80]) begin
                    rexp = rexp - 50'sd2;
                    mant_out = sum_m[79:1];
                    guard = sum_m[0]; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[79]) begin
                    rexp = rexp - 50'sd3;
                    mant_out = sum_m[78:0];
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[78]) begin
                    rexp = rexp - 50'sd4;
                    mant_out = {sum_m[77:0], 1'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[77]) begin
                    rexp = rexp - 50'sd5;
                    mant_out = {sum_m[76:0], 2'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[76]) begin
                    rexp = rexp - 50'sd6;
                    mant_out = {sum_m[75:0], 3'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[75]) begin
                    rexp = rexp - 50'sd7;
                    mant_out = {sum_m[74:0], 4'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[74]) begin
                    rexp = rexp - 50'sd8;
                    mant_out = {sum_m[73:0], 5'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[73]) begin
                    rexp = rexp - 50'sd9;
                    mant_out = {sum_m[72:0], 6'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[72]) begin
                    rexp = rexp - 50'sd10;
                    mant_out = {sum_m[71:0], 7'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[71]) begin
                    rexp = rexp - 50'sd11;
                    mant_out = {sum_m[70:0], 8'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[70]) begin
                    rexp = rexp - 50'sd12;
                    mant_out = {sum_m[69:0], 9'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[69]) begin
                    rexp = rexp - 50'sd13;
                    mant_out = {sum_m[68:0], 10'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[68]) begin
                    rexp = rexp - 50'sd14;
                    mant_out = {sum_m[67:0], 11'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[67]) begin
                    rexp = rexp - 50'sd15;
                    mant_out = {sum_m[66:0], 12'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[66]) begin
                    rexp = rexp - 50'sd16;
                    mant_out = {sum_m[65:0], 13'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[65]) begin
                    rexp = rexp - 50'sd17;
                    mant_out = {sum_m[64:0], 14'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[64]) begin
                    rexp = rexp - 50'sd18;
                    mant_out = {sum_m[63:0], 15'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[63]) begin
                    rexp = rexp - 50'sd19;
                    mant_out = {sum_m[62:0], 16'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[62]) begin
                    rexp = rexp - 50'sd20;
                    mant_out = {sum_m[61:0], 17'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[61]) begin
                    rexp = rexp - 50'sd21;
                    mant_out = {sum_m[60:0], 18'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[60]) begin
                    rexp = rexp - 50'sd22;
                    mant_out = {sum_m[59:0], 19'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[59]) begin
                    rexp = rexp - 50'sd23;
                    mant_out = {sum_m[58:0], 20'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[58]) begin
                    rexp = rexp - 50'sd24;
                    mant_out = {sum_m[57:0], 21'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[57]) begin
                    rexp = rexp - 50'sd25;
                    mant_out = {sum_m[56:0], 22'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[56]) begin
                    rexp = rexp - 50'sd26;
                    mant_out = {sum_m[55:0], 23'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[55]) begin
                    rexp = rexp - 50'sd27;
                    mant_out = {sum_m[54:0], 24'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[54]) begin
                    rexp = rexp - 50'sd28;
                    mant_out = {sum_m[53:0], 25'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[53]) begin
                    rexp = rexp - 50'sd29;
                    mant_out = {sum_m[52:0], 26'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[52]) begin
                    rexp = rexp - 50'sd30;
                    mant_out = {sum_m[51:0], 27'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[51]) begin
                    rexp = rexp - 50'sd31;
                    mant_out = {sum_m[50:0], 28'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[50]) begin
                    rexp = rexp - 50'sd32;
                    mant_out = {sum_m[49:0], 29'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[49]) begin
                    rexp = rexp - 50'sd33;
                    mant_out = {sum_m[48:0], 30'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[48]) begin
                    rexp = rexp - 50'sd34;
                    mant_out = {sum_m[47:0], 31'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[47]) begin
                    rexp = rexp - 50'sd35;
                    mant_out = {sum_m[46:0], 32'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[46]) begin
                    rexp = rexp - 50'sd36;
                    mant_out = {sum_m[45:0], 33'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[45]) begin
                    rexp = rexp - 50'sd37;
                    mant_out = {sum_m[44:0], 34'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[44]) begin
                    rexp = rexp - 50'sd38;
                    mant_out = {sum_m[43:0], 35'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[43]) begin
                    rexp = rexp - 50'sd39;
                    mant_out = {sum_m[42:0], 36'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[42]) begin
                    rexp = rexp - 50'sd40;
                    mant_out = {sum_m[41:0], 37'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[41]) begin
                    rexp = rexp - 50'sd41;
                    mant_out = {sum_m[40:0], 38'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[40]) begin
                    rexp = rexp - 50'sd42;
                    mant_out = {sum_m[39:0], 39'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[39]) begin
                    rexp = rexp - 50'sd43;
                    mant_out = {sum_m[38:0], 40'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[38]) begin
                    rexp = rexp - 50'sd44;
                    mant_out = {sum_m[37:0], 41'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[37]) begin
                    rexp = rexp - 50'sd45;
                    mant_out = {sum_m[36:0], 42'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[36]) begin
                    rexp = rexp - 50'sd46;
                    mant_out = {sum_m[35:0], 43'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[35]) begin
                    rexp = rexp - 50'sd47;
                    mant_out = {sum_m[34:0], 44'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[34]) begin
                    rexp = rexp - 50'sd48;
                    mant_out = {sum_m[33:0], 45'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[33]) begin
                    rexp = rexp - 50'sd49;
                    mant_out = {sum_m[32:0], 46'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[32]) begin
                    rexp = rexp - 50'sd50;
                    mant_out = {sum_m[31:0], 47'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[31]) begin
                    rexp = rexp - 50'sd51;
                    mant_out = {sum_m[30:0], 48'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[30]) begin
                    rexp = rexp - 50'sd52;
                    mant_out = {sum_m[29:0], 49'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[29]) begin
                    rexp = rexp - 50'sd53;
                    mant_out = {sum_m[28:0], 50'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[28]) begin
                    rexp = rexp - 50'sd54;
                    mant_out = {sum_m[27:0], 51'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[27]) begin
                    rexp = rexp - 50'sd55;
                    mant_out = {sum_m[26:0], 52'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[26]) begin
                    rexp = rexp - 50'sd56;
                    mant_out = {sum_m[25:0], 53'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[25]) begin
                    rexp = rexp - 50'sd57;
                    mant_out = {sum_m[24:0], 54'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[24]) begin
                    rexp = rexp - 50'sd58;
                    mant_out = {sum_m[23:0], 55'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[23]) begin
                    rexp = rexp - 50'sd59;
                    mant_out = {sum_m[22:0], 56'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[22]) begin
                    rexp = rexp - 50'sd60;
                    mant_out = {sum_m[21:0], 57'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[21]) begin
                    rexp = rexp - 50'sd61;
                    mant_out = {sum_m[20:0], 58'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[20]) begin
                    rexp = rexp - 50'sd62;
                    mant_out = {sum_m[19:0], 59'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[19]) begin
                    rexp = rexp - 50'sd63;
                    mant_out = {sum_m[18:0], 60'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[18]) begin
                    rexp = rexp - 50'sd64;
                    mant_out = {sum_m[17:0], 61'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[17]) begin
                    rexp = rexp - 50'sd65;
                    mant_out = {sum_m[16:0], 62'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[16]) begin
                    rexp = rexp - 50'sd66;
                    mant_out = {sum_m[15:0], 63'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[15]) begin
                    rexp = rexp - 50'sd67;
                    mant_out = {sum_m[14:0], 64'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[14]) begin
                    rexp = rexp - 50'sd68;
                    mant_out = {sum_m[13:0], 65'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[13]) begin
                    rexp = rexp - 50'sd69;
                    mant_out = {sum_m[12:0], 66'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[12]) begin
                    rexp = rexp - 50'sd70;
                    mant_out = {sum_m[11:0], 67'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[11]) begin
                    rexp = rexp - 50'sd71;
                    mant_out = {sum_m[10:0], 68'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[10]) begin
                    rexp = rexp - 50'sd72;
                    mant_out = {sum_m[9:0], 69'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[9]) begin
                    rexp = rexp - 50'sd73;
                    mant_out = {sum_m[8:0], 70'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[8]) begin
                    rexp = rexp - 50'sd74;
                    mant_out = {sum_m[7:0], 71'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[7]) begin
                    rexp = rexp - 50'sd75;
                    mant_out = {sum_m[6:0], 72'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[6]) begin
                    rexp = rexp - 50'sd76;
                    mant_out = {sum_m[5:0], 73'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[5]) begin
                    rexp = rexp - 50'sd77;
                    mant_out = {sum_m[4:0], 74'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[4]) begin
                    rexp = rexp - 50'sd78;
                    mant_out = {sum_m[3:0], 75'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[3]) begin
                    rexp = rexp - 50'sd79;
                    mant_out = {sum_m[2:0], 76'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[2]) begin
                    rexp = rexp - 50'sd80;
                    mant_out = {sum_m[1:0], 77'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[1]) begin
                    rexp = rexp - 50'sd81;
                    mant_out = {sum_m[0:0], 78'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else begin
                    mant_out = 79'd0;
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end

                round_up     = guard && (round_b || sticky || mant_out[0]);
                mant_rounded = {1'b0, mant_out} + (round_up ? 80'd1 : 80'd0);
                if (mant_rounded[79]) begin
                    rexp     = rexp + 50'sd1;
                    mant_out = 79'd0;
                end else begin
                    mant_out = mant_rounded[78:0];
                end

                if (rexp < 0)
                    result = result_sign ? 128'h80000000000000000000000000000000 : 128'h0;
                else if (rexp >= EXP_MAX_S)
                    result = result_sign ? 128'hFFFFFFFFFFFF80000000000000000000 : 128'h7FFFFFFFFFFF80000000000000000000;
                else if (rexp == 0 && mant_out == 79'd0)
                    result = result_sign ? 128'h80000000000000000000000000000000 : 128'h0;
                else
                    result = {result_sign, rexp[47:0], mant_out};
            end
        end
    end

endmodule
