// SPDX-License-Identifier: Apache-2.0
// t27/rtl_gen/gf256_add.v
// GoldenFloat256 Addition Unit -- [S(1) | E(97) | M(158)], bias 2^(E-1)-1.
// value = (-1)^S (1 + M/2^158) 2^(E-bias).
//
// Generated by test/gen_gf_add_fix.py (generalizes the exhaustively-verified
// gf8_add). Proper float add: significands carry 3 guard bits, alignment captures
// a sticky bit, the post-add leading 1 is found by priority and renormalized, and
// the 158-bit mantissa is rounded to nearest, ties-to-even. The running exponent is
// SIGNED and wide enough to tell underflow (exp<0) from a valid large exponent --
// the previous unit flushed valid exponents >= 2^(E-1) to zero. Verified by
// test/gf_arith_xcheck.py and test/gf_add_sweep.py.

`default_nettype none
module gf256_add (
    input  wire [255:0] a,
    input  wire [255:0] b,
    output reg  [255:0] result
);

    localparam [96:0] EXP_MAX = 97'd158456325028528675187087900671;
    localparam signed [98:0] EXP_MAX_S = 99'sd158456325028528675187087900671;

    wire             sign_a = a[255];
    wire [96:0]   exp_a  = a[254:158];
    wire [157:0]   mant_a = a[157:0];
    wire             sign_b = b[255];
    wire [96:0]   exp_b  = b[254:158];
    wire [157:0]   mant_b = b[157:0];

    wire is_zero_a = (exp_a == 97'd0) && (mant_a == 158'd0);
    wire is_zero_b = (exp_b == 97'd0) && (mant_b == 158'd0);
    wire is_inf_a  = (exp_a == EXP_MAX) && (mant_a == 158'd0);
    wire is_inf_b  = (exp_b == EXP_MAX) && (mant_b == 158'd0);
    wire is_nan_a  = (exp_a == EXP_MAX) && (mant_a != 158'd0);
    wire is_nan_b  = (exp_b == EXP_MAX) && (mant_b != 158'd0);

    wire a_larger = (exp_a > exp_b) || ((exp_a == exp_b) && (mant_a >= mant_b));

    reg        big_sign, small_sign, result_sign;
    reg [96:0] big_exp, small_exp;
    reg [157:0] big_m, small_m;
    reg [161:0] big_ext, small_ext, shifted;   // {1, mant, 3 guard bits}
    reg [97:0]  shamt;
    reg            sticky_shift;
    reg [162:0] sum_m;                          // room for add carry
    reg signed [98:0] rexp;
    reg [157:0]  mant_out;
    reg [158:0]   mant_rounded;                    // M+1 bits, catches overflow
    reg            guard, round_b, sticky, round_up;

    always @(*) begin
        big_sign = 0; small_sign = 0; result_sign = 0;
        big_exp = 0; small_exp = 0; big_m = 0; small_m = 0;
        big_ext = 0; small_ext = 0; shifted = 0; shamt = 0; sticky_shift = 0;
        sum_m = 0; rexp = 0; mant_out = 0; mant_rounded = 0;
        guard = 0; round_b = 0; sticky = 0; round_up = 0;

        if (is_nan_a || is_nan_b)
            result = 256'hFFFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000001;
        else if (is_inf_a && is_inf_b && (sign_a != sign_b))
            result = 256'hFFFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000001;
        else if (is_inf_a)
            result = sign_a ? 256'hFFFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000000 : 256'h7FFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000000;
        else if (is_inf_b)
            result = sign_b ? 256'hFFFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000000 : 256'h7FFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000000;
        else if (is_zero_a && is_zero_b)
            result = 256'h0;
        else if (is_zero_a)
            result = b;
        else if (is_zero_b)
            result = a;
        else begin
            if (a_larger) begin
                big_sign = sign_a; big_exp = exp_a; big_m = mant_a;
                small_sign = sign_b; small_exp = exp_b; small_m = mant_b;
            end else begin
                big_sign = sign_b; big_exp = exp_b; big_m = mant_b;
                small_sign = sign_a; small_exp = exp_a; small_m = mant_a;
            end

            big_ext   = {1'b1, big_m,   3'b0};
            small_ext = {1'b1, small_m, 3'b0};
            shamt     = big_exp - small_exp;

            if (shamt >= 162)
                begin shifted = 0; sticky_shift = |small_ext; end
            else begin
                shifted = small_ext >> shamt;
                sticky_shift = |(small_ext & ((162'd1 << shamt) - 162'd1));
            end

            result_sign = big_sign;
            rexp = $signed({2'b0, big_exp});

            if (big_sign == small_sign)
                sum_m = {1'b0, big_ext} + {1'b0, shifted};
            else
                sum_m = {1'b0, big_ext} - {1'b0, shifted};

            if (sum_m == 0) begin
                result = 256'h0;
            end else begin
                if (sum_m[162]) begin
                    rexp = rexp + 99'sd1;
                    mant_out = sum_m[161:4];
                    guard = sum_m[3]; round_b = sum_m[2]; sticky = (|sum_m[1:0]) | sticky_shift;
                end
                else if (sum_m[161]) begin
                    mant_out = sum_m[160:3];
                    guard = sum_m[2]; round_b = sum_m[1]; sticky = (|sum_m[0:0]) | sticky_shift;
                end
                else if (sum_m[160]) begin
                    rexp = rexp - 99'sd1;
                    mant_out = sum_m[159:2];
                    guard = sum_m[1]; round_b = sum_m[0]; sticky = sticky_shift;
                end
                else if (sum_m[159]) begin
                    rexp = rexp - 99'sd2;
                    mant_out = sum_m[158:1];
                    guard = sum_m[0]; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[158]) begin
                    rexp = rexp - 99'sd3;
                    mant_out = sum_m[157:0];
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[157]) begin
                    rexp = rexp - 99'sd4;
                    mant_out = {sum_m[156:0], 1'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[156]) begin
                    rexp = rexp - 99'sd5;
                    mant_out = {sum_m[155:0], 2'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[155]) begin
                    rexp = rexp - 99'sd6;
                    mant_out = {sum_m[154:0], 3'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[154]) begin
                    rexp = rexp - 99'sd7;
                    mant_out = {sum_m[153:0], 4'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[153]) begin
                    rexp = rexp - 99'sd8;
                    mant_out = {sum_m[152:0], 5'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[152]) begin
                    rexp = rexp - 99'sd9;
                    mant_out = {sum_m[151:0], 6'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[151]) begin
                    rexp = rexp - 99'sd10;
                    mant_out = {sum_m[150:0], 7'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[150]) begin
                    rexp = rexp - 99'sd11;
                    mant_out = {sum_m[149:0], 8'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[149]) begin
                    rexp = rexp - 99'sd12;
                    mant_out = {sum_m[148:0], 9'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[148]) begin
                    rexp = rexp - 99'sd13;
                    mant_out = {sum_m[147:0], 10'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[147]) begin
                    rexp = rexp - 99'sd14;
                    mant_out = {sum_m[146:0], 11'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[146]) begin
                    rexp = rexp - 99'sd15;
                    mant_out = {sum_m[145:0], 12'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[145]) begin
                    rexp = rexp - 99'sd16;
                    mant_out = {sum_m[144:0], 13'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[144]) begin
                    rexp = rexp - 99'sd17;
                    mant_out = {sum_m[143:0], 14'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[143]) begin
                    rexp = rexp - 99'sd18;
                    mant_out = {sum_m[142:0], 15'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[142]) begin
                    rexp = rexp - 99'sd19;
                    mant_out = {sum_m[141:0], 16'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[141]) begin
                    rexp = rexp - 99'sd20;
                    mant_out = {sum_m[140:0], 17'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[140]) begin
                    rexp = rexp - 99'sd21;
                    mant_out = {sum_m[139:0], 18'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[139]) begin
                    rexp = rexp - 99'sd22;
                    mant_out = {sum_m[138:0], 19'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[138]) begin
                    rexp = rexp - 99'sd23;
                    mant_out = {sum_m[137:0], 20'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[137]) begin
                    rexp = rexp - 99'sd24;
                    mant_out = {sum_m[136:0], 21'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[136]) begin
                    rexp = rexp - 99'sd25;
                    mant_out = {sum_m[135:0], 22'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[135]) begin
                    rexp = rexp - 99'sd26;
                    mant_out = {sum_m[134:0], 23'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[134]) begin
                    rexp = rexp - 99'sd27;
                    mant_out = {sum_m[133:0], 24'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[133]) begin
                    rexp = rexp - 99'sd28;
                    mant_out = {sum_m[132:0], 25'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[132]) begin
                    rexp = rexp - 99'sd29;
                    mant_out = {sum_m[131:0], 26'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[131]) begin
                    rexp = rexp - 99'sd30;
                    mant_out = {sum_m[130:0], 27'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[130]) begin
                    rexp = rexp - 99'sd31;
                    mant_out = {sum_m[129:0], 28'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[129]) begin
                    rexp = rexp - 99'sd32;
                    mant_out = {sum_m[128:0], 29'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[128]) begin
                    rexp = rexp - 99'sd33;
                    mant_out = {sum_m[127:0], 30'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[127]) begin
                    rexp = rexp - 99'sd34;
                    mant_out = {sum_m[126:0], 31'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[126]) begin
                    rexp = rexp - 99'sd35;
                    mant_out = {sum_m[125:0], 32'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[125]) begin
                    rexp = rexp - 99'sd36;
                    mant_out = {sum_m[124:0], 33'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[124]) begin
                    rexp = rexp - 99'sd37;
                    mant_out = {sum_m[123:0], 34'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[123]) begin
                    rexp = rexp - 99'sd38;
                    mant_out = {sum_m[122:0], 35'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[122]) begin
                    rexp = rexp - 99'sd39;
                    mant_out = {sum_m[121:0], 36'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[121]) begin
                    rexp = rexp - 99'sd40;
                    mant_out = {sum_m[120:0], 37'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[120]) begin
                    rexp = rexp - 99'sd41;
                    mant_out = {sum_m[119:0], 38'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[119]) begin
                    rexp = rexp - 99'sd42;
                    mant_out = {sum_m[118:0], 39'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[118]) begin
                    rexp = rexp - 99'sd43;
                    mant_out = {sum_m[117:0], 40'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[117]) begin
                    rexp = rexp - 99'sd44;
                    mant_out = {sum_m[116:0], 41'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[116]) begin
                    rexp = rexp - 99'sd45;
                    mant_out = {sum_m[115:0], 42'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[115]) begin
                    rexp = rexp - 99'sd46;
                    mant_out = {sum_m[114:0], 43'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[114]) begin
                    rexp = rexp - 99'sd47;
                    mant_out = {sum_m[113:0], 44'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[113]) begin
                    rexp = rexp - 99'sd48;
                    mant_out = {sum_m[112:0], 45'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[112]) begin
                    rexp = rexp - 99'sd49;
                    mant_out = {sum_m[111:0], 46'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[111]) begin
                    rexp = rexp - 99'sd50;
                    mant_out = {sum_m[110:0], 47'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[110]) begin
                    rexp = rexp - 99'sd51;
                    mant_out = {sum_m[109:0], 48'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[109]) begin
                    rexp = rexp - 99'sd52;
                    mant_out = {sum_m[108:0], 49'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[108]) begin
                    rexp = rexp - 99'sd53;
                    mant_out = {sum_m[107:0], 50'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[107]) begin
                    rexp = rexp - 99'sd54;
                    mant_out = {sum_m[106:0], 51'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[106]) begin
                    rexp = rexp - 99'sd55;
                    mant_out = {sum_m[105:0], 52'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[105]) begin
                    rexp = rexp - 99'sd56;
                    mant_out = {sum_m[104:0], 53'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[104]) begin
                    rexp = rexp - 99'sd57;
                    mant_out = {sum_m[103:0], 54'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[103]) begin
                    rexp = rexp - 99'sd58;
                    mant_out = {sum_m[102:0], 55'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[102]) begin
                    rexp = rexp - 99'sd59;
                    mant_out = {sum_m[101:0], 56'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[101]) begin
                    rexp = rexp - 99'sd60;
                    mant_out = {sum_m[100:0], 57'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[100]) begin
                    rexp = rexp - 99'sd61;
                    mant_out = {sum_m[99:0], 58'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[99]) begin
                    rexp = rexp - 99'sd62;
                    mant_out = {sum_m[98:0], 59'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[98]) begin
                    rexp = rexp - 99'sd63;
                    mant_out = {sum_m[97:0], 60'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[97]) begin
                    rexp = rexp - 99'sd64;
                    mant_out = {sum_m[96:0], 61'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[96]) begin
                    rexp = rexp - 99'sd65;
                    mant_out = {sum_m[95:0], 62'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[95]) begin
                    rexp = rexp - 99'sd66;
                    mant_out = {sum_m[94:0], 63'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[94]) begin
                    rexp = rexp - 99'sd67;
                    mant_out = {sum_m[93:0], 64'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[93]) begin
                    rexp = rexp - 99'sd68;
                    mant_out = {sum_m[92:0], 65'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[92]) begin
                    rexp = rexp - 99'sd69;
                    mant_out = {sum_m[91:0], 66'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[91]) begin
                    rexp = rexp - 99'sd70;
                    mant_out = {sum_m[90:0], 67'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[90]) begin
                    rexp = rexp - 99'sd71;
                    mant_out = {sum_m[89:0], 68'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[89]) begin
                    rexp = rexp - 99'sd72;
                    mant_out = {sum_m[88:0], 69'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[88]) begin
                    rexp = rexp - 99'sd73;
                    mant_out = {sum_m[87:0], 70'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[87]) begin
                    rexp = rexp - 99'sd74;
                    mant_out = {sum_m[86:0], 71'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[86]) begin
                    rexp = rexp - 99'sd75;
                    mant_out = {sum_m[85:0], 72'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[85]) begin
                    rexp = rexp - 99'sd76;
                    mant_out = {sum_m[84:0], 73'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[84]) begin
                    rexp = rexp - 99'sd77;
                    mant_out = {sum_m[83:0], 74'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[83]) begin
                    rexp = rexp - 99'sd78;
                    mant_out = {sum_m[82:0], 75'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[82]) begin
                    rexp = rexp - 99'sd79;
                    mant_out = {sum_m[81:0], 76'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[81]) begin
                    rexp = rexp - 99'sd80;
                    mant_out = {sum_m[80:0], 77'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[80]) begin
                    rexp = rexp - 99'sd81;
                    mant_out = {sum_m[79:0], 78'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[79]) begin
                    rexp = rexp - 99'sd82;
                    mant_out = {sum_m[78:0], 79'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[78]) begin
                    rexp = rexp - 99'sd83;
                    mant_out = {sum_m[77:0], 80'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[77]) begin
                    rexp = rexp - 99'sd84;
                    mant_out = {sum_m[76:0], 81'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[76]) begin
                    rexp = rexp - 99'sd85;
                    mant_out = {sum_m[75:0], 82'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[75]) begin
                    rexp = rexp - 99'sd86;
                    mant_out = {sum_m[74:0], 83'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[74]) begin
                    rexp = rexp - 99'sd87;
                    mant_out = {sum_m[73:0], 84'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[73]) begin
                    rexp = rexp - 99'sd88;
                    mant_out = {sum_m[72:0], 85'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[72]) begin
                    rexp = rexp - 99'sd89;
                    mant_out = {sum_m[71:0], 86'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[71]) begin
                    rexp = rexp - 99'sd90;
                    mant_out = {sum_m[70:0], 87'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[70]) begin
                    rexp = rexp - 99'sd91;
                    mant_out = {sum_m[69:0], 88'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[69]) begin
                    rexp = rexp - 99'sd92;
                    mant_out = {sum_m[68:0], 89'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[68]) begin
                    rexp = rexp - 99'sd93;
                    mant_out = {sum_m[67:0], 90'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[67]) begin
                    rexp = rexp - 99'sd94;
                    mant_out = {sum_m[66:0], 91'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[66]) begin
                    rexp = rexp - 99'sd95;
                    mant_out = {sum_m[65:0], 92'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[65]) begin
                    rexp = rexp - 99'sd96;
                    mant_out = {sum_m[64:0], 93'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[64]) begin
                    rexp = rexp - 99'sd97;
                    mant_out = {sum_m[63:0], 94'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[63]) begin
                    rexp = rexp - 99'sd98;
                    mant_out = {sum_m[62:0], 95'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[62]) begin
                    rexp = rexp - 99'sd99;
                    mant_out = {sum_m[61:0], 96'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[61]) begin
                    rexp = rexp - 99'sd100;
                    mant_out = {sum_m[60:0], 97'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[60]) begin
                    rexp = rexp - 99'sd101;
                    mant_out = {sum_m[59:0], 98'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[59]) begin
                    rexp = rexp - 99'sd102;
                    mant_out = {sum_m[58:0], 99'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[58]) begin
                    rexp = rexp - 99'sd103;
                    mant_out = {sum_m[57:0], 100'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[57]) begin
                    rexp = rexp - 99'sd104;
                    mant_out = {sum_m[56:0], 101'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[56]) begin
                    rexp = rexp - 99'sd105;
                    mant_out = {sum_m[55:0], 102'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[55]) begin
                    rexp = rexp - 99'sd106;
                    mant_out = {sum_m[54:0], 103'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[54]) begin
                    rexp = rexp - 99'sd107;
                    mant_out = {sum_m[53:0], 104'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[53]) begin
                    rexp = rexp - 99'sd108;
                    mant_out = {sum_m[52:0], 105'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[52]) begin
                    rexp = rexp - 99'sd109;
                    mant_out = {sum_m[51:0], 106'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[51]) begin
                    rexp = rexp - 99'sd110;
                    mant_out = {sum_m[50:0], 107'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[50]) begin
                    rexp = rexp - 99'sd111;
                    mant_out = {sum_m[49:0], 108'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[49]) begin
                    rexp = rexp - 99'sd112;
                    mant_out = {sum_m[48:0], 109'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[48]) begin
                    rexp = rexp - 99'sd113;
                    mant_out = {sum_m[47:0], 110'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[47]) begin
                    rexp = rexp - 99'sd114;
                    mant_out = {sum_m[46:0], 111'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[46]) begin
                    rexp = rexp - 99'sd115;
                    mant_out = {sum_m[45:0], 112'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[45]) begin
                    rexp = rexp - 99'sd116;
                    mant_out = {sum_m[44:0], 113'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[44]) begin
                    rexp = rexp - 99'sd117;
                    mant_out = {sum_m[43:0], 114'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[43]) begin
                    rexp = rexp - 99'sd118;
                    mant_out = {sum_m[42:0], 115'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[42]) begin
                    rexp = rexp - 99'sd119;
                    mant_out = {sum_m[41:0], 116'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[41]) begin
                    rexp = rexp - 99'sd120;
                    mant_out = {sum_m[40:0], 117'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[40]) begin
                    rexp = rexp - 99'sd121;
                    mant_out = {sum_m[39:0], 118'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[39]) begin
                    rexp = rexp - 99'sd122;
                    mant_out = {sum_m[38:0], 119'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[38]) begin
                    rexp = rexp - 99'sd123;
                    mant_out = {sum_m[37:0], 120'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[37]) begin
                    rexp = rexp - 99'sd124;
                    mant_out = {sum_m[36:0], 121'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[36]) begin
                    rexp = rexp - 99'sd125;
                    mant_out = {sum_m[35:0], 122'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[35]) begin
                    rexp = rexp - 99'sd126;
                    mant_out = {sum_m[34:0], 123'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[34]) begin
                    rexp = rexp - 99'sd127;
                    mant_out = {sum_m[33:0], 124'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[33]) begin
                    rexp = rexp - 99'sd128;
                    mant_out = {sum_m[32:0], 125'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[32]) begin
                    rexp = rexp - 99'sd129;
                    mant_out = {sum_m[31:0], 126'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[31]) begin
                    rexp = rexp - 99'sd130;
                    mant_out = {sum_m[30:0], 127'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[30]) begin
                    rexp = rexp - 99'sd131;
                    mant_out = {sum_m[29:0], 128'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[29]) begin
                    rexp = rexp - 99'sd132;
                    mant_out = {sum_m[28:0], 129'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[28]) begin
                    rexp = rexp - 99'sd133;
                    mant_out = {sum_m[27:0], 130'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[27]) begin
                    rexp = rexp - 99'sd134;
                    mant_out = {sum_m[26:0], 131'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[26]) begin
                    rexp = rexp - 99'sd135;
                    mant_out = {sum_m[25:0], 132'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[25]) begin
                    rexp = rexp - 99'sd136;
                    mant_out = {sum_m[24:0], 133'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[24]) begin
                    rexp = rexp - 99'sd137;
                    mant_out = {sum_m[23:0], 134'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[23]) begin
                    rexp = rexp - 99'sd138;
                    mant_out = {sum_m[22:0], 135'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[22]) begin
                    rexp = rexp - 99'sd139;
                    mant_out = {sum_m[21:0], 136'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[21]) begin
                    rexp = rexp - 99'sd140;
                    mant_out = {sum_m[20:0], 137'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[20]) begin
                    rexp = rexp - 99'sd141;
                    mant_out = {sum_m[19:0], 138'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[19]) begin
                    rexp = rexp - 99'sd142;
                    mant_out = {sum_m[18:0], 139'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[18]) begin
                    rexp = rexp - 99'sd143;
                    mant_out = {sum_m[17:0], 140'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[17]) begin
                    rexp = rexp - 99'sd144;
                    mant_out = {sum_m[16:0], 141'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[16]) begin
                    rexp = rexp - 99'sd145;
                    mant_out = {sum_m[15:0], 142'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[15]) begin
                    rexp = rexp - 99'sd146;
                    mant_out = {sum_m[14:0], 143'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[14]) begin
                    rexp = rexp - 99'sd147;
                    mant_out = {sum_m[13:0], 144'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[13]) begin
                    rexp = rexp - 99'sd148;
                    mant_out = {sum_m[12:0], 145'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[12]) begin
                    rexp = rexp - 99'sd149;
                    mant_out = {sum_m[11:0], 146'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[11]) begin
                    rexp = rexp - 99'sd150;
                    mant_out = {sum_m[10:0], 147'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[10]) begin
                    rexp = rexp - 99'sd151;
                    mant_out = {sum_m[9:0], 148'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[9]) begin
                    rexp = rexp - 99'sd152;
                    mant_out = {sum_m[8:0], 149'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[8]) begin
                    rexp = rexp - 99'sd153;
                    mant_out = {sum_m[7:0], 150'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[7]) begin
                    rexp = rexp - 99'sd154;
                    mant_out = {sum_m[6:0], 151'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[6]) begin
                    rexp = rexp - 99'sd155;
                    mant_out = {sum_m[5:0], 152'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[5]) begin
                    rexp = rexp - 99'sd156;
                    mant_out = {sum_m[4:0], 153'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[4]) begin
                    rexp = rexp - 99'sd157;
                    mant_out = {sum_m[3:0], 154'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[3]) begin
                    rexp = rexp - 99'sd158;
                    mant_out = {sum_m[2:0], 155'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[2]) begin
                    rexp = rexp - 99'sd159;
                    mant_out = {sum_m[1:0], 156'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else if (sum_m[1]) begin
                    rexp = rexp - 99'sd160;
                    mant_out = {sum_m[0:0], 157'd0};
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end
                else begin
                    mant_out = 158'd0;
                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;
                end

                round_up     = guard && (round_b || sticky || mant_out[0]);
                mant_rounded = {1'b0, mant_out} + (round_up ? 159'd1 : 159'd0);
                if (mant_rounded[158]) begin
                    rexp     = rexp + 99'sd1;
                    mant_out = 158'd0;
                end else begin
                    mant_out = mant_rounded[157:0];
                end

                if (rexp < 0)
                    result = result_sign ? 256'h8000000000000000000000000000000000000000000000000000000000000000 : 256'h0;
                else if (rexp >= EXP_MAX_S)
                    result = result_sign ? 256'hFFFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000000 : 256'h7FFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000000000000000000000;
                else if (rexp == 0 && mant_out == 158'd0)
                    result = result_sign ? 256'h8000000000000000000000000000000000000000000000000000000000000000 : 256'h0;
                else
                    result = {result_sign, rexp[96:0], mant_out};
            end
        end
    end

endmodule
